REPLACE VIEW MDM.ERR_CODE_DETAILS
AS
LOCKING ROW FOR ACCESS
SELECT LOAD_ID,
MKTNG_PGM_NBR,
SYS_ERR_CODE AS ERR_DESC,
COUNT(DISTINCT REGIS_CNSMR_ID_VAL) ERROR_CODE_NBR
FROM MDM.ERR_PRSNA_STG
GROUP BY 1,2,3;