REPLACE VIEW MDM.V_ADDRESS 
	AS LOCKING ROW FOR ACCESS

	SELECT
	AD.REGIS_PRSNA_ID
	,AD.SUBSCRPTN_OPT_IND
	,AD.CNSMR_CHCE_DATETM
	,COALESCE(AD.ADDR_LINE_1_TXT,'') || COALESCE(AD.ADDR_LINE_2_TXT,'') || COALESCE(AD.CITY_NAME,'') || COALESCE(AD.POSTL_AREA_CODE,'') AS ADDR_LINE_1_TXT
	,AD.ADDR_LINE_2_TXT
	,AD.CITY_NAME
	,AD.POSTL_AREA_CODE
	,AD.CNTRY_CODE
	,AD.CNTCT_POINT_CATEG_CODE
	,AD.SUBSCRPTN_OPT_NBR
	,AD.MKTNG_PGM_NBR
	,AD.LEGAL_ENT_NBR
	,SO.SUBSCRPTN_OPT_NAME
	,SO.SUBSCRPTN_OPT_STMT_TXT
	,NULL (INTEGER)   AS  SYS_TARGET_ID
	,NULL (VARCHAR(25))  AS SYS_AUTH_ID
	,NULL (VARCHAR(25))  AS SYS_SOURCE
	,NULL (VARCHAR(70))  AS SYS_CREATED_BY
	,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
	,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
	,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
	,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
	,NULL (VARCHAR(25))  AS SYS_NC_TYPE
	,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
	,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY                                                           
	FROM MDM.REGIS_PRSNA_POSTL_ADDR AD
	LEFT JOIN
	(SEL * FROM  MDM.SUBSCRPTN_OPT ) SO
	ON
	AD.MKTNG_PGM_NBR=SO.MKTNG_PGM_NBR
	AND 
	AD.LEGAL_ENT_NBR=SO.LEGAL_ENT_NBR
	AND
	AD.SUBSCRPTN_OPT_NBR=SO.SUBSCRPTN_OPT_NBR;