REPLACE	VIEW MDM.V_CAMPAIGN
		AS
		LOCKING ROW FOR ACCESS
		SELECT
		A.REGIS_PRSNA_ID
		,A.CAMPAIGN_ID
		,A.PROMOTION_EMAIL_ADDR_TXT
		,A.MKTNG_PGM_NBR
		,C.MKTNG_PGM_DESC
		,B.CAMPAIGN_NAME
		,B.CAMPAIGN_CREATION_DT CAMPAIGN_EXEC_DATE
		,NULL (INTEGER)   AS  SYS_TARGET_ID
		 ,NULL (VARCHAR(25))  AS SYS_AUTH_ID
		 ,NULL (VARCHAR(25))  AS SYS_SOURCE
		 ,NULL (VARCHAR(70))  AS SYS_CREATED_BY
		 ,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
		 ,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
		 ,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
		 ,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
		 ,NULL (VARCHAR(25))  AS SYS_NC_TYPE
		 ,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
		 ,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   
			FROM CNSMR_PROMOTION A INNER JOIN CAMPAIGN B 
		ON	TRIM(A.CAMPAIGN_ID) = B.CAMPAIGN_ID 
		AND	A.MKTNG_PGM_NBR = B.MKTNG_PGM_NBR INNER JOIN MKTNG_PGM C 
		ON	A.MKTNG_PGM_NBR = C.MKTNG_PGM_NBR;