REPLACE VIEW MDM.V_DATA_SRCE    
  AS LOCKING ROW FOR ACCESS   
SELECT   
   DS.AGNCY_NBR   
  ,DS.AGNCY_NM   
  ,DS.AGNCY_DESC   
  ,WS.WEB_SITE_URL_TXT   
  ,RP.REGIS_PRSNA_ID   
  ,RP.MKTNG_PGM_NBR   
  ,RP.LEGAL_ENT_NBR   
  ,NULL (INTEGER)   AS  SYS_TARGET_ID   
  ,NULL (VARCHAR(25))  AS SYS_AUTH_ID   
  ,NULL (VARCHAR(25))  AS SYS_SOURCE   
  ,NULL (VARCHAR(70))  AS SYS_CREATED_BY   
  ,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE   
  ,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE   
  ,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY   
  ,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE   
  ,NULL (VARCHAR(25))  AS SYS_NC_TYPE   
  ,NULL (VARCHAR(10000))  AS SYS_ERR_CODE   
  ,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY      
  FROM MDM.REGIS_PRSNA RP   
  INNER JOIN   
  MDM.AGNCY DS   
  ON   
  RP.SYS_TARGET_ID=DS.AGNCY_NBR  
  INNER JOIN   
  MDM.WEB_SITE WS   
  ON   
  DS.AGNCY_NBR= WS.AGNCY_NBR;