REPLACE VIEW MDM.V_GDPR_EDIT_REGIS
 AS LOCKING ROW FOR ACCESS

 SELECT   DISTINCT GDPR_SRCH_RSLT.GDPR_SRCH_TYPE_CODE,
 GDPR_RQST.GDPR_CASE_ID,
 GDPR_SRCH_RSLT.MKTNG_PGM_NBR,
 GDPR_SRCH_RSLT.REGIS_PRSNA_ID,
 GDPR_RQST_TYPE.GDPR_RQST_TYPE_NAME,
 GDPR_RQST_STATUS.GDPR_RQST_STATUS_NAME,
 GDPR_RQST.GVN_NAME,
 GDPR_RQST.MID_NAME,
 GDPR_RQST.FAMLY_NAME,
 GDPR_RQST.NAME_SUFFX_TXT,
 GDPR_RQST.FULL_NAME,
 MKTNG_PGM.MKTNG_PGM_DESC,
 GDPR_RQST.REGIS_CNSMR_ID_VAL,
 GDPR_RQST.DATA_SRCE_NBR, 
 GDPR_RQST.NATIONAL_ID_NBR,
 GDPR_RQST.EMAIL_ADDR_TXT,
 GDPR_RQST.FULL_PHONE_NUM,
 COALESCE(GDPR_RQST.ADDR_LINE_1_TXT,'')||' '||COALESCE(GDPR_RQST.ADDR_LINE_2_TXT,'')||' '||COALESCE(GDPR_RQST.ADDR_LINE_3_TXT,'')||' '||COALESCE(GDPR_RQST.CITY_NAME,'')||' '||COALESCE(GDPR_RQST.TERR_NAME,'')||' '||COALESCE(GDPR_RQST.CNTRY_CODE,'')||' '||COALESCE(GDPR_RQST.POSTL_AREA_CODE,'') 
 AS FULLADDRESS ,
 GDPR_RQST.GDPR_RQST_FULFLMT_DATETM,
 GDPR_RQST.GDPR_RQST_CRTN_DATETM, 
 GDPR_RQST.GDPR_RQST_IDNTY_VFYD_DATETM
 ,NULL (INTEGER)   AS  SYS_TARGET_ID
 ,NULL (VARCHAR(25))  AS SYS_AUTH_ID
 ,NULL (VARCHAR(25))  AS SYS_SOURCE
 ,NULL (VARCHAR(70))  AS SYS_CREATED_BY
 ,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
 ,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
 ,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
 ,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
 ,NULL (VARCHAR(25))  AS SYS_NC_TYPE
 ,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
 ,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY  
 FROM    GDPR_RQST
 LEFT JOIN
 GDPR_RQST_TYPE ON
 GDPR_RQST.GDPR_RQST_TYPE_CD=GDPR_RQST_TYPE.GDPR_RQST_TYPE_CD 
 LEFT JOIN
 GDPR_RQST_STATUS ON 
 GDPR_RQST.GDPR_RQST_STATUS_CD=GDPR_RQST_STATUS.GDPR_RQST_STATUS_CD 
 LEFT JOIN 
 MKTNG_PGM ON 
 GDPR_RQST.MKTNG_PGM_NBR=MKTNG_PGM.MKTNG_PGM_NBR 
 LEFT JOIN
 GDPR_SRCH_RSLT ON 
 GDPR_RQST.GDPR_CASE_ID= GDPR_SRCH_RSLT.GDPR_CASE_ID 
 AND GDPR_SRCH_RSLT.PROC_IND='Y'