REPLACE VIEW MDM.V_GDPR_Review
(GDPR_CASE_ID
,GVN_NAME
,MID_NAME
,FAMLY_NAME
,FULL_NAME
,ADDR_LINE_1_TXT
,ADDR_LINE_2_TXT
,ADDR_LINE_3_TXT
,TERR_NAME
,CITY_NAME
,MKTNG_PGM_NBR
,CNTRY_CODE
,GDPR_CASE_OWNR_CNTCT_NBR
,GDPR_RQST_TYPE_CD
,POSTL_AREA_CODE
,GDPR_RQST_CRTN_DATETM         
,EMAIL_ADDR_TXT
,GDPR_RQST_STATUS_CD
,FULL_PHONE_NUM
,DATA_SRCE_NBR
,NAME_SUFFX_TXT 
,REGIS_CNSMR_ID_VAL
,NATIONAL_ID_NBR
,SR_NBR
,GDPR_RQST_FULFLMT_DATETM
,GDPR_RQST_IDNTY_VFYD_DATETM
,GDPR_RQST_TYPE_NAME
,GDPR_RQST_STATUS_NAME
,CNTRY_NAME
,MKTNG_PGM_DESC
  ,A.SYS_TARGET_ID,   
  SYS_AUTH_ID,   
  SYS_SOURCE,   
  SYS_CREATED_BY,   
  SYS_CREATION_DATE,   
  SYS_ENT_STATE,   
  SYS_LAST_MODIFIED_BY,   
  SYS_LAST_MODIFIED_DATE,   
  SYS_NC_TYPE,   
  SYS_ERR_CODE,   
  SYS_ERR_SVRTY,
 TEMPORAL_TIME
  )
AS 

LOCKING ROW FOR ACCESS  SEL
A.GDPR_CASE_ID
,A.GVN_NAME
,A.MID_NAME
,A.FAMLY_NAME
,A.FULL_NAME
,A.ADDR_LINE_1_TXT
,A.ADDR_LINE_2_TXT
,A.ADDR_LINE_3_TXT
,A.TERR_NAME
,A.CITY_NAME
,A.MKTNG_PGM_NBR
,A.CNTRY_CODE
,A.GDPR_CASE_OWNR_CNTCT_NBR
,A.GDPR_RQST_TYPE_CD
,A.POSTL_AREA_CODE
,A.GDPR_RQST_CRTN_DATETM         
,A.EMAIL_ADDR_TXT
,A.GDPR_RQST_STATUS_CD
,A.FULL_PHONE_NUM
,A.DATA_SRCE_NBR
,A.NAME_SUFFX_TXT 
,A.REGIS_CNSMR_ID_VAL
,A.NATIONAL_ID_NBR
,F.SR_NBR
,A.GDPR_RQST_FULFLMT_DATETM
,A.GDPR_RQST_IDNTY_VFYD_DATETM
,C.GDPR_RQST_TYPE_NAME
,B.GDPR_RQST_STATUS_NAME
,D.CNTRY_NAME
,E.MKTNG_PGM_DESC
  ,A.SYS_TARGET_ID,   
  A.SYS_AUTH_ID,   
  A.SYS_SOURCE,   
  A.SYS_CREATED_BY,   
  A.SYS_CREATION_DATE,   
  A.SYS_ENT_STATE,   
  A.SYS_LAST_MODIFIED_BY,   
  A.SYS_LAST_MODIFIED_DATE,   
  A.SYS_NC_TYPE,   
  A.SYS_ERR_CODE,   
  A.SYS_ERR_SVRTY ,
  A.TEMPORAL_TIME
FROM icrm_tbl.GDPR_RQST A LEFT OUTER JOIN icrm_tbl.GDPR_RQST_STATUS B
ON A.GDPR_RQST_STATUS_CD= B.GDPR_RQST_STATUS_CD
 LEFT OUTER JOIN icrm_tbl.GDPR_RQST_TYPE  C
ON A.GDPR_RQST_TYPE_CD= C.GDPR_RQST_TYPE_CD
LEFT OUTER JOIN icrm_tbl.CNTRY D
ON A.CNTRY_CODE= D.CNTRY_CODE
LEFT OUTER JOIN icrm_tbl.MKTNG_PGM E
ON A.MKTNG_PGM_NBR= E.MKTNG_PGM_NBR
LEFT OUTER JOIN icrm_tbl.CNTCT F
ON A.GDPR_CASE_OWNR_CNTCT_NBR= F.CNTCT_NBR
WHERE A.GDPR_RQST_STATUS_CD<>'CP';