REPLACE	VIEW MDM.V_LEGACY_CAMPAIGN
	AS
	LOCKING ROW FOR ACCESS
	SELECT
	 A.REGIS_PRSNA_ID
    ,A.CAMPAIGN_RUN_DTTM as SELECTION_DATE
	,B.CAMPAIGN_NAME as CAMPAIGN_NAME
    ,A.MKTNG_PGM_NBR
    ,D.COMM_CHNL_NAME as CAMPAIGN_CHANNEL
    ,E.MKTNG_PGM_NAME	
	,NULL (INTEGER)   AS  SYS_TARGET_ID
	 ,NULL (VARCHAR(25))  AS SYS_AUTH_ID
	 ,NULL (VARCHAR(25))  AS SYS_SOURCE
	 ,NULL (VARCHAR(70))  AS SYS_CREATED_BY
	 ,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
	 ,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
	 ,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
	 ,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
	 ,NULL (VARCHAR(25))  AS SYS_NC_TYPE
	 ,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
	 ,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   
		FROM 
		 MDM.CAMPAIGN_SGMNT_CNSMR   A 	 
        INNER JOIN MDM.CAMPAIGN B 
	ON	A.CAMPAIGN_ID = B.CAMPAIGN_ID
	INNER JOIN MDM.COMM_CHNL D
	ON A.COMM_CHNL_CODE=D.COMM_CHNL_CODE
	INNER JOIN MDM.MKTNG_PGM E
	ON A.MKTNG_PGM_NBR=E.MKTNG_PGM_NBR	;