REPLACE VIEW MDM.V_MATCHD_CNSMR_PRSNA
AS
LOCKING ROW FOR ACCESS
SELECT 
REGIS_PRSNA_1.MATCHD_CNSMR_PRSNA_ID
,MATCHD_CNSMR_PRSNA_1.HSHLD_PRSNA_ID 
,REGIS_PRSNA_1.REGIS_PRSNA_ID 
,REGIS_PRSNA_1.MKTNG_PGM_NBR  
,REGIS_PRSNA_1.REGIS_CNSMR_ID_VAL
,REGIS_PRSNA_1.GVN_NAME
,REGIS_PRSNA_1.MID_NAME
,REGIS_PRSNA_1.FAMLY_NAME
,REGIS_PRSNA_1.FAMLY_NAME ||','|| REGIS_PRSNA_1.GVN_NAME AS FULL_NAME
,REGIS_PRSNA_1.BRTH_DATE
,REGIS_PRSNA_1.CNTRY_CODE AS CNTRY_NAME
,REGIS_PRSNA_1.NATIONAL_ID_NBR
,REGIS_PRSNA_1.PRSNA_STATUS_CODE
,TRIM(REGIS_PRSNA_1.NAME_PREFX_TXT) AS NAME_PREFX_TXT
,TRIM(REGIS_PRSNA_1.NAME_SUFFX_TXT) AS NAME_SUFFX_TXT
,REGIS_PRSNA_1.CNSMR_USER_NAME
,REGIS_PRSNA_1.GENDR_IND
,REGIS_PRSNA_1.LEGAL_ENT_NBR
,REGIS_PRSNA_1.LANG_CODE AS LANG_CODE
,REGIS_PRSNA_1.LANG_CODE AS LANG_NAME
,REGIS_PRSNA_1.DATA_ORIGIN_SRCE_NBR 
,PRSNA_POSTL_ADDR_1.ADDR_LINE_1_TXT
,PRSNA_POSTL_ADDR_1.ADDR_LINE_2_TXT
,PRSNA_POSTL_ADDR_1.ADDR_LINE_3_TXT
,PRSNA_POSTL_ADDR_1.STRET_NUM
,PRSNA_POSTL_ADDR_1.STRET_NAME
,PRSNA_POSTL_ADDR_1.APT_NUM
,PRSNA_POSTL_ADDR_1.PO_BOX_NUM
,PRSNA_POSTL_ADDR_1.CITY_NAME
,PRSNA_POSTL_ADDR_1.TERR_CODE
,PRSNA_POSTL_ADDR_1.TERR_CODE AS TERR_NAME
,PRSNA_POSTL_ADDR_1.POSTL_AREA_CODE
,PRSNA_POSTL_ADDR_1.WIN_KEY
,COALESCE(PRSNA_POSTL_ADDR_1.ADDR_LINE_1_TXT,'') ||  ' ' ||
COALESCE(PRSNA_POSTL_ADDR_1.ADDR_LINE_2_TXT,'') ||   ' ' ||
COALESCE(PRSNA_POSTL_ADDR_1.CITY_NAME,'') ||  ' ' ||
COALESCE(PRSNA_POSTL_ADDR_1.POSTL_AREA_CODE,'') AS FULL_ADDRESS
,MKTNG_PGM_1.MKTNG_PGM_NAME
,NULL (INTEGER)   AS  SYS_TARGET_ID
,NULL (VARCHAR(25))  AS SYS_AUTH_ID
,NULL (VARCHAR(25))  AS SYS_SOURCE
,NULL (VARCHAR(70))  AS SYS_CREATED_BY
,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
,NULL (VARCHAR(25))  AS SYS_NC_TYPE
,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   
,NULL (VARCHAR(200))  AS EMAIL_ADDR_TXT_1 
,NULL (SMALLINT) AS PHONE_CNTRY_NBR_1
,NULL (SMALLINT) AS PHONE_AREA_NBR_1
,NULL (SMALLINT) AS PHONE_EXCHG_NBR_1
,NULL  (BIGINT) AS PHONE_LINE_NBR_1
,NULL (VARCHAR(20)) AS PHONE_EXTSN_NUM_1
,NULL  (VARCHAR(20))  AS FULL_PHONE_NUM_1
,PRSNA_POSTL_ADDR_1.SUBSCRPTN_OPT_NBR AS SUBSCRPTN_OPT_NBR
,PRSNA_POSTL_ADDR_1.SUBSCRPTN_OPT_IND AS SUBSCRPTN_OPT_IND
,PRSNA_POSTL_ADDR_1.CNSMR_CHCE_DATETM  AS CNSMR_CHCE_DATETM
,'A'  CNTCT_POINT_TYPE_CODE
,'ADDRESS'  CNTCT_POINT_TYPE
,PRSNA_POSTL_ADDR_1.CNTCT_POINT_CATEG_CODE  AS CNTCT_POINT_CATEG_CODE
,CNTCT_POINT_CATEG_1.CNTCT_POINT_CATEG_NAME  AS CNTCT_POINT_CATEG_NAME
,SUBSCRPTN_OPT_1.SUBSCRPTN_OPT_NAME
FROM REGIS_PRSNA REGIS_PRSNA_1
JOIN REGIS_PRSNA_POSTL_ADDR PRSNA_POSTL_ADDR_1
ON REGIS_PRSNA_1.REGIS_PRSNA_ID = PRSNA_POSTL_ADDR_1.REGIS_PRSNA_ID
AND REGIS_PRSNA_1.MKTNG_PGM_NBR = PRSNA_POSTL_ADDR_1.MKTNG_PGM_NBR
JOIN MKTNG_PGM MKTNG_PGM_1
ON REGIS_PRSNA_1.MKTNG_PGM_NBR = MKTNG_PGM_1.MKTNG_PGM_NBR
JOIN SUBSCRPTN_OPT SUBSCRPTN_OPT_1
ON PRSNA_POSTL_ADDR_1.SUBSCRPTN_OPT_NBR=SUBSCRPTN_OPT_1.SUBSCRPTN_OPT_NBR
AND PRSNA_POSTL_ADDR_1.MKTNG_PGM_NBR = SUBSCRPTN_OPT_1.MKTNG_PGM_NBR
JOIN CNTCT_POINT_CATEG CNTCT_POINT_CATEG_1
ON PRSNA_POSTL_ADDR_1.CNTCT_POINT_CATEG_CODE=CNTCT_POINT_CATEG_1.CNTCT_POINT_CATEG_CODE
JOIN MATCHD_CNSMR_PRSNA MATCHD_CNSMR_PRSNA_1
ON REGIS_PRSNA_1.MATCHD_CNSMR_PRSNA_ID=MATCHD_CNSMR_PRSNA_1.MATCHD_CNSMR_PRSNA_ID
UNION ALL
SELECT 
REGIS_PRSNA_1.MATCHD_CNSMR_PRSNA_ID
,MATCHD_CNSMR_PRSNA_1.HSHLD_PRSNA_ID 
,REGIS_PRSNA_1.REGIS_PRSNA_ID 
,REGIS_PRSNA_1.MKTNG_PGM_NBR  
,REGIS_PRSNA_1.REGIS_CNSMR_ID_VAL
,REGIS_PRSNA_1.GVN_NAME
,REGIS_PRSNA_1.MID_NAME
,REGIS_PRSNA_1.FAMLY_NAME
,REGIS_PRSNA_1.FAMLY_NAME ||','|| REGIS_PRSNA_1.GVN_NAME AS FULL_NAME
,REGIS_PRSNA_1.BRTH_DATE
,REGIS_PRSNA_1.CNTRY_CODE AS CNTRY_NAME
,REGIS_PRSNA_1.NATIONAL_ID_NBR
,REGIS_PRSNA_1.PRSNA_STATUS_CODE
,TRIM(REGIS_PRSNA_1.NAME_PREFX_TXT) AS NAME_PREFX_TXT
,TRIM(REGIS_PRSNA_1.NAME_SUFFX_TXT) AS NAME_SUFFX_TXT
,REGIS_PRSNA_1.CNSMR_USER_NAME
,REGIS_PRSNA_1.GENDR_IND
,REGIS_PRSNA_1.LEGAL_ENT_NBR
,REGIS_PRSNA_1.LANG_CODE AS LANG_CODE
,REGIS_PRSNA_1.LANG_CODE AS LANG_NAME
,REGIS_PRSNA_1.DATA_ORIGIN_SRCE_NBR 
, NULL (VARCHAR(500) ) AS ADDR_LINE_1_TXT
,NULL  (VARCHAR(500) )AS ADDR_LINE_2_TXT
,NULL  (VARCHAR(500) )AS ADDR_LINE_3_TXT
,NULL (VARCHAR(20))AS STRET_NUM
,NULL ( VARCHAR(100) )AS STRET_NAME
,NULL (VARCHAR(20) )AS APT_NUM
,NULL (VARCHAR(20) )AS PO_BOX_NUM
,NULL ( VARCHAR(100) )AS CITY_NAME
,NULL ( CHAR(8) )AS TERR_CODE
,NULL ( VARCHAR(100))AS  TERR_NAME
,NULL (VARCHAR(20)) AS POSTL_AREA_CODE
,NULL ( VARCHAR(100) )AS WIN_KEY
,NULL  (VARCHAR(10000))  AS FULL_ADDRESS
,MKTNG_PGM_1.MKTNG_PGM_NAME
,NULL (INTEGER)   AS  SYS_TARGET_ID
,NULL (VARCHAR(25))  AS SYS_AUTH_ID
,NULL (VARCHAR(25))  AS SYS_SOURCE
,NULL (VARCHAR(70))  AS SYS_CREATED_BY
,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
,NULL (VARCHAR(25))  AS SYS_NC_TYPE
,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   
,NULL (VARCHAR(200))  AS EMAIL_ADDR_TXT_1 
,PRSNA_PHONE_1.PHONE_CNTRY_NBR AS PHONE_CNTRY_NBR_1
,PRSNA_PHONE_1.PHONE_AREA_NBR  AS PHONE_AREA_NBR_1
,PRSNA_PHONE_1.PHONE_EXCHG_NBR AS PHONE_EXCHG_NBR_1
,PRSNA_PHONE_1.PHONE_LINE_NBR  AS PHONE_LINE_NBR_1
,PRSNA_PHONE_1.PHONE_EXTSN_NUM AS PHONE_EXTSN_NUM_1
,PRSNA_PHONE_1.FULL_PHONE_NUM  AS FULL_PHONE_NUM_1
,PRSNA_PHONE_1.SUBSCRPTN_OPT_NBR AS SUBSCRPTN_OPT_NBR
,PRSNA_PHONE_1.SUBSCRPTN_OPT_IND AS SUBSCRPTN_OPT_IND
,PRSNA_PHONE_1.CNSMR_CHCE_DATETM  AS CNSMR_CHCE_DATETM
,'P'  CNTCT_POINT_TYPE_CODE
,'PHONE'  CNTCT_POINT_TYPE
,PRSNA_PHONE_1.CNTCT_POINT_CATEG_CODE  AS CNTCT_POINT_CATEG_CODE
,CNTCT_POINT_CATEG_1.CNTCT_POINT_CATEG_NAME  AS CNTCT_POINT_CATEG_NAME
,SUBSCRPTN_OPT_1.SUBSCRPTN_OPT_NAME
FROM REGIS_PRSNA REGIS_PRSNA_1
JOIN REGIS_PRSNA_PHONE PRSNA_PHONE_1
ON REGIS_PRSNA_1.REGIS_PRSNA_ID = PRSNA_PHONE_1.REGIS_PRSNA_ID
AND REGIS_PRSNA_1.MKTNG_PGM_NBR = PRSNA_PHONE_1.MKTNG_PGM_NBR
JOIN MKTNG_PGM MKTNG_PGM_1
ON REGIS_PRSNA_1.MKTNG_PGM_NBR = MKTNG_PGM_1.MKTNG_PGM_NBR
JOIN SUBSCRPTN_OPT SUBSCRPTN_OPT_1
ON PRSNA_PHONE_1.SUBSCRPTN_OPT_NBR=SUBSCRPTN_OPT_1.SUBSCRPTN_OPT_NBR
AND PRSNA_PHONE_1.MKTNG_PGM_NBR = SUBSCRPTN_OPT_1.MKTNG_PGM_NBR
JOIN CNTCT_POINT_CATEG CNTCT_POINT_CATEG_1
ON PRSNA_PHONE_1.CNTCT_POINT_CATEG_CODE=CNTCT_POINT_CATEG_1.CNTCT_POINT_CATEG_CODE
JOIN MATCHD_CNSMR_PRSNA MATCHD_CNSMR_PRSNA_1
ON REGIS_PRSNA_1.MATCHD_CNSMR_PRSNA_ID=MATCHD_CNSMR_PRSNA_1.MATCHD_CNSMR_PRSNA_ID
UNION ALL
SELECT 
REGIS_PRSNA_1.MATCHD_CNSMR_PRSNA_ID
,MATCHD_CNSMR_PRSNA_1.HSHLD_PRSNA_ID 
,REGIS_PRSNA_1.REGIS_PRSNA_ID 
,REGIS_PRSNA_1.MKTNG_PGM_NBR  
,REGIS_PRSNA_1.REGIS_CNSMR_ID_VAL
,REGIS_PRSNA_1.GVN_NAME
,REGIS_PRSNA_1.MID_NAME
,REGIS_PRSNA_1.FAMLY_NAME
,REGIS_PRSNA_1.FAMLY_NAME ||','|| REGIS_PRSNA_1.GVN_NAME AS FULL_NAME
,REGIS_PRSNA_1.BRTH_DATE
,REGIS_PRSNA_1.CNTRY_CODE AS CNTRY_NAME
,REGIS_PRSNA_1.NATIONAL_ID_NBR
,REGIS_PRSNA_1.PRSNA_STATUS_CODE
,TRIM(REGIS_PRSNA_1.NAME_PREFX_TXT) AS NAME_PREFX_TXT
,TRIM(REGIS_PRSNA_1.NAME_SUFFX_TXT) AS NAME_SUFFX_TXT
,REGIS_PRSNA_1.CNSMR_USER_NAME
,REGIS_PRSNA_1.GENDR_IND
,REGIS_PRSNA_1.LEGAL_ENT_NBR
,REGIS_PRSNA_1.LANG_CODE AS LANG_CODE
,REGIS_PRSNA_1.LANG_CODE AS LANG_NAME
,REGIS_PRSNA_1.DATA_ORIGIN_SRCE_NBR 
, NULL (VARCHAR(500) ) AS ADDR_LINE_1_TXT
,NULL  (VARCHAR(500) )AS ADDR_LINE_2_TXT
,NULL  (VARCHAR(500) )AS ADDR_LINE_3_TXT
,NULL (VARCHAR(20))AS STRET_NUM
,NULL ( VARCHAR(100) )AS STRET_NAME
,NULL (VARCHAR(20) )AS APT_NUM
,NULL (VARCHAR(20) )AS PO_BOX_NUM
,NULL ( VARCHAR(100) )AS CITY_NAME
,NULL ( CHAR(8) )AS TERR_CODE
,NULL ( VARCHAR(100))AS  TERR_NAME
,NULL (VARCHAR(20)) AS POSTL_AREA_CODE
,NULL ( VARCHAR(100) )AS WIN_KEY
,NULL  (VARCHAR(10000))  AS FULL_ADDRESS
,MKTNG_PGM_1.MKTNG_PGM_NAME
,NULL (INTEGER)   AS  SYS_TARGET_ID
,NULL (VARCHAR(25))  AS SYS_AUTH_ID
,NULL (VARCHAR(25))  AS SYS_SOURCE
,NULL (VARCHAR(70))  AS SYS_CREATED_BY
,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
,NULL (VARCHAR(25))  AS SYS_NC_TYPE
,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   
,PRSNA_EMAIL_ADDR_1.EMAIL_ADDR_TXT AS EMAIL_ADDR_TXT_1 
,NULL (SMALLINT) AS PHONE_CNTRY_NBR_1
,NULL (SMALLINT) AS PHONE_AREA_NBR_1
,NULL (SMALLINT) AS PHONE_EXCHG_NBR_1
,NULL  (BIGINT) AS PHONE_LINE_NBR_1
,NULL (VARCHAR(20)) AS PHONE_EXTSN_NUM_1
,NULL  (VARCHAR(20))  AS FULL_PHONE_NUM_1
,PRSNA_EMAIL_ADDR_1.SUBSCRPTN_OPT_NBR AS SUBSCRPTN_OPT_NBR
,PRSNA_EMAIL_ADDR_1.SUBSCRPTN_OPT_IND AS SUBSCRPTN_OPT_IND
,PRSNA_EMAIL_ADDR_1.CNSMR_CHCE_DATETM  AS CNSMR_CHCE_DATETM
,'E'  CNTCT_POINT_TYPE_CODE
,'EMAIL'  CNTCT_POINT_TYPE
,PRSNA_EMAIL_ADDR_1.CNTCT_POINT_CATEG_CODE  AS CNTCT_POINT_CATEG_CODE
,CNTCT_POINT_CATEG_1.CNTCT_POINT_CATEG_NAME  AS CNTCT_POINT_CATEG_NAME
,SUBSCRPTN_OPT_1.SUBSCRPTN_OPT_NAME
FROM REGIS_PRSNA REGIS_PRSNA_1
JOIN REGIS_PRSNA_EMAIL_ADDR PRSNA_EMAIL_ADDR_1
ON REGIS_PRSNA_1.REGIS_PRSNA_ID = PRSNA_EMAIL_ADDR_1.REGIS_PRSNA_ID
AND REGIS_PRSNA_1.MKTNG_PGM_NBR = PRSNA_EMAIL_ADDR_1.MKTNG_PGM_NBR
JOIN MKTNG_PGM MKTNG_PGM_1
ON REGIS_PRSNA_1.MKTNG_PGM_NBR = MKTNG_PGM_1.MKTNG_PGM_NBR
JOIN SUBSCRPTN_OPT SUBSCRPTN_OPT_1
ON PRSNA_EMAIL_ADDR_1.SUBSCRPTN_OPT_NBR=SUBSCRPTN_OPT_1.SUBSCRPTN_OPT_NBR
AND PRSNA_EMAIL_ADDR_1.MKTNG_PGM_NBR = SUBSCRPTN_OPT_1.MKTNG_PGM_NBR
JOIN CNTCT_POINT_CATEG CNTCT_POINT_CATEG_1
ON PRSNA_EMAIL_ADDR_1.CNTCT_POINT_CATEG_CODE=CNTCT_POINT_CATEG_1.CNTCT_POINT_CATEG_CODE
JOIN MATCHD_CNSMR_PRSNA MATCHD_CNSMR_PRSNA_1
ON REGIS_PRSNA_1.MATCHD_CNSMR_PRSNA_ID=MATCHD_CNSMR_PRSNA_1.MATCHD_CNSMR_PRSNA_ID
;