REPLACE VIEW MDM.V_MATCHD_CNSMR_PRSNA_DTL
AS
LOCKING ROW FOR ACCESS
SELECT
 LEGAL_ENT_PRSNA_1.GVN_NAME
,LEGAL_ENT_PRSNA_1.FAMLY_NAME
,TRIM(LEGAL_ENT_PRSNA_1.FAMLY_NAME) ||','|| TRIM(LEGAL_ENT_PRSNA_1.GVN_NAME) as FULL_NAME     
,LEGAL_ENT_PRSNA_1.MATCHD_CNSMR_PRSNA_ID
,LEGAL_ENT_PRSNA_1.GENDR_IND
,LEGAL_ENT_PRSNA_1.BRTH_DATE
,COALESCE(TRIM(PRSNA_POSTL_ADDR_1.ADDR_LINE_1_TXT),'') ||    ' ' ||
 COALESCE(TRIM(PRSNA_POSTL_ADDR_1.ADDR_LINE_2_TXT),'') ||  ' ' ||
 COALESCE(TRIM(PRSNA_POSTL_ADDR_1.CITY_NAME),'') ||  ' ' ||
 COALESCE(TRIM(PRSNA_POSTL_ADDR_1.POSTL_AREA_CODE),'') as FULL_ADDRESS
          
,LEGAL_ENT_PRSNA_1.LEGAL_ENT_NBR
,NULL (INTEGER) 		AS  SYS_TARGET_ID
,NULL (VARCHAR(25)) 	AS SYS_AUTH_ID
,NULL (VARCHAR(25)) 	AS SYS_SOURCE
,NULL (VARCHAR(70)) 	AS SYS_CREATED_BY
,NULL (TIMESTAMP(0)) 	AS SYS_CREATION_DATE
,'ACTIVE'  (VARCHAR(25)) 	AS  SYS_ENT_STATE
,NULL (VARCHAR(70)) 	AS SYS_LAST_MODIFIED_BY
,NULL (TIMESTAMP(0)) 	AS SYS_LAST_MODIFIED_DATE
,NULL (VARCHAR(25)) 	AS SYS_NC_TYPE
,NULL (VARCHAR(10000)) 	AS SYS_ERR_CODE
,NULL (VARCHAR(30)) 	AS SYS_ERR_SVRTY   
 FROM MDM.MATCHD_CNSMR_PRSNA LEGAL_ENT_PRSNA_1   
 LEFT OUTER JOIN MDM.MATCHD_CNSMR_POSTL_ADDR PRSNA_POSTL_ADDR_1
 ON LEGAL_ENT_PRSNA_1.MATCHD_CNSMR_PRSNA_ID = 
 PRSNA_POSTL_ADDR_1.MATCHD_CNSMR_PRSNA_ID
 AND LEGAL_ENT_PRSNA_1.LEGAL_ENT_NBR = PRSNA_POSTL_ADDR_1.LEGAL_ENT_NBR
;