REPLACE VIEW MDM.V_MATCHED_NOT_FND_OPT
	(
	PE_OPTOUT_ID,
	GVN_NAME_OPT,
	MID_NAME_OPT,
	FAMLY_NAME_OPT,
	FULL_PHONE_NUM_OPT,
	EMAIL_ADDR_TXT_OPT,
	ADDRESS_OPT,
	LEGAL_ENT_NBR,
	MATCH_FLG,
	NATIONAL_ID_NBR,
	REGIS_PRSNA_ID,
	GVN_NAME_REG,
	FAMLY_NAME_REG
	)
	AS
	
	LOCKING ROW FOR ACCESS	
	SELECT 
		OONF.PE_OPTOUT_ID,
		OONF.GVN_NAME AS GVN_NAME_OPT,
		OONF.MID_NAME AS MID_NAME_OPT,
		OONF.FAMLY_NAME AS FAMLY_NAME_OPT,
		OONF.FULL_PHONE_NUM AS FULL_PHONE_NUM_OPT,
		OONF.EMAIL_ADDR_TXT AS EMAIL_ADDR_TXT_OPT,
		coalesce(OONF.ADDR_LINE_1_TXT,'')||' '||coalesce(OONF.ADDR_LINE_2_TXT,'')||' '||coalesce(OONF.ADDR_LINE_3_TXT,'')||' '||coalesce(OONF.CITY_NAME,'')||' '||coalesce(OONF.TERR_NAME,'')||' '||coalesce(OONF.CNTRY_NAME,'')||' '||coalesce(OONF.POSTL_AREA_CODE,'') AS ADDRESS_OPT,
		OONF.LEGAL_ENT_NBR ,
		OONF.MATCH_FLG ,
		OONF.NATIONAL_ID_NBR,
		RP.REGIS_PRSNA_ID,
		RP.GVN_NAME,
		RP.FAMLY_NAME
	FROM MDM.OPT_OUT_NOT_FOUND OONF 
	JOIN MDM.OPT_OUT_NOT_FOUND_XREF XREF ON OONF.PE_OPTOUT_ID=XREF.PE_OPTOUT_ID 
	JOIN MDM.REGIS_PRSNA RP ON RP.MKTNG_PGM_NBR IN (SELECT MKTNG_PGM_NBR FROM MDM.MKTNG_PGM WHERE LEGAL_ENT_NBR=OONF.LEGAL_ENT_NBR ) AND RP.REGIS_PRSNA_ID=XREF.REGIS_PRSNA_ID;