REPLACE VIEW MDM.V_PHONE 
	AS LOCKING ROW FOR ACCESS
	SELECT
	PH.REGIS_PRSNA_ID
	,PH.SUBSCRPTN_OPT_IND
	,PH.CNSMR_CHCE_DATETM
	,PH.PREF_CNTCT_POINT_IND
	,PH.FULL_PHONE_NUM
	,PH.CNTCT_POINT_CATEG_CODE
	,PH.SUBSCRPTN_OPT_NBR
	,PH.MKTNG_PGM_NBR
	,PH.LEGAL_ENT_NBR
	,SO.SUBSCRPTN_OPT_NAME
	,SO.SUBSCRPTN_OPT_STMT_TXT
	,NULL (INTEGER)   AS  SYS_TARGET_ID
	,NULL (VARCHAR(25))  AS SYS_AUTH_ID
	,NULL (VARCHAR(25))  AS SYS_SOURCE
	,NULL (VARCHAR(70))  AS SYS_CREATED_BY
	,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
	,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
	,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
	,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
	,NULL (VARCHAR(25))  AS SYS_NC_TYPE
	,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
	,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY 
	FROM MDM.REGIS_PRSNA_PHONE PH
	LEFT JOIN
	(SEL * FROM  MDM.SUBSCRPTN_OPT ) SO
	ON
	PH.MKTNG_PGM_NBR=SO.MKTNG_PGM_NBR
	AND 
	PH.LEGAL_ENT_NBR=SO.LEGAL_ENT_NBR
	AND
	PH.SUBSCRPTN_OPT_NBR=SO.SUBSCRPTN_OPT_NBR;