REPLACE VIEW MDM.V_REGIS_PRSNA		
AS			
LOCKING ROW FOR ACCESS			
SELECT
MATCHD_CNSMR_PRSNA_1.HSHLD_PRSNA_ID 			
,REGIS_PRSNA_1.REGIS_PRSNA_ID 			
,REGIS_PRSNA_1.MKTNG_PGM_NBR  			
,REGIS_PRSNA_1.REGIS_CNSMR_ID_VAL			
,REGIS_PRSNA_1.GVN_NAME			
,REGIS_PRSNA_1.MID_NAME			
,REGIS_PRSNA_1.FAMLY_NAME			
,REGIS_PRSNA_1.FAMLY_NAME ||','|| REGIS_PRSNA_1.GVN_NAME AS FULL_NAME			
,REGIS_PRSNA_1.BRTH_DATE			
,REGIS_PRSNA_1.CNTRY_CODE AS CNTRY_NAME			
,REGIS_PRSNA_1.NATIONAL_ID_NBR			
,TRIM(REGIS_PRSNA_1.NAME_PREFX_TXT) AS NAME_PREFX_TXT			
,TRIM(REGIS_PRSNA_1.NAME_SUFFX_TXT) AS NAME_SUFFX_TXT			
,REGIS_PRSNA_1.CNSMR_USER_NAME			
,REGIS_PRSNA_1.GENDR_IND			
,REGIS_PRSNA_1.LEGAL_ENT_NBR			
,REGIS_PRSNA_1.LANG_CODE AS LANG_CODE			
,REGIS_PRSNA_1.LANG_CODE AS LANG_NAME			
,REGIS_PRSNA_1.MATCHD_CNSMR_PRSNA_ID 			
,REGIS_PRSNA_1.DATA_ORIGIN_SRCE_NBR 			
,REGIS_PRSNA_1.DATA_OP_SRCE_NAME			
,REGIS_PRSNA_1.PRSNA_STATUS_CODE			
,PRSNA_POSTL_ADDR_1.ADDR_LINE_1_TXT			
,PRSNA_POSTL_ADDR_1.ADDR_LINE_2_TXT			
,PRSNA_POSTL_ADDR_1.ADDR_LINE_3_TXT			
,PRSNA_POSTL_ADDR_1.STRET_NUM			
,PRSNA_POSTL_ADDR_1.STRET_NAME			
,PRSNA_POSTL_ADDR_1.APT_NUM			
,PRSNA_POSTL_ADDR_1.PO_BOX_NUM			
,PRSNA_POSTL_ADDR_1.CITY_NAME			
,PRSNA_POSTL_ADDR_1.TERR_CODE			
,PRSNA_POSTL_ADDR_1.TERR_CODE AS TERR_NAME			
,PRSNA_POSTL_ADDR_1.POSTL_AREA_CODE			
,PRSNA_POSTL_ADDR_1.WIN_KEY			
,COALESCE(PRSNA_POSTL_ADDR_1.ADDR_LINE_1_TXT,'') ||  ' ' ||			
COALESCE(PRSNA_POSTL_ADDR_1.ADDR_LINE_2_TXT,'') ||   ' ' ||			
COALESCE(PRSNA_POSTL_ADDR_1.CITY_NAME,'') ||  ' ' ||			
COALESCE(PRSNA_POSTL_ADDR_1.POSTL_AREA_CODE,'') AS FULL_ADDRESS			
,MKTNG_PGM_1.MKTNG_PGM_NAME			
,NULL (INTEGER)   AS  SYS_TARGET_ID			
,NULL (VARCHAR(25))  AS SYS_AUTH_ID			
,NULL (VARCHAR(25))  AS SYS_SOURCE			
,NULL (VARCHAR(70))  AS SYS_CREATED_BY			
,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE			
,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE			
,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY			
,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE			
,NULL (VARCHAR(25))  AS SYS_NC_TYPE			
,NULL (VARCHAR(10000))  AS SYS_ERR_CODE			
,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   			
,PRSNA_EMAIL_ADDR_1.EMAIL_ADDR_TXT AS EMAIL_ADDR_TXT_1 			
,PRSNA_PHONE_1.PHONE_CNTRY_NBR AS PHONE_CNTRY_NBR_1			
,PRSNA_PHONE_1.PHONE_AREA_NBR  AS PHONE_AREA_NBR_1			
,PRSNA_PHONE_1.PHONE_EXCHG_NBR AS PHONE_EXCHG_NBR_1			
,PRSNA_PHONE_1.PHONE_LINE_NBR  AS PHONE_LINE_NBR_1			
,PRSNA_PHONE_1.PHONE_EXTSN_NUM AS PHONE_EXTSN_NUM_1			
,PRSNA_PHONE_1.FULL_PHONE_NUM  AS FULL_PHONE_NUM_1			
FROM MDM.REGIS_PRSNA REGIS_PRSNA_1			
LEFT OUTER JOIN MDM.REGIS_PRSNA_POSTL_ADDR PRSNA_POSTL_ADDR_1			
ON REGIS_PRSNA_1.REGIS_PRSNA_ID = PRSNA_POSTL_ADDR_1.REGIS_PRSNA_ID			
AND REGIS_PRSNA_1.MKTNG_PGM_NBR = PRSNA_POSTL_ADDR_1.MKTNG_PGM_NBR			
LEFT OUTER JOIN MDM.REGIS_PRSNA_PHONE PRSNA_PHONE_1			
ON REGIS_PRSNA_1.REGIS_PRSNA_ID = PRSNA_PHONE_1.REGIS_PRSNA_ID			
AND REGIS_PRSNA_1.MKTNG_PGM_NBR = PRSNA_PHONE_1.MKTNG_PGM_NBR			
LEFT OUTER JOIN MDM.REGIS_PRSNA_EMAIL_ADDR PRSNA_EMAIL_ADDR_1			
ON REGIS_PRSNA_1.REGIS_PRSNA_ID = PRSNA_EMAIL_ADDR_1.REGIS_PRSNA_ID			
AND REGIS_PRSNA_1.MKTNG_PGM_NBR = PRSNA_EMAIL_ADDR_1.MKTNG_PGM_NBR			
INNER JOIN MDM.MKTNG_PGM MKTNG_PGM_1			
ON REGIS_PRSNA_1.MKTNG_PGM_NBR = MKTNG_PGM_1.MKTNG_PGM_NBR
INNER JOIN MDM.MATCHD_CNSMR_PRSNA MATCHD_CNSMR_PRSNA_1
ON REGIS_PRSNA_1.MATCHD_CNSMR_PRSNA_ID=MATCHD_CNSMR_PRSNA_1.MATCHD_CNSMR_PRSNA_ID		
QUALIFY RANK() OVER(PARTITION BY REGIS_PRSNA_1.REGIS_PRSNA_ID,REGIS_PRSNA_1.MKTNG_PGM_NBR			
ORDER BY REGIS_PRSNA_1.PRSNA_STATUS_CODE ASC,PRSNA_EMAIL_ADDR_1.PREF_CNTCT_POINT_IND DESC, PRSNA_PHONE_1.PREF_CNTCT_POINT_IND DESC,PRSNA_POSTL_ADDR_1.PREF_CNTCT_POINT_IND DESC,PRSNA_EMAIL_ADDR_1.EMAIL_ADDR_TXT DESC,PRSNA_PHONE_1.FULL_PHONE_NUM DESC,PRSNA_EMAIL_ADDR_1.SUBSCRPTN_OPT_NBR DESC,PRSNA_PHONE_1.SUBSCRPTN_OPT_NBR DESC,PRSNA_POSTL_ADDR_1.SUBSCRPTN_OPT_NBR DESC,PRSNA_EMAIL_ADDR_1.CNTCT_POINT_CATEG_CODE DESC,PRSNA_PHONE_1.CNTCT_POINT_CATEG_CODE DESC,PRSNA_POSTL_ADDR_1.CNTCT_POINT_CATEG_CODE DESC) = 1;