REPLACE VIEW MDM.V_RPT_LOAD_NBR
AS
LOCKING ROW FOR ACCESS
SELECT 
A.LOAD_ID,
B.SOURCE_ID,
B.REQ_MAIL_ID,
B.DATA_SOURCE,
A.MKTNG_PGM_NBR,
A.LEGAL_ENT_NBR,
M.MKTNG_PGM_NAME,
L.LEGAL_ENT_NAME,
STAGING_NBR,
C.STG_REJECT_CNT,
C.STG_REJECT_DESC,
ERROR_NBR,
ACTIVE_NBR,
DUPLICATE_NBR,
PHONE_OPT_IN,
PHONE_OPT_OUT,
EMAIL_OPT_IN,
EMAIL_OPT_OUT,
POSTAL_OPT_IN,
POSTAL_OPT_OUT,
SOCIAL_OPT_IN,
SOCIAL_OPT_OUT,
LOADSTATUS AS LOAD_SUCCESS, 
CAST(LOADSTARTTS AS DATE FORMAT 'mm/dd/yyyy') AS START_DATE,
CAST(LOADENDTS AS DATE FORMAT 'mm/dd/yyyy') AS END_DATE
FROM RPT_LOAD_NBR A
LEFT OUTER JOIN (
SELECT b.SOURCE_ID,
b.DATA_SOURCE,
b.REQ_MAIL_ID,
a.LOAD_ID,
LOADSTATUS,
MIN(LOADSTARTTS) LOADSTARTTS,
MAX(LOADENDTS) LOADENDTS
FROM
ETL_CTRL.LOAD_CONTROL a
INNER JOIN ETL_CTRL.SOURCE_CONTROL b
ON b.SOURCE_ID=a.SOURCE_ID
AND LOADSTATUS='Success'
GROUP BY 1,2,3,4,5
) B
ON A.LOAD_ID=B.LOAD_ID
LEFT OUTER JOIN
(SELECT LOAD_ID,
	(CASE WHEN SOURCECNT = TARGETCNT 
			THEN 0
			ELSE  REJECTSCNT END)AS STG_REJECT_CNT,
FailedReason AS STG_REJECT_DESC
FROM
	ETL_CTRL.LOAD_CONTROL
WHERE LOAD_TYPE='ETL'
)C
ON B.LOAD_ID=C.LOAD_ID
LEFT OUTER JOIN MKTNG_PGM M
ON M.MKTNG_PGM_NBR = A.MKTNG_PGM_NBR
LEFT OUTER JOIN LEGAL_ENT L
ON L.LEGAL_ENT_NBR = A.LEGAL_ENT_NBR
;