REPLACE VIEW MDM.V_RPT_PROFILE_CHANGES
 AS
 LOCKING ROW FOR ACCESS
 SELECT 
       LEGAL_ENT_NBR,
      MKTNG_PGM_NBR,
      USER_ID,
      MONTH_START,
      PROFILE_CHANGE_NBR
 FROM
 MDM.RPT_PROFILE_CHANGES;