REPLACE VIEW MDM.V_RPT_ADDR_QLTY	
	AS
	LOCKING ROW FOR ACCESS
	SELECT
	A.MKTNG_PGM_NBR, 
	A.LEGAL_ENT_NBR, 
	ACTV_RGSTRTN_CNT, 
	SUCCESS_PCT, 
	LCLTY_FAIL_PCT, 
	UNK_ADDR_PCT, 
	MULTIPLE_ADDR_MATCH_PCT, 
	CITY_TERR_FAIL_PCT, 
	STREET_NAME_FAIL_PCT, 
	HOUSE_NO_FAIL_PCT, 
	STREET_COMPT_FAIL_PCT, 
	MULTIPLE_STREET_ADDR_PCT, 
	LEGAL_ENT_NAME,
	MKTNG_PGM_NAME
	FROM MDM.RPT_ADDR_QLTY A
	JOIN MKTNG_PGM MP ON A.MKTNG_PGM_NBR=MP.MKTNG_PGM_NBR
	JOIN LEGAL_ENT L ON A.LEGAL_ENT_NBR=L.LEGAL_ENT_NBR;