REPLACE VIEW MDM.V_SOCIAL
	AS LOCKING ROW FOR ACCESS 
	SELECT
	SOC.REGIS_PRSNA_ID
	,SOC.SUBSCRPTN_OPT_IND
	,SOC.CNSMR_CHCE_DATETM
	,SOC.PREF_CNTCT_POINT_IND
	,SOC.SOC_NET_STATUS_CODE 
	,SOC.CNTCT_POINT_CATEG_CODE
	,SOC.SUBSCRPTN_OPT_NBR
	,SOC.MKTNG_PGM_NBR
	,SOC.LEGAL_ENT_NBR
	,SOC.SOCIAL_NETWK_ACCT_ID_VAL
	,SO.SUBSCRPTN_OPT_NAME
	,SO.SUBSCRPTN_OPT_STMT_TXT
	,NULL (INTEGER)   AS  SYS_TARGET_ID
	,NULL (VARCHAR(25))  AS SYS_AUTH_ID
	,NULL (VARCHAR(25))  AS SYS_SOURCE
	,NULL (VARCHAR(70))  AS SYS_CREATED_BY
	,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE
	,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE
	,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY
	,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE
	,NULL (VARCHAR(25))  AS SYS_NC_TYPE
	,NULL (VARCHAR(10000))  AS SYS_ERR_CODE
	,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   
	FROM MDM.REGIS_PRSNA_SOC_NET_ACCT SOC
	LEFT JOIN
	(SEL * FROM  MDM.SUBSCRPTN_OPT ) SO
	ON
	SOC.MKTNG_PGM_NBR=SO.MKTNG_PGM_NBR
	AND 
	SOC.LEGAL_ENT_NBR=SO.LEGAL_ENT_NBR
	AND
	SOC.SUBSCRPTN_OPT_NBR=SO.SUBSCRPTN_OPT_NBR;