REPLACE VIEW MDM.V_SRC_EMAIL_DETAIL
AS
LOCKING ROW FOR ACCESS
SELECT DISTINCT A.SOURCE_ID,
A.REQ_MAIL_ID,
A.AGN_CON_MAIL_ID,
B.LOAD_ID
FROM ETL_CTRL.SOURCE_CONTROL A
INNER JOIN ETL_CTRL.LOAD_CONTROL B
ON A.SOURCE_ID = B.SOURCE_ID
AND B.LOAD_TYPE='ETL'
AND B.LOAD_ID IN(SEL LOAD_ID FROM MDM.MDM_LOAD_CONTROL)
INNER JOIN MDM.LOAD_INFO LI
ON B.LOAD_ID = LI.LOAD_ID
AND LI.PROCESS_NAME='Wrapper'
AND LI.STATUS = 'Success';