REPLACE VIEW MDM.V_UNMATCHED_NOT_FND_OPT
	(
	PE_OPTOUT_ID,
	GVN_NAME_OPT,
	MID_NAME_OPT,
	FAMLY_NAME_OPT,
	FULL_PHONE_NUM_OPT,
	EMAIL_ADDR_TXT_OPT,
	ADDRESS_OPT,
	LEGAL_ENT_NBR,
	MATCH_FLG,
	NATIONAL_ID_NBR
	)
	AS
	LOCKING ROW FOR ACCESS	
	SELECT 
		PE_OPTOUT_ID,
		GVN_NAME AS GVN_NAME_OPT,
		MID_NAME AS MID_NAME_OPT,
		FAMLY_NAME AS FAMLY_NAME_OPT,
		FULL_PHONE_NUM AS FULL_PHONE_NUM_OPT,
		EMAIL_ADDR_TXT AS EMAIL_ADDR_TXT_OPT,
		coalesce(ADDR_LINE_1_TXT,'')||' '||coalesce(ADDR_LINE_2_TXT,'')||' '||coalesce(ADDR_LINE_3_TXT,'')||' '||coalesce(CITY_NAME,'')||' '||coalesce(TERR_NAME,'')||' '||coalesce(CNTRY_NAME,'')||' '||coalesce(POSTL_AREA_CODE,'') AS ADDRESS_OPT ,
		LEGAL_ENT_NBR,
		MATCH_FLG,
		NATIONAL_ID_NBR
	FROM MDM.OPT_OUT_NOT_FOUND WHERE MATCH_FLG = 'N' ;