REPLACE VIEW MDM.V_UNMATCHED_NOT_FND_OPT_RPRT
	(
	PE_OPTOUT_ID,
	GVN_NAME_OPT,
	MID_NAME_OPT,
	FAMLY_NAME_OPT,
	FULL_PHONE_NUM_OPT,
	EMAIL_ADDR_TXT_OPT,
	ADDRESS_OPT,
	ADDRESS_OPT1,
	LEGAL_ENT_NBR,
	MATCH_FLG,
	NATIONAL_ID_NBR
	)
	AS
		LOCKING ROW FOR ACCESS	
	SELECT 
	      OPT_OUT_DRCTV_ID AS	PE_OPTOUT_ID,
		FIRST_NAME AS GVN_NAME_OPT,
		' ' AS MID_NAME_OPT,
		LAST_NAME AS FAMLY_NAME_OPT,
		CONTACT_PHONE_NBR AS FULL_PHONE_NUM_OPT,
		EMAIL_ADDR_TEXT AS EMAIL_ADDR_TXT_OPT,
		coalesce(ADDR_LINE_1_TXT,'')||' '||coalesce(ADDR_LINE_2_TXT,'')||' '||coalesce(ADDR_LINE_3_TXT,'')||' '||coalesce(CITY_NAME,'')||' '||coalesce(TERR_NAME,'')||' '||coalesce(CNTRY_NAME,'')||' '||coalesce(POSTL_AREA_CODE,'') AS ADDRESS_OPT ,
		coalesce(ADDR_LINE_1_TXT,'')||'^'||coalesce(ADDR_LINE_2_TXT,'')||'^'||coalesce(ADDR_LINE_3_TXT,'') AS ADDRESS_OPT1 ,
		LEGAL_ENT_NBR,
		' ' AS MATCH_FLG,
		NATIONAL_ID_NBR
	FROM MDM.OPT_OUT_DIRECTIVE  
	WHERE OPT_OUT_DRCTV_ID NOT IN (SELECT OPT_OUT_DRCTV_ID FROM MDM.REGIS_PRSNA_OPT_HIST)
;