REPLACE VIEW MDM.WS_CAMPAIGN_SGMNT_CNSMR
( 
 MKTNG_PGM_NBR,
  REGIS_PRSNA_ID,
 REGIS_CNSMR_ID_VAL,
 DATA_SRCE_NBR ,
 CAMPAIGN_LEAD_KEY,
 SYS_TARGET_ID,
 SYS_AUTH_ID,
 SYS_SOURCE,
 SYS_CREATED_BY,
 SYS_CREATION_DATE,
 SYS_ENT_STATE,
 SYS_LAST_MODIFIED_BY,
 SYS_LAST_MODIFIED_DATE,
 SYS_NC_TYPE,
 SYS_ERR_CODE,
 SYS_ERR_SVRTY 
) 
AS
LOCKING ROW FOR ACCESS 
SELECT
B.MKTNG_PGM_NBR, 
B.REGIS_PRSNA_ID,
B.REGIS_CNSMR_ID_VAL,
B.DATA_SRCE_NBR,
A.CAMPAIGN_LEAD_KEY,
NULL (INTEGER)   AS  SYS_TARGET_ID,
NULL (VARCHAR(1000))  AS SYS_AUTH_ID,
NULL (VARCHAR(256))  AS SYS_SOURCE,
NULL (VARCHAR(70))  AS SYS_CREATED_BY,
NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE,
NULL  (VARCHAR(25))  AS  SYS_ENT_STATE,
NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY,
NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE, 
NULL (VARCHAR(25))  AS SYS_NC_TYPE,
NULL (VARCHAR(10000))  AS SYS_ERR_CODE,
NULL (VARCHAR(30))  AS SYS_ERR_SVRTY
FROM MDM.CAMPAIGN_SGMNT_CNSMR A
INNER JOIN MDM.REGIS_PRSNA B
ON A.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND A.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID;