REPLACE VIEW MDM.WS_CAMPAIGN_EMAIL
( 
 CAMPAIGN_LEAD_KEY,
EMAIL_ADDR_TXT,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_SOURCE,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_LAST_MODIFIED_DATE,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY 
) 
AS
LOCKING ROW FOR ACCESS 
SELECT
TEMP.CAMPAIGN_LEAD_KEY,
A.EMAIL_ADDR_TXT,
NULL (INTEGER)   AS  SYS_TARGET_ID,
NULL (VARCHAR(1000))  AS SYS_AUTH_ID,   
NULL (VARCHAR(256))  AS SYS_SOURCE,
NULL (VARCHAR(70))  AS SYS_CREATED_BY,
NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE,
NULL  (VARCHAR(25))  AS  SYS_ENT_STATE,
NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY,
NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE, 
NULL (VARCHAR(25))  AS SYS_NC_TYPE,
NULL (VARCHAR(10000))  AS SYS_ERR_CODE,
NULL (VARCHAR(30))  AS SYS_ERR_SVRTY
FROM     MDM.CAMPAIGN_CNSMR TEMP
    INNER JOIN MDM.CAMPAIGN_INST C
        ON TEMP.CAMPAIGN_INST_ID=C.CAMPAIGN_INST_ID
    INNER JOIN  (NONSEQUENCED TRANSACTIONTIME
    SEL MKTNG_PGM_NBR,REGIS_PRSNA_ID,TEMPORAL_TIME,EMAIL_ADDR_TXT
    FROM    ICRM.REGIS_PRSNA_EMAIL_ADDR A
        WHERE   A.SUBSCRPTN_OPT_IND IS NOT NULL) A
        ON TEMP.MKTNG_PGM_NBR = A.MKTNG_PGM_NBR
        AND TEMP.REGIS_PRSNA_ID = A.REGIS_PRSNA_ID
    WHERE    C.CAMPAIGN_INST_START_DTTM BETWEEN Begin(TEMPORAL_TIME) 
        AND End(TEMPORAL_TIME)
        
       QUALIFY   Row_Number() Over (
    PARTITION BY TEMP.CAMPAIGN_LEAD_KEY 
    ORDER BY TEMPORAL_TIME DESC)=1;