REPLACE VIEW MDM.WS_CAMPAIGN_JOBS  
(CAMPAIGN_NAME
,MKTNG_PGM_NBR
,MKTNG_PGM_NAME
,COUNTRY
,VENDOR_NAME
,CAMPAIGN_URL
,EMAIL_DEPLOYMENT_DATE
,EMAIL_DEPLOYMENT_TIME
,START_DTTM
,END_DTTM
,NEXT_SCHEDULED_RUN_DTTM
,LEAD_GENERATION_CNT
,AUTOMATED_IND
,STATUS
,SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_SOURCE,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_LAST_MODIFIED_DATE,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY ) 
AS
SELECT DISTINCT
CAMPAIGN_NAME
,MKTNG_PGM_NBR
,MKTNG_PGM_NAME
,COUNTRY
,VENDOR_NAME
,CAMPAIGN_URL
,CAST(EMAIL_DEPLOYMENT_DATE AS DATE)
,CAST(EMAIL_DEPLOYMENT_TIME AS TIME)
,START_DTTM
,END_DTTM
,NEXT_SCHEDULED_RUN_DTTM
,LEAD_GENERATION_CNT
,AUTOMATED_IND
,STATUS
,NULL (INTEGER)              AS  SYS_TARGET_ID,
NULL (VARCHAR(1000)) AS SYS_AUTH_ID,
NULL (VARCHAR(256))   AS SYS_SOURCE,
NULL (VARCHAR(70))    AS SYS_CREATED_BY,
NULL (TIMESTAMP(0))   AS SYS_CREATION_DATE,
'ACTIVE'  (VARCHAR(25))       AS  SYS_ENT_STATE,
NULL (VARCHAR(70))    AS SYS_LAST_MODIFIED_BY,
NULL (TIMESTAMP(0))   AS SYS_LAST_MODIFIED_DATE, 
NULL (VARCHAR(25))    AS SYS_NC_TYPE,
NULL (VARCHAR(10000)) AS SYS_ERR_CODE,
NULL (VARCHAR(30))    AS SYS_ERR_SVRTY   
FROM 
TRM_VIEWS_DB.RB_CAMPAIGN_JOBS;