REPLACE VIEW  MDM.WS_MATCHD_CNSMR_PRSNA_TRT 
(MKTNG_PGM_NBR, 
REGIS_PRSNA_ID,
 REGIS_CNSMR_ID_VAL,
 DATA_SRCE_NBR,
 MATCHD_CNSMR_PRSNA_ID, 
 TRT_NAME,
 MATCHD_PRSNA_TRT_TXT,
 MATCHD_PRSNA_TRT_DATE,
 SYS_TARGET_ID,
 SYS_AUTH_ID,
 SYS_SOURCE,
 SYS_CREATED_BY,
 SYS_CREATION_DATE,
 SYS_ENT_STATE,
 SYS_LAST_MODIFIED_BY,
 SYS_LAST_MODIFIED_DATE,
 SYS_NC_TYPE,
 SYS_ERR_CODE,
 SYS_ERR_SVRTY ) 
AS   
SELECT 
B.MKTNG_PGM_NBR,
B.REGIS_PRSNA_ID, 
B.REGIS_CNSMR_ID_VAL,
B.DATA_SRCE_NBR,
A.MATCHD_CNSMR_PRSNA_ID, 
C.TRT_NAME,
A.MATCHD_PRSNA_TRT_TXT,
A.MATCHD_PRSNA_TRT_DATE,
NULL (INTEGER)   AS  SYS_TARGET_ID,
NULL (VARCHAR(1000))  AS SYS_AUTH_ID,
NULL (VARCHAR(256))  AS SYS_SOURCE,
NULL (VARCHAR(70))  AS SYS_CREATED_BY,
NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE,
NULL (VARCHAR(25))  AS  SYS_ENT_STATE,
NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY,
NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE, 
NULL (VARCHAR(25))  AS SYS_NC_TYPE,
NULL (VARCHAR(10000))  AS SYS_ERR_CODE,
NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   
FROM MDM.MATCHD_CNSMR_PRSNA_TRT A
INNER JOIN MDM.REGIS_PRSNA B
ON A.LEGAL_ENT_NBR=B.LEGAL_ENT_NBR
AND A.MATCHD_CNSMR_PRSNA_ID=B.MATCHD_CNSMR_PRSNA_ID
INNER JOIN MDM.TRT C
ON A.TRT_NBR=C.TRT_NBR;