REPLACE VIEW  MDM.WS_MKTNG_PGM_SCORE_SGMNT 
(
MKTNG_PGM_NBR,
MKTNG_PGM_NAME ,
MKTNG_PGM_SHORT_NAME ,
MKTNG_PGM_DESC ,
MKTNG_PGM_STATUS ,
MKTNG_PGM_BUSN_NAME ,
LEGAL_ENT_NBR ,
CNSMR_SCORE_NBR ,
CNSMR_SCORE_NAME,
CNSMR_SCORE_DESC,  
WEBSITE_SGMNT_IND,
 SYS_TARGET_ID,
 SYS_AUTH_ID,
 SYS_SOURCE,
 SYS_CREATED_BY,
 SYS_CREATION_DATE,
 SYS_ENT_STATE,
 SYS_LAST_MODIFIED_BY,
 SYS_LAST_MODIFIED_DATE,
 SYS_NC_TYPE,
 SYS_ERR_CODE,
 SYS_ERR_SVRTY 
	  ) AS 
SEL	
MKTNG_PGM_NBR,
MKTNG_PGM_NAME ,
MKTNG_PGM_SHORT_NAME ,
MKTNG_PGM_DESC ,
MKTNG_PGM_STATUS ,
MKTNG_PGM_BUSN_NAME ,
B.LEGAL_ENT_NBR ,
A.CNSMR_SCORE_NBR ,
CNSMR_SCORE_NAME,
CNSMR_SCORE_DESC,  
WEBSITE_SGMNT_IND,
NULL (INTEGER) 		AS  SYS_TARGET_ID,
NULL (VARCHAR(1000)) 	AS SYS_AUTH_ID,
NULL (VARCHAR(256)) 	AS SYS_SOURCE,
NULL (VARCHAR(70)) 	AS SYS_CREATED_BY,
NULL (TIMESTAMP(0)) 	AS SYS_CREATION_DATE,
NULL  (VARCHAR(25)) 	AS  SYS_ENT_STATE,
NULL (VARCHAR(70)) 	AS SYS_LAST_MODIFIED_BY,
NULL (TIMESTAMP(0)) 	AS SYS_LAST_MODIFIED_DATE, 
NULL (VARCHAR(25)) 	AS SYS_NC_TYPE,
NULL (VARCHAR(10000)) 	AS SYS_ERR_CODE,
NULL (VARCHAR(30)) 	AS SYS_ERR_SVRTY
FROM 
CNSMR_SCORE_REF A 
LEFT JOIN 
MTCHD_CNSMR_SCR_DMN_MAP B 
ON A.CNSMR_SCORE_NBR = B.CNSMR_SCORE_NBR
LEFT JOIN MKTNG_PGM C 
ON B.LEGAL_ENT_NBR = C.LEGAL_ENT_NBR
WHERE WEBSITE_SGMNT_IND='Y';