REPLACE VIEW  MDM.WS_PROD_ITEM_HIER_ASSOC
(
 SECTOR_CODE           ,   
 SECTOR_NAME,
 SUB_SECTOR_CODE               ,
 SUB_SECTOR_NAME,
 CATEG_CODE                    ,
 CATEG_NAME,
 SEG_CODE                      ,
 SEG_NAME,
 SUB_BRAND_CODE                ,
 SUB_BRAND_NAME,
 BRAND_CODE                    ,
 BRAND_NAME,
 ITEM_VERS_CODE                ,
 GLOBAL_FORM_CODE              ,
 PROD_ITEM_UPC                 ,
 PROD_ITEM_NAME ,
 PROD_FAMLY_ID,
 PROD_FAMLY_NAME ,
 BRAND_FAMLY_ID,
 BRAND_FAMLY_NAME,
 SYS_TARGET_ID,
 SYS_AUTH_ID,
 SYS_SOURCE,
 SYS_CREATED_BY,
 SYS_CREATION_DATE,
 SYS_ENT_STATE,
 SYS_LAST_MODIFIED_BY,
 SYS_LAST_MODIFIED_DATE,
 SYS_NC_TYPE,
 SYS_ERR_CODE,
 SYS_ERR_SVRTY ) 
AS LOCKING ROW FOR ACCESS
SELECT
A.SECTOR_CODE           ,   
G.SECTOR_NAME,
A.SUB_SECTOR_CODE               ,
D.SUB_SECTOR_NAME,
A.CATEG_CODE                    ,
B.CATEG_NAME,
A.SEG_CODE                      ,
C.SEG_NAME,
A.SUB_BRAND_CODE                ,
F.SUB_BRAND_NAME,
A.BRAND_CODE                    ,
E.BRAND_NAME,
A.ITEM_VERS_CODE                ,
A.GLOBAL_FORM_CODE              ,
A.PROD_ITEM_UPC                 ,
H.PROD_ITEM_NAME,
I.PROD_FAMLY_ID,
I.PROD_FAMLY_NAME ,
J.BRAND_FAMLY_ID,
J.BRAND_FAMLY_NAME,
NULL (INTEGER)   AS  SYS_TARGET_ID,
NULL (VARCHAR(1000))  AS SYS_AUTH_ID,
NULL (VARCHAR(256))  AS SYS_SOURCE,
NULL (VARCHAR(70))  AS SYS_CREATED_BY,
NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE,
NULL  (VARCHAR(25))  AS  SYS_ENT_STATE,
NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY,
NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE, 
NULL (VARCHAR(25))  AS SYS_NC_TYPE,
NULL (VARCHAR(10000))  AS SYS_ERR_CODE,
NULL (VARCHAR(30))  AS SYS_ERR_SVRTY   
FROM 
MDM.PROD_ITEM_HIER_ASSOC A
LEFT OUTER JOIN MDM.CATEG B
ON A.CATEG_CODE=B.CATEG_CODE
LEFT OUTER JOIN MDM.SEG C
ON A.SEG_CODE=C.SEG_CODE
LEFT OUTER JOIN MDM.SUB_SECTOR D
ON A.SUB_SECTOR_CODE=D.SUB_SECTOR_CODE
LEFT OUTER JOIN MDM.BRAND E
ON A.BRAND_CODE=E.BRAND_CODE
LEFT OUTER JOIN MDM.SUB_BRAND F
ON A.SUB_BRAND_CODE=F.SUB_BRAND_CODE
LEFT OUTER JOIN MDM.SECTOR G
ON A.SECTOR_CODE=G.SECTOR_CODE
LEFT OUTER JOIN MDM.PROD_ITEM H
ON A.PROD_ITEM_UPC=H.PROD_ITEM_UPC 
LEFT OUTER JOIN MDM.PROD_FAMLY I
ON A.PROD_FAMLY_ID=I.PROD_FAMLY_ID 
LEFT OUTER JOIN MDM.BRAND_FAMLY J
ON A.BRAND_FAMLY_ID=J.BRAND_FAMLY_ID 
;