.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L0
CREATE TABLE DEPLOY_WORK.ENV_NM_ROLLBACK AS MDM.ENV_NM WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L1
CREATE TABLE MDM.ENV_NM AS DEPLOY_WORK.ENV_NM_BK_01122017 WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
.LABEL L2
REPLACE VIEW MDM.CAMPAIGN_RUN_HST AS LOCKING ROW FOR ACCESS SELECT * FROM ICRM_TBL.CAMPAIGN_RUN_HST;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L3
 REPLACE VIEW MDM.CAMPAIGN_SGMNT_CNSMR AS LOCKING ROW FOR ACCESS SELECT * FROM ICRM_TBL.CAMPAIGN_SGMNT_CNSMR;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L4
REPLACE VIEW MDM.V_CAMPAIGN
 AS  
 LOCKING ROW FOR ACCESS  
 SELECT  
  A.REGIS_PRSNA_ID
  ,A.CAMPAIGN_ID   
    ,B.CAMPAIGN_NAME AS CAMPAIGN_NAME  
    ,A.MKTNG_PGM_NBR   
    ,D.COMM_CHNL_NAME AS CAMPAIGN_CHANNEL   
  ,A.CAMPAIGN_RUN_DTTM AS CAMPAIGN_EXEC_DATE
 ,E.MKTNG_PGM_NAME AS MKTNG_PGM_DESC
 ,D.COMM_CHNL_NAME AS PROMOTION_EMAIL_ADDR_TXT 
 ,NULL (INTEGER)   AS  SYS_TARGET_ID  
  ,NULL (VARCHAR(25))  AS SYS_AUTH_ID  
  ,NULL (VARCHAR(25))  AS SYS_SOURCE  
  ,NULL (VARCHAR(70))  AS SYS_CREATED_BY  
  ,NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE  
  ,'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE  
  ,NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY  
  ,NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE  
  ,NULL (VARCHAR(25))  AS SYS_NC_TYPE  
  ,NULL (VARCHAR(10000))  AS SYS_ERR_CODE  
  ,NULL (VARCHAR(30))  AS SYS_ERR_SVRTY     
  FROM  
   MDM.CAMPAIGN_SGMNT_CNSMR   A   
        INNER JOIN MDM.CAMPAIGN B    
 ON A.CAMPAIGN_ID = B.CAMPAIGN_ID 
 INNER JOIN MDM.COMM_CHNL D  
 ON A.COMM_CHNL_CODE=D.COMM_CHNL_CODE
AND D.COMM_CHNL_NAME NOT IN (SEL AV_DESCRIPTION FROM ATTRIBUTE_VALUES
 WHERE SYS_ENT_STATE='ACTIVE' AND ATTRIBUTE_TYPE_ID IN
 (SEL ATTRIBUTE_TYPE_ID 
 FROM ATTRIBUTE_TYPES
 WHERE ATTRIBUTE_TYPE='Ignore Channel Class')) 
 INNER JOIN MDM.MKTNG_PGM E  
 ON A.MKTNG_PGM_NBR=E.MKTNG_PGM_NBR;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  
 
    .LABEL L5
REPLACE VIEW MDM.SMS_CMPGN_RESP AS LOCKING ROW FOR ACCESS SELECT * FROM ICRM_TBL.SMS_CMPGN_RESP;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;   
  
.LABEL L6
REPLACE VIEW MDM.CAMPAIGN AS LOCKING ROW FOR ACCESS SELECT * FROM ICRM_TBL.CAMPAIGN;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE; 
  
  .LABEL L7
  REPLACE VIEW MDM.CAMPAIGN_COLLATERAL AS LOCKING ROW FOR ACCESS 
SELECT * FROM iCRM_TBL.CAMPAIGN_COLLATERAL;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE; 
  
.LABEL L8
REPLACE VIEW MDM.SALES_TRANX
AS LOCKING ROW FOR ACCESS SELECT
*
FROM ICRM_TBL.SALES_TRANX;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE; 

.LABEL L9
REPLACE VIEW MDM.MOBILE_CAMP_STG AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_STAGE_TBL.MOBILE_CAMP_STG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L10
REPLACE VIEW MDM.MOBILE_CAMP_STG_HIST AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_STAGE_TBL.MOBILE_CAMP_STG_HIST;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L11
UPDATE ETL_CTRL.FILE_CONTROL
SET ERROR_THRS_HOLD='10%'
WHERE FORMAT_ID IN (68,10,89);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE; 
    .LABEL L12    
REPLACE VIEW MDM.RT_DMC_CONTACT AS LOCKING ROW FOR ACCESS SELECT * FROM TRM_LEAD_DB.RT_DMC_CONTACT;    
   .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
    .LABEL L13 
REPLACE VIEW MDM.SALES_TRANX_LINE AS LOCKING ROW FOR ACCESS SELECT * FROM ICRM_TBL.SALES_TRANX_LINE;    
   .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
   
  .LABEL L14  
REPLACE VIEW MDM.REGIS_PRSNA_RPLNSH_INST 
AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
 RPLNSH_INST_ID,
 MKTNG_PGM_NBR,
 DATA_SRCE_NBR,
 REGIS_PRSNA_ID,
 RPLNSH_ID,
 PROD_ITEM_UPC,
 LYLTY_ACCT_NUM,
 LYLTY_PGM_NBR,
 REGIS_CNSMR_ID_VAL,
 CREATE_DATETM,
 NEXT_ORDER_DATE,
 RPLNSH_INST_STATUS_CODE,
 RPLNSH_INST_STATUS_DATETM,
 FREQ_DAYS,
 PROD_ITEM_QTY,
 ORIG_ORDER_ID,
 CNCLTN_RSN_CODE,
 ORDER_SKIP_DATE,
 NTH_ORDER_CNT,
 LOG_SOURCE_ID,
 LOG_LOAD_ID,
 LOG_UPDATE_USER
FROM ICRM_TBL.REGIS_PRSNA_RPLNSH_INST;  
   .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;   
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L71
DROP TABLE MDM.OPT_OUT_I10_BEL_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L72
DROP TABLE MDM.OPT_OUT_I10_PRT_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L73
DROP TABLE MDM.OPT_OUT_I10_HKG_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L74
DROP TABLE MDM.OPT_OUT_I10_PAK_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L75
DROP TABLE MDM.OPT_OUT_I10_LUX_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L76
DROP TABLE MDM.OPT_OUT_I10_HUN_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L77
DROP TABLE MDM.OPT_OUT_I10_ARB_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L78
DROP TABLE MDM.OPT_OUT_I10_ROU_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L79
DROP TABLE MDM.OPT_OUT_I10_ESP_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L80
DROP TABLE MDM.OPT_OUT_I10_ISR_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L81
DROP TABLE MDM.OPT_OUT_I10_BGR_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L81A
DROP TABLE MDM.OPT_OUT_I10_AUS_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L82
DROP TABLE MDM.OPT_OUT_I10_NOR_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L83
DROP TABLE MDM.OPT_OUT_I10_IND_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L84
DROP TABLE MDM.OPT_OUT_I10_POL_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L85
DROP TABLE MDM.OPT_OUT_I10_IRL_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L86
DROP TABLE MDM.OPT_OUT_I10_NLD_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L87
DROP TABLE MDM.OPT_OUT_I10_AUT_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L88
DROP TABLE MDM.OPT_OUT_I10_PHL_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L89
DROP TABLE MDM.OPT_OUT_I10_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L90
DROP TABLE MDM.OPT_OUT_I10_OTH_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L91
DROP TABLE MDM.OPT_OUT_I10_HRV_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L92
DROP TABLE MDM.OPT_OUT_I10_GBR_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L93
DROP TABLE MDM.OPT_OUT_I10_FRA_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L94
DROP TABLE MDM.OPT_OUT_I10_ITA_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L95
DROP TABLE MDM.OPT_OUT_I10_AFR_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L96
DROP TABLE MDM.OPT_OUT_I10_GRC_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L97
DROP TABLE MDM.OPT_OUT_I10_MYS_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L98
DROP TABLE MDM.OPT_OUT_I10_DEU_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L99
DROP TABLE MDM.OPT_OUT_I10_USA_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L100
DROP TABLE MDM.OPT_OUT_I10_CZE_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L101
DROP TABLE MDM.OPT_OUT_I10_LA_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L102
DROP TABLE MDM.OPT_OUT_I10_NZL_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L103
DROP TABLE MDM.OPT_OUT_I10_DNK_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L104
DROP TABLE MDM.OPT_OUT_I10_SWE_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L105
DROP TABLE MDM.OPT_OUT_I10_TWN_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L106
DROP TABLE MDM.OPT_OUT_I10_FIN_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L107
DROP TABLE MDM.OPT_OUT_I10_JPN_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L108
DROP TABLE MDM.OPT_OUT_I10_CHE_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L109
DROP TABLE MDM.OPT_OUT_I10_SGP_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L110
DROP TABLE MDM.OPT_OUT_I10_TUR_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L111
DROP TABLE MDM.OPT_OUT_I10_RUS_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L112
DROP TABLE MDM.OPT_OUT_I10_KOR_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L113
DROP TABLE MDM.OPT_OUT_I10_CAN_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L114
DROP TABLE MDM.OPT_OUT_I10_CHN_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L115
DROP TABLE MDM.OPT_OUT_I10_BRA_LIST_PHONE ;
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L116
DROP TABLE MDM.OPT_OUT_I10_EGY_LIST_PHONE ;   
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L120
CREATE MULTISET TABLE MDM.OPT_OUT_I10_BEL_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L121
CREATE MULTISET TABLE MDM.OPT_OUT_I10_PRT_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L122
CREATE MULTISET TABLE MDM.OPT_OUT_I10_HKG_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L123
CREATE MULTISET TABLE MDM.OPT_OUT_I10_PAK_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L124
CREATE MULTISET TABLE MDM.OPT_OUT_I10_LUX_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L125
CREATE MULTISET TABLE MDM.OPT_OUT_I10_HUN_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L126
CREATE MULTISET TABLE MDM.OPT_OUT_I10_ARB_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L127
CREATE MULTISET TABLE MDM.OPT_OUT_I10_ROU_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L128
CREATE MULTISET TABLE MDM.OPT_OUT_I10_ESP_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L129
CREATE MULTISET TABLE MDM.OPT_OUT_I10_ISR_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L130
CREATE MULTISET TABLE MDM.OPT_OUT_I10_BGR_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L131
CREATE MULTISET TABLE MDM.OPT_OUT_I10_AUS_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L132
CREATE MULTISET TABLE MDM.OPT_OUT_I10_NOR_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L133
CREATE MULTISET TABLE MDM.OPT_OUT_I10_IND_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L134
CREATE MULTISET TABLE MDM.OPT_OUT_I10_POL_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L135
CREATE MULTISET TABLE MDM.OPT_OUT_I10_IRL_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L136
CREATE MULTISET TABLE MDM.OPT_OUT_I10_NLD_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L137
CREATE MULTISET TABLE MDM.OPT_OUT_I10_AUT_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L138
CREATE MULTISET TABLE MDM.OPT_OUT_I10_PHL_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L139
CREATE MULTISET TABLE MDM.OPT_OUT_I10_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_PRSNA_ID )
PARTITION BY CAST((MKTNG_PGM_NBR ) AS INTEGER);
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L140
CREATE MULTISET TABLE MDM.OPT_OUT_I10_OTH_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L141
CREATE MULTISET TABLE MDM.OPT_OUT_I10_HRV_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L142
CREATE MULTISET TABLE MDM.OPT_OUT_I10_GBR_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L143
CREATE MULTISET TABLE MDM.OPT_OUT_I10_FRA_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L144
CREATE MULTISET TABLE MDM.OPT_OUT_I10_ITA_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L145
CREATE MULTISET TABLE MDM.OPT_OUT_I10_AFR_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L146
CREATE MULTISET TABLE MDM.OPT_OUT_I10_GRC_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L147
CREATE MULTISET TABLE MDM.OPT_OUT_I10_MYS_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L148
CREATE MULTISET TABLE MDM.OPT_OUT_I10_DEU_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L149
CREATE MULTISET TABLE MDM.OPT_OUT_I10_USA_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L150
CREATE MULTISET TABLE MDM.OPT_OUT_I10_CZE_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L151
CREATE MULTISET TABLE MDM.OPT_OUT_I10_LA_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L152
CREATE MULTISET TABLE MDM.OPT_OUT_I10_NZL_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L153
CREATE MULTISET TABLE MDM.OPT_OUT_I10_DNK_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L154
CREATE MULTISET TABLE MDM.OPT_OUT_I10_SWE_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L154
CREATE MULTISET TABLE MDM.OPT_OUT_I10_TWN_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L156
CREATE MULTISET TABLE MDM.OPT_OUT_I10_FIN_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L157
CREATE MULTISET TABLE MDM.OPT_OUT_I10_JPN_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L158
CREATE MULTISET TABLE MDM.OPT_OUT_I10_CHE_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L159
CREATE MULTISET TABLE MDM.OPT_OUT_I10_SGP_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L160
CREATE MULTISET TABLE MDM.OPT_OUT_I10_TUR_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L161
CREATE MULTISET TABLE MDM.OPT_OUT_I10_RUS_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L162
CREATE MULTISET TABLE MDM.OPT_OUT_I10_KOR_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L163
CREATE MULTISET TABLE MDM.OPT_OUT_I10_CAN_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L164
CREATE MULTISET TABLE MDM.OPT_OUT_I10_CHN_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L165
CREATE MULTISET TABLE MDM.OPT_OUT_I10_BRA_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
--------------------------------------------------------------------------------

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L166
CREATE MULTISET TABLE MDM.OPT_OUT_I10_EGY_LIST_PHONE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LEAD_KEY_ID VARCHAR(18) CHARACTER SET LATIN NOT CASESPECIFIC,
      MKTNG_PGM_NBR DECIMAL(18,0),
      REGIS_PRSNA_ID DECIMAL(18,0),
      SUBSCRPTN_OPT_NBR DECIMAL(18,0),
      CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEPLOYED_DATE DATE FORMAT 'YYYY-MM-DD',
      LAST_ACTIVITY_TM TIMESTAMP(0),
      LOAD_ID DECIMAL(18,0),
      LOAD_TS TIMESTAMP(0),
      MDM_LOAD_IND CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ICRM_STG_LOAD_ID DECIMAL(18,0))
PRIMARY INDEX ( MKTNG_PGM_NBR ,LAST_ACTIVITY_TM ,LOAD_ID ,REGIS_CNSMR_ID_VAL );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L167
  DROP TABLE MDM.I10B_OPT_OUT_CHK_RPT;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  .LABEL L168
CREATE SET TABLE MDM.I10B_OPT_OUT_CHK_RPT ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      IMPCT_REGIS_PRSNA_ID INTEGER NOT NULL,
      IMPCT_MKTNG_PGM_NBR INTEGER NOT NULL,
      IMPCT_CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ,
      IMPCT_SUBSCRPTN_OPT_NBR INTEGER COMPRESS ,
      MKTNG_PGM_NBR DECIMAL(18,0) COMPRESS ,
      FULL_PHONE_NBR VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      LAST_ACTIVITY_TM TIMESTAMP(0),
      UNSUB CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOAD_ID DECIMAL(18,0) COMPRESS ,
      RPT_DATE DATE FORMAT 'YY/MM/DD' NOT NULL,
      OPT_CHK_DESC VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX I10B_OPT_OUT_CHK_RPT ( IMPCT_REGIS_PRSNA_ID ,IMPCT_MKTNG_PGM_NBR )
PARTITION BY IMPCT_MKTNG_PGM_NBR ;  