.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
DROP TABLE DEPLOY_WORK.CNTNT_ELEM_582;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
.LABEL L2
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_POSTL_ADDR_582;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
.LABEL L3
DROP TABLE DEPLOY_WORK.VW_DQ_RESULT_SUMMARY_FACT_582;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  
.LABEL L4
DROP TABLE DEPLOY_WORK.SOURCE_CONTROL_582;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L5
DROP TABLE DEPLOY_WORK.CNTNT_ELEM_DUP1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L6
DROP TABLE DEPLOY_WORK.CNTNT_ELEM_DUP2;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L7
DROP TABLE DEPLOY_WORK.CNTNT_ELEM_DUP3;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
