 .logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_BKUP_SP1;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L2
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_POSTL_ADDR_BKUP_SP1;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L3
DROP TABLE DEPLOY_WORK.MATCHD_CNSMR_POSTL_ADDR_BKUP_SP1;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L4
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_OPT_HIST_BKUP_SP1;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;