.logon $TDPID/$TDUSER,$TDPWD


.SET ERROROUT STDOUT;
.SET SESSION CHARSET 'UTF8';
.SET ERRORLEVEL 3807 SEVERITY 0

DATABASE MDM;
.GOTO $Step

.LABEL L0
CREATE TABLE DEPLOY_WORK.DATA_SUPLR_573 AS  iCRM_TBL.DATA_SUPLR WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L1
CREATE TABLE DEPLOY_WORK.DATA_SRCE_573 AS  iCRM_TBL.DATA_SRCE WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;