.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
CREATE TABLE DEPLOY_WORK.CNTNT_ELEM_582 AS 
(SEL * FROM MDM.CNTNT_ELEM )WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L2
CREATE TABLE DEPLOY_WORK.REGIS_PRSNA_POSTL_ADDR_582 AS (SEL * FROM REGIS_PRSNA_POSTL_ADDR WHERE VALID_CNTCT_POINT_IND='') WITH DATA 
PRIMARY INDEX(MKTNG_PGM_NBR,REGIS_PRSNA_ID) PARTITION BY MKTNG_PGM_NBR;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
  .LABEL L3
 CREATE TABLE  DEPLOY_WORK.VW_DQ_RESULT_SUMMARY_FACT_582 AS 
 ( SEL * FROM  DQRM.VW_DQ_RESULT_SUMMARY_FACT) WITH DATA;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  
  .LABEL L4
 CREATE TABLE DEPLOY_WORK.SOURCE_CONTROL_582 AS 
 (SEL * FROM ETL_CTRL.SOURCE_CONTROL) WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 
 
 
 