 .logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
CREATE TABLE DEPLOY_WORK.REGIS_PRSNA_BKUP_SP1 AS 
(SEL * FROM REGIS_PRSNA  WHERE CNTRY_CODE  IN('ESP','PRT') AND MKTNG_PGM_NBR IN( 
SEL MKTNG_PGM_nbr FROM MKTNG_PGM WHERE LEGAL_ENT_NBR NOT IN (22,35)) )WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L2
CREATE TABLE DEPLOY_WORK.REGIS_PRSNA_POSTL_ADDR_BKUP_SP1 AS 
(SEL * FROM REGIS_PRSNA_POSTL_ADDR  WHERE CNTRY_CODE  IN('ESP','PRT') AND MKTNG_PGM_NBR IN( 
SEL MKTNG_PGM_nbr FROM MKTNG_PGM WHERE LEGAL_ENT_NBR NOT IN (22,35)) )WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L3
CREATE TABLE DEPLOY_WORK.MATCHD_CNSMR_POSTL_ADDR_BKUP_SP1 AS 
(SEL * FROM MATCHD_CNSMR_POSTL_ADDR  WHERE CNTRY_CODE  IN('ESP','PRT') AND LEGAL_ENT_NBR NOT IN (22,35))WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L4
CREATE TABLE DEPLOY_WORK.REGIS_PRSNA_OPT_HIST_BKUP_SP1 AS 
(SEL * FROM REGIS_PRSNA_OPT_HIST  WHERE CNTRY_NAME  IN('ESP','PRT') AND MKTNG_PGM_NBR IN(
SEL MKTNG_PGM_nbr FROM MKTNG_PGM WHERE LEGAL_ENT_NBR NOT IN (22,35)) )WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 
 


