.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_AFR_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
	   )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_AFR_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_AFR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_AFR_KEY AS mdm.TRILLIUM_OUTPUT1_AFR_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_AFR_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_AFR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_ARB_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_ARB_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_ARB_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_ARB_KEY AS mdm.TRILLIUM_OUTPUT1_ARB_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_ARB_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_ARB_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_AUS_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND' )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_AUS_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_AUS_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_AUS_KEY AS mdm.TRILLIUM_OUTPUT1_AUS_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_AUS_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_AUS_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_AUT_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND')
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_AUT_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_AUT_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_AUT_KEY AS mdm.TRILLIUM_OUTPUT1_AUT_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_AUT_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_AUT_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_BEL_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND' )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_BEL_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_BEL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_BEL_KEY AS mdm.TRILLIUM_OUTPUT1_BEL_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_BEL_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_BEL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_BGR_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND' )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_BGR_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_BGR_KEY;

RENAME TABLE mdm.TRILLIUM_OUTPUT1_BGR_KEY AS mdm.TRILLIUM_OUTPUT1_BGR_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_BGR_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_BGR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_BRA_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND' )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_BRA_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_BRA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_BRA_KEY AS mdm.TRILLIUM_OUTPUT1_BRA_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_BRA_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_BRA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_CAN_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND')
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_CAN_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_CAN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_CAN_KEY AS mdm.TRILLIUM_OUTPUT1_CAN_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_CAN_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_CAN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_CHE_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND' )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_CHE_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_CHE_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_CHE_KEY AS mdm.TRILLIUM_OUTPUT1_CHE_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_CHE_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_CHE_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_CHN_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND' )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_CHN_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_CHN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_CHN_KEY AS mdm.TRILLIUM_OUTPUT1_CHN_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_CHN_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_CHN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_CZE_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND')
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_CZE_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_CZE_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_CZE_KEY AS mdm.TRILLIUM_OUTPUT1_CZE_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_CZE_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_CZE_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_DEU_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_DEU_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_DEU_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_DEU_KEY AS mdm.TRILLIUM_OUTPUT1_DEU_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_DEU_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_DEU_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_DNK_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_DNK_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_DNK_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_DNK_KEY AS mdm.TRILLIUM_OUTPUT1_DNK_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_DNK_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_DNK_KEY;



CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_EGY_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_EGY_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_EGY_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_EGY_KEY AS mdm.TRILLIUM_OUTPUT1_EGY_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_EGY_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_EGY_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_ESP_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_ESP_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_ESP_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_ESP_KEY AS mdm.TRILLIUM_OUTPUT1_ESP_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_ESP_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_ESP_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_FIN_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_FIN_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_FIN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_FIN_KEY AS mdm.TRILLIUM_OUTPUT1_FIN_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_FIN_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_FIN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_FRA_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_FRA_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_FRA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_FRA_KEY AS mdm.TRILLIUM_OUTPUT1_FRA_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_FRA_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_FRA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_GBR_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_GBR_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_GBR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_GBR_KEY AS mdm.TRILLIUM_OUTPUT1_GBR_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_GBR_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_GBR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_GRC_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_GRC_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_GRC_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_GRC_KEY AS mdm.TRILLIUM_OUTPUT1_GRC_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_GRC_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_GRC_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_HKG_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_HKG_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_HKG_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_HKG_KEY AS mdm.TRILLIUM_OUTPUT1_HKG_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_HKG_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_HKG_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_HRV_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_HRV_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_HRV_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_HRV_KEY AS mdm.TRILLIUM_OUTPUT1_HRV_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_HRV_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_HRV_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_HUN_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_HUN_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_HUN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_HUN_KEY AS mdm.TRILLIUM_OUTPUT1_HUN_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_HUN_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_HUN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_IND_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_IND_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_IND_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_IND_KEY AS mdm.TRILLIUM_OUTPUT1_IND_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_IND_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_IND_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_IRL_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_IRL_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_IRL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_IRL_KEY AS mdm.TRILLIUM_OUTPUT1_IRL_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_IRL_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_IRL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_ISR_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_ISR_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_ISR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_ISR_KEY AS mdm.TRILLIUM_OUTPUT1_ISR_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_ISR_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_ISR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_ITA_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_ITA_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_ITA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_ITA_KEY AS mdm.TRILLIUM_OUTPUT1_ITA_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_ITA_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_ITA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_JPN_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_JPN_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_JPN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_JPN_KEY AS mdm.TRILLIUM_OUTPUT1_JPN_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_JPN_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_JPN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_KOR_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_KOR_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_KOR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_KOR_KEY AS mdm.TRILLIUM_OUTPUT1_KOR_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_KOR_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_KOR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_LA_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_LA_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_LA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_LA_KEY AS mdm.TRILLIUM_OUTPUT1_LA_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_LA_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_LA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_LUX_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_LUX_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_LUX_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_LUX_KEY AS mdm.TRILLIUM_OUTPUT1_LUX_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_LUX_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_LUX_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_MYS_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_MYS_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_MYS_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_MYS_KEY AS mdm.TRILLIUM_OUTPUT1_MYS_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_MYS_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_MYS_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_NLD_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_NLD_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_NLD_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_NLD_KEY AS mdm.TRILLIUM_OUTPUT1_NLD_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_NLD_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_NLD_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_NOR_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_NOR_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_NOR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_NOR_KEY AS mdm.TRILLIUM_OUTPUT1_NOR_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_NOR_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_NOR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_NZL_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_NZL_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_NZL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_NZL_KEY AS mdm.TRILLIUM_OUTPUT1_NZL_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_NZL_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_NZL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_OTH_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_OTH_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_OTH_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_OTH_KEY AS mdm.TRILLIUM_OUTPUT1_OTH_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_OTH_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_OTH_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_PAK_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_PAK_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_PAK_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_PAK_KEY AS mdm.TRILLIUM_OUTPUT1_PAK_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_PAK_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_PAK_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_PHL_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_PHL_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_PHL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_PHL_KEY AS mdm.TRILLIUM_OUTPUT1_PHL_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_PHL_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_PHL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_POL_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_POL_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_POL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_POL_KEY AS mdm.TRILLIUM_OUTPUT1_POL_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_POL_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_POL_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_PRT_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_PRT_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_PRT_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_PRT_KEY AS mdm.TRILLIUM_OUTPUT1_PRT_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_PRT_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_PRT_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_ROU_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_ROU_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_ROU_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_ROU_KEY AS mdm.TRILLIUM_OUTPUT1_ROU_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_ROU_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_ROU_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_RUS_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_RUS_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_RUS_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_RUS_KEY AS mdm.TRILLIUM_OUTPUT1_RUS_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_RUS_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_RUS_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_SGP_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_SGP_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_SGP_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_SGP_KEY AS mdm.TRILLIUM_OUTPUT1_SGP_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_SGP_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_SGP_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_SWE_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_SWE_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_SWE_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_SWE_KEY AS mdm.TRILLIUM_OUTPUT1_SWE_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_SWE_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_SWE_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_TUR_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_TUR_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_TUR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_TUR_KEY AS mdm.TRILLIUM_OUTPUT1_TUR_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_TUR_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_TUR_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_TWN_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_TWN_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_TWN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_TWN_KEY AS mdm.TRILLIUM_OUTPUT1_TWN_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_TWN_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_TWN_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

CREATE MULTISET TABLE mdm.TRILLIUM_OUTPUT1_USA_KEY_NEW ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Seq INTEGER FORMAT '-------------9' NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  	  	  REFERENCE_HOUSEHOLD_ID VARCHAR(50) ,
      REFERENCE_LEGALENTITYKEY VARCHAR(50) ,
      REFERENCE_REGISTRATIONKEY VARCHAR(50),
      SYS_TARGET_ID INTEGER,
      SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND'
 )
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
Insert into mdm.TRILLIUM_OUTPUT1_USA_KEY_NEW(Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE) SEL Seq, MKTNG_PGM_NBR,REGIS_CNSMR_ID_VAL,SYS_TARGET_ID,SYS_SOURCE FROM mdm.TRILLIUM_OUTPUT1_USA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE mdm.TRILLIUM_OUTPUT1_USA_KEY AS mdm.TRILLIUM_OUTPUT1_USA_KEY_CHG0033904;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
RENAME TABLE MDM.TRILLIUM_OUTPUT1_USA_KEY_NEW AS MDM.TRILLIUM_OUTPUT1_USA_KEY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;








