.logon $TDPID/$TDUSER,$TDPWD


.SET ERROROUT STDOUT;
.SET SESSION CHARSET 'UTF8';
.SET ERRORLEVEL 3807 SEVERITY 0

DATABASE MDM;
.GOTO $Step

.LABEL L5
UPDATE ICRM_STAGE.PRSNA_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L6

UPDATE ICRM_STAGE.PRSNA_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L7

UPDATE ICRM_STAGE.PRSNA_TRT_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_TRT_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_TRT_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_TRT_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L8

UPDATE ICRM_STAGE.PRSNA_TRT_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_TRT_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_TRT_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_TRT_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L9

UPDATE ICRM_STAGE.PRSNA_POSTL_ADDR_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_POSTL_ADDR_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_POSTL_ADDR_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_POSTL_ADDR_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L10

UPDATE ICRM_STAGE.PRSNA_POSTL_ADDR_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_POSTL_ADDR_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_POSTL_ADDR_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_POSTL_ADDR_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L11

UPDATE ICRM_STAGE.PRSNA_PHONE_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_PHONE_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_PHONE_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_PHONE_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L12

UPDATE ICRM_STAGE.PRSNA_PHONE_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_PHONE_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_PHONE_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_PHONE_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L13

UPDATE ICRM_STAGE.PRSNA_EMAIL_ADDR_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_EMAIL_ADDR_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_EMAIL_ADDR_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_EMAIL_ADDR_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L14

UPDATE ICRM_STAGE.PRSNA_EMAIL_ADDR_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_EMAIL_ADDR_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_EMAIL_ADDR_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_EMAIL_ADDR_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L15

UPDATE ICRM_STAGE.PRSNA_SOCIAL_NETWK_ACCT_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_SOCIAL_NETWK_ACCT_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_SOCIAL_NETWK_ACCT_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_SOCIAL_NETWK_ACCT_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L16

UPDATE ICRM_STAGE.PRSNA_SOCL_NWK_ACCT_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PRSNA_SOCL_NWK_ACCT_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PRSNA_SOCL_NWK_ACCT_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PRSNA_SOCL_NWK_ACCT_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L17

UPDATE ICRM_STAGE.CNTCT_OPTN_CHCE_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.CNTCT_OPTN_CHCE_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.CNTCT_OPTN_CHCE_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.CNTCT_OPTN_CHCE_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L18

UPDATE ICRM_STAGE.CNTCT_OPTN_CHCE_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.CNTCT_OPTN_CHCE_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.CNTCT_OPTN_CHCE_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.CNTCT_OPTN_CHCE_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L19

UPDATE ICRM_STAGE.CNSMR_AFFLTN_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.CNSMR_AFFLTN_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.CNSMR_AFFLTN_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.CNSMR_AFFLTN_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L20

UPDATE ICRM_STAGE.CNSMR_AFFLTN_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.CNSMR_AFFLTN_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.CNSMR_AFFLTN_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.CNSMR_AFFLTN_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L21

UPDATE ICRM_STAGE.DPEND_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.DPEND_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.DPEND_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.DPEND_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L22

UPDATE ICRM_STAGE.DPEND_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.DPEND_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.DPEND_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.DPEND_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L23

UPDATE ICRM_STAGE.DPEND_TRT_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.DPEND_TRT_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.DPEND_TRT_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.DPEND_TRT_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L24

UPDATE ICRM_STAGE.DPEND_TRT_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.DPEND_TRT_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.DPEND_TRT_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.DPEND_TRT_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L25

UPDATE ICRM_STAGE.PET_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PET_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PET_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PET_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L26

UPDATE ICRM_STAGE.PET_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PET_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PET_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PET_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L27

UPDATE ICRM_STAGE.PET_TRT_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PET_TRT_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PET_TRT_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PET_TRT_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L28

UPDATE ICRM_STAGE.PET_TRT_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PET_TRT_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PET_TRT_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PET_TRT_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L29

UPDATE ICRM_STAGE.REQSTD_INCTV_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.REQSTD_INCTV_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.REQSTD_INCTV_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.REQSTD_INCTV_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L30

UPDATE ICRM_STAGE.SALES_TRANX_LINE_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.SALES_TRANX_LINE_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.SALES_TRANX_LINE_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.SALES_TRANX_LINE_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L31

UPDATE ICRM_STAGE.POS
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.POS.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.POS.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.POS.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L32

UPDATE ICRM_STAGE.POS_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.POS_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.POS_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.POS_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L34

UPDATE ICRM_STAGE.POS_TRANX_LINE
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.POS_TRANX_LINE.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.POS_TRANX_LINE.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.POS_TRANX_LINE.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L35

UPDATE ICRM_STAGE.POS_TRANX_LINE_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.POS_TRANX_LINE_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.POS_TRANX_LINE_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.POS_TRANX_LINE_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L36

UPDATE ICRM_STAGE.POS_RETURN
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.POS_RETURN.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.POS_RETURN.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.POS_RETURN.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L37

UPDATE ICRM_STAGE.POS_RETURN_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.POS_RETURN_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.POS_RETURN_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.POS_RETURN_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L38

UPDATE ICRM_STAGE.POS_TENDER
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.POS_TENDER.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.POS_TENDER.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.POS_TENDER.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L39

UPDATE ICRM_STAGE.POS_TENDER_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.POS_TENDER_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.POS_TENDER_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.POS_TENDER_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L40

UPDATE ICRM_STAGE.CNSMR_ACTN_R2_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.CNSMR_ACTN_R2_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.CNSMR_ACTN_R2_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.CNSMR_ACTN_R2_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L41

UPDATE ICRM_STAGE.CNSMR_ACTN_R2_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.CNSMR_ACTN_R2_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.CNSMR_ACTN_R2_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.CNSMR_ACTN_R2_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L42

UPDATE ICRM_STAGE.CAMPGNRESP_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.CAMPGNRESP_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.CAMPGNRESP_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.CAMPGNRESP_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L43

UPDATE ICRM_STAGE.CAMPGN_HIST_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.CAMPGN_HIST_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.CAMPGN_HIST_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.CAMPGN_HIST_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L44

UPDATE ICRM_STAGE.APPEND_TRT_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.APPEND_TRT_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.APPEND_TRT_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.APPEND_TRT_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L45

UPDATE ICRM_STAGE.APPEND_TRT_STG_HIST
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.APPEND_TRT_STG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.APPEND_TRT_STG_HIST.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.APPEND_TRT_STG_HIST.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L46

UPDATE ICRM_STAGE.PCREGISTRATION_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCREGISTRATION_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCREGISTRATION_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCREGISTRATION_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L47

UPDATE ICRM_STAGE.PCTRAIT_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCTRAIT_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCTRAIT_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCTRAIT_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L48

UPDATE ICRM_STAGE.PCPOSTL_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCPOSTL_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCPOSTL_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCPOSTL_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L49

UPDATE ICRM_STAGE.PCPHONE_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCPHONE_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCPHONE_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCPHONE_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L50

UPDATE ICRM_STAGE.PCEMAIL_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCEMAIL_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCEMAIL_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCEMAIL_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L51

UPDATE ICRM_STAGE.PCSOCIAL_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCSOCIAL_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCSOCIAL_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCSOCIAL_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L52

UPDATE ICRM_STAGE.PCCNTCT_OPTN_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCCNTCT_OPTN_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCCNTCT_OPTN_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCCNTCT_OPTN_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L53

UPDATE ICRM_STAGE.PCDPEND_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCDPEND_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCDPEND_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCDPEND_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L54

UPDATE ICRM_STAGE.PCPET_STG
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE ICRM_STAGE.PCPET_STG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND ICRM_STAGE.PCPET_STG.REGIS_CNSMR_ID_VAL=B.NEW_REGIS_CNSMR_ID_VAL
AND ICRM_STAGE.PCPET_STG.LOAD_ID IN 
(SEL LOAD_ID FROM ETL_CTRL.LOAD_CONTROL WHERE SOURCE_ID=1153);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L55

UPDATE iCRM_TBL.CNSMR_ACTN                   
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE iCRM_TBL.CNSMR_ACTN.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND iCRM_TBL.CNSMR_ACTN.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L56

UPDATE iCRM_TBL.RTN_RULES_REGIS_RUN_LOG_HIST 
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE iCRM_TBL.RTN_RULES_REGIS_RUN_LOG_HIST .MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND iCRM_TBL.RTN_RULES_REGIS_RUN_LOG_HIST .REGIS_PRSNA_ID=B.REGIS_PRSNA_ID;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L57
 
UPDATE iCRM_TBL.PRSNA_POSTL_ADDR_ORIG        
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE iCRM_TBL.PRSNA_POSTL_ADDR_ORIG.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND iCRM_TBL.PRSNA_POSTL_ADDR_ORIG.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L58
 
UPDATE iCRM_TBL.DELETE_REGIS_RUN_LOG_HIST    
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE iCRM_TBL.DELETE_REGIS_RUN_LOG_HIST.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND iCRM_TBL.DELETE_REGIS_RUN_LOG_HIST.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L59
 
UPDATE iCRM_TBL.REGIS_PRSNA                  
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE iCRM_TBL.REGIS_PRSNA.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND iCRM_TBL.REGIS_PRSNA.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L60
 
UPDATE iCRM_TBL.SMS_CMPGN_RESP               
FROM DEPLOY_WORK.PRSNA_STG B
SET REGIS_CNSMR_ID_VAL=B.REGIS_CNSMR_ID_VAL
WHERE iCRM_TBL.SMS_CMPGN_RESP.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND iCRM_TBL.SMS_CMPGN_RESP.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



