.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1

UPDATE  MDM.TRT
SET PRDFN_TRT_IND ='N'
WHERE TRT_NBR NOT IN (SELECT TRT_NBR FROM PREDFND_TRT_VAL);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L2
CREATE VOLATILE TABLE PRDFND_CNT1
AS
(
SEL TRT_NBR,COUNT(*) CNT 
FROM	PREDFND_TRT_VAL
GROUP BY TRT_NBR
HAVING CNT=1 ) 
WITH	DATA
ON COMMIT	PRESERVE ROWS;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L3
UPDATE TRT
FROM	(SEL A.TRT_NBR FROM  PRDFND_CNT1 A
INNER JOIN   PREDFND_TRT_VAL B
ON A.TRT_NBR=B.TRT_NBR
WHERE PREDFND_TRT_TXT IS NULL) C
SET PRDFN_TRT_IND ='N'
WHERE TRT.TRT_NBR=C.TRT_NBR;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



