.logon $TDPID/$TDUSER,$TDPWD
.SET ERRORLEVEL (3807) SEVERITY 0;
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step
.LABEL L1
CREATE TABLE DEPLOY_WORK.TSS_CNTRY_TABLE_MAP_BKP_DMND0001211 AS MDM.TSS_CNTRY_TABLE_MAP WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L2
UPDATE MDM.TSS_CNTRY_TABLE_MAP
SET CALL_BACK_DURATION=2
WHERE CNTRY_NAME IN ('USA','CAN','LA' ,'BRA','TUR');
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 
 .LABEL L3
UPDATE MDM.TSS_CNTRY_TABLE_MAP
SET CALL_BACK_DURATION=3
WHERE CNTRY_NAME IN ('AUS', 'CHN', 'HKG', 'IND', 'JPN', 'KOR', 'MYS', 'SGP', 'OTH', 'PHL', 'TWN', 'NZL');

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;