.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1

ALTER TABLE mdm.gdpr_props
ADD MIME_TYPE VARCHAR(50) ,
 ADD   HOST VARCHAR(50) ,
 ADD  AUTHORZATION VARCHAR(200);
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;





