.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.GOTO $Step

.LABEL L1 

UPDATE MDM.DQRM_CSV_CONFIG set MAX_ROW_COUNT= 2000;

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

  