.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1

CREATE SET TABLE MDM.DQRM_CSV_CONFIG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      MAX_ATTACHMENT_SIZE_BYTES INTEGER NOT NULL,
      MAX_ROW_COUNT INTEGER NOT NULL,
      SYS_CREATED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATION_DATE TIMESTAMP(0),
      SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_CODE VARCHAR(10000) CHARACTER SET LATIN NOT CASESPECIFIC, 
CONSTRAINT DQRM_CSV_CONFIG_PK PRIMARY KEY ( MAX_ATTACHMENT_SIZE_BYTES ,
MAX_ROW_COUNT ))
;

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

  .LABEL L2
  
INSERT	INTO MDM.DQRM_CSV_CONFIG
(MAX_ATTACHMENT_SIZE_BYTES, MAX_ROW_COUNT)
VALUES
(5000000, 2000)

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

  .LABEL L3
  
INSERT INTO ATTRIBUTE_TYPES(ATTRIBUTE_TYPE_ID,ATTRIBUTE_TYPE,DISPLAY_NAME,DATA_TYPE,DATA_FORMAT,DATA_LENGTH,SELECTION_METHOD,AV_CODE_FLAG,AV_SHORT_NAME_FLAG,USER_MANAGED_FLAG,SYS_ENT_STATE)
VALUES((SEL  MAX(ATTRIBUTE_TYPE_ID+1) FROM ATTRIBUTE_TYPES),'DQRM_ESCALATION','DQRM_ESCALATION','Text','YYYY-MM-DD',20,'Default','Y','Y','C','ACTIVE');

INSERT INTO ATTRIBUTE_VALUES(AV_ID,    ATTRIBUTE_TYPE_ID,    ACTIVE_FLAG,    AV_DESCRIPTION,    AV_CODE,    AV_SHORT_NAME,SYS_ENT_STATE)
VALUES((SEL  MAX(AV_ID+1) FROM ATTRIBUTE_VALUES),(SEL ATTRIBUTE_TYPE_ID FROM ATTRIBUTE_TYPES WHERE ATTRIBUTE_TYPE='DQRM_ESCALATION'),'Y','Paulina Jedraszewska~jedraszewska.p@pg.com','NAME','EMAIL','ACTIVE');

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

  .LABEL L4
 
REPLACE VIEW MDM .VW_DQ_MDM_OTHER_EMAILS
AS
LOCKING ROW FOR ACCESS
SEL PROCESS_ID,RULE_RUN_DATE,PROJECT_ID,PROJECT_NAME,RULE_NUMBER ,RULE_REVISION,RULE_NAME,RULE_DESC,REGEXP_REPLACE(bus_impact_notes,x'0a','<br>'||x'0a') AS BUS_IMPACT_NOTES,QUERY,DETAIL_QUERY,ERRORMSG,REGION_CODE,EMAIL_TYPE  
 FROM  DQRM.VW_DQ_MDM_OTHER_EMAILS

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

  .LABEL L5
REPLACE VIEW MDM.VW_DQ_MDM_SERVICE_NOW_EMAILS
AS 
SEL PROCESS_ID                    ,
PROJECT_ID                    ,
RULE_RUN_DATE                 ,
SN_Priority                   ,
SN_Category                   ,
SN_Subcategory                ,
SN_OPENEDBY                   ,
QUERY                         ,
DETAIL_QUERY                  ,
PROJECT_NAME                  ,
RULE_NUMBER                   ,
RULE_REVISION                 ,
RULE_NAME                     ,
RULE_DESC                     ,
RegExp_Replace(NOTES,x'0a','<br>'||x'0a') AS NOTES                         
FROM
dqrm.VW_DQ_MDM_SERVICE_NOW_EMAILS;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;