.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L0

REPLACE VIEW MDM.VW_DQ_METRIC_RESULTS 
AS
LOCKING ROW FOR ACCESS
SELECT 
*
FROM 
DQRM.VW_DQ_METRIC_RESULTS;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L1
 
INS etl_ctrl.format_control
VALUES(25,'DQRM','NA','NA','NA','MDM','NA','NA');


 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
  .LABEL L2

  CREATE SET TABLE MDM.DQRM_ID_GEN ,NO FALLBACK ,
      NO BEFORE JOURNAL,
      NO AFTER JOURNAL,
      CHECKSUM = DEFAULT,
      DEFAULT MERGEBLOCKRATIO
      (
       PRCS_ID INTEGER NOT NULL,
       LOAD_ID INTEGER GENERATED ALWAYS AS IDENTITY
           (START WITH 25 
            INCREMENT BY 100 
            MINVALUE -2147483647 
            MAXVALUE 2147483647 
            NO CYCLE))
UNIQUE PRIMARY INDEX ( PRCS_ID );


 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
  .LABEL L3

REPLACE VIEW MDM.VW_DQ_RESULT_SUMMARY_FACT 
AS
LOCKING ROW FOR ACCESS
SELECT 
*
FROM 
DQRM.VW_DQ_RESULT_SUMMARY_FACT;
  
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


