.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
DROP TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_MDM_dqrm ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L2
DROP TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_MDM_dqrm;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L3
DROP TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_HIERARCHY_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L4
DROP TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_RELN_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L5
DROP TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_HIERARCHY_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L6
DROP TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_RELN_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L7
DROP TABLE DEPLOY_WORK.RPT_ADDR_QLTY_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L8
DROP TABLE DEPLOY_WORK.RPT_CNSMR_NBR_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L9
DROP TABLE DEPLOY_WORK.RPT_DATA_NBR_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L10
DROP TABLE DEPLOY_WORK.RPT_LOAD_NBR_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L11
DROP TABLE DEPLOY_WORK.TRILLIUM_OUTPUT_DUP_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L12
DROP TABLE DEPLOY_WORK.tss_cntry_table_map_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L13
DROP TABLE DEPLOY_WORK.ENV_NM_MDM_dqrm ;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L14
DROP TABLE DEPLOY_WORK.upld_tmplt_prps_MDM_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



