.LOGON 10.36.32.8/sysdba,;

CREATE SET TABLE DQRM_TBL.DQRM_METRIC_TABLE_LEVEL1_NEW ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      PROJECT_ID INTEGER NOT NULL,
      RULE_NUMBER INTEGER TITLE 'RULE_NUMBER' NOT NULL,
      RULE_REVISION INTEGER TITLE 'RULE REVISION' NOT NULL,
      METRIC_DATE DATE FORMAT 'YYYY-MM-DD' TITLE 'METRIC DATE' NOT NULL,
      METRIC_TIME FLOAT FORMAT '99:99:99' TITLE 'METRIC TIME' NOT NULL,
      PROCESS_ID INTEGER TITLE 'PROCESS_ID',
      FROM_BUSINESS_DATE DATE FORMAT 'YYYY-MM-DD',
      TO_BUSINESS_DATE DATE FORMAT 'YYYY-MM-DD',
      ABSOLUTE_DEVIATION_NUM DECIMAL(18,6) TITLE 'ABSOLUTE DEVIATION NUMBER',
      ABSOLUTE_RECORD_NUM DECIMAL(18,6) TITLE 'ABSOLUTE RECORD NUMBER',
      ADJUSTED_DEVIATION_NUM DECIMAL(18,6) TITLE 'ADJUSTED DEVIATION NUMBER',
      ADJUSTED_RECORD_NUM DECIMAL(18,6) TITLE 'ADJUSTED RECORD NUMBER',
      LEGAL_ENTITY INTEGER,   							
      MARKET_SEGMENT INTEGER, 							
      SOURCE_SYSTEM INTEGER   	)						
PRIMARY INDEX ( RULE_NUMBER ,RULE_REVISION )
UNIQUE INDEX ( RULE_NUMBER ,RULE_REVISION ,METRIC_DATE ,METRIC_TIME ,
LEGAL_ENTITY ,MARKET_SEGMENT ,SOURCE_SYSTEM );

INSERT INTO DQRM_TBL.DQRM_METRIC_TABLE_LEVEL1_NEW
SELECT * FROM DQRM_TBL.DQRM_METRIC_TABLE_LEVEL1;

COLLECT STATS  ON  DQRM_TBL.DQRM_METRIC_TABLE_LEVEL1_NEW
COLUMN ( RULE_NUMBER ,RULE_REVISION );

RENAME TABLE DQRM_TBL.DQRM_METRIC_TABLE_LEVEL1 TO DQRM_TBL.DQRM_METRIC_TABLE_LEVEL1_R582 ;

RENAME TABLE DQRM_TBL.DQRM_METRIC_TABLE_LEVEL1_NEW TO DQRM_TBL.DQRM_METRIC_TABLE_LEVEL1;

REPLACE VIEW DQRM.VW_DQ_RESULT_SUMMARY_FACT
(PROJECT_ID
,RULE_NUMBER
,RULE_REVISION
,PROCESS_ID
,MEASURE_DATE
,MEASURE_TIME
,EXECUTION_DATE
,START_TIME
,END_TIME
,TOTAL_RECORDS_MEASURED
,TOTAL_DEVIATIONS_FOUND
,ACTUAL_THRESHOLD_PCT
,QUALITY_TRESHOLD_PCT
,THRESHOLD_FAILURE_FLAG
,LEGAL_ENT_NBR
,MKTNG_PGM_NBR
,DATA_SRCE_NBR
,REGION_CODE
,LEGAL_ENT_NAME
,MKTNG_PGM_DESC
,DATA_SRCE_NAME) 
AS 
LOCKING ROW FOR ACCESS
SELECT	
				 R.PROJECT_ID									 
				,R.RULE_NUMBER								
				,R.RULE_REVISION							
				,R.PROCESS_ID								
				,METRIC_DATE								
				,METRIC_TIME
				,RL.EXECUTION_DATE
				,RL.START_TIME
				,RL.END_TIME
				,COALESCE(CAST(ABSOLUTE_RECORD_NUM AS DECIMAL(12)), 0)	ABSOLUTE_RECORD_NUM
				,COALESCE(CAST(ABSOLUTE_DEVIATION_NUM AS DECIMAL(12)), 0) ABSOLUTE_DEVIATION_NUM
				,((ABSOLUTE_RECORD_NUM-ABSOLUTE_DEVIATION_NUM) / ABSOLUTE_RECORD_NUM) * 100  ACTUAL_THRESHOLD_PCT
				,DQR.QUALITY_THRESHOLD_PCT
				,CASE WHEN ACTUAL_THRESHOLD_PCT < QUALITY_THRESHOLD_PCT THEN 'Y'
					ELSE 'N' END THRESHOLD_FAILURE_FLAG
				,COALESCE(TRIM(LEGAL_ENTITY),' ') LEGAL_ENT_NBR
				,COALESCE(TRIM(MARKET_SEGMENT),' ') MKTNG_PGM_NBR
				,COALESCE(TRIM(SOURCE_SYSTEM),' ') DATA_SRCE_NBR
				,COALESCE(GEOC_REGN_CODE, ' ') REGION_CODE
				,COALESCE(LEGAL_ENT_NAME, ' ') LEGAL_ENT_NAME
				,COALESCE(MKTNG_PGM_DESC, ' ') MKTNG_PGM_DESC
				,COALESCE(DATA_SRCE_NAME, ' ') DATA_SRCE_NAME
				
 				
FROM	DQRM_TBL.VW_DQ_METRIC_RESULTS R
INNER JOIN DQRM.VW_DQ_DATA_QUALITY_RULE_DIM DQR
ON R.PROJECT_ID = DQR.PROJECT_ID
AND R.RULE_NUMBER = DQR.RULE_NUMBER
AND R.RULE_REVISION = DQR.RULE_REVISION
LEFT OUTER JOIN ICRM.LEGAL_ENT L
ON  TRIM(R.LEGAL_ENTITY)= L.LEGAL_ENT_NBR   
LEFT OUTER JOIN ICRM.MKTNG_PGM M
ON MARKET_SEGMENT = M.MKTNG_PGM_NBR   		
LEFT OUTER JOIN (
SELECT	DATA_SRCE_NBR, MAX(DATA_SRCE_NAME) DATA_SRCE_NAME
FROM ICRM.DATA_SRCE
GROUP BY 1
)D
ON SOURCE_SYSTEM = D.DATA_SRCE_NBR  		
LEFT OUTER JOIN 
(SELECT L.PROCESS_ID, L.PROJECT_ID, L.RULE_ID, L.RULE_NAME,
		L.EXECUTION_DATE, L.START_TIME, L.END_TIME
FROM
(SELECT	PROCESS_ID, PROJECT_ID, RULE_ID, MAX(START_TIME) START_TIME
FROM DQRM_TBL.DQ_RUNTIME_LOG
WHERE START_TIME IS NOT NULL
AND END_TIME IS NOT NULL
GROUP BY 1,2,3) A
INNER JOIN DQRM_TBL.DQ_RUNTIME_LOG L
ON A.PROCESS_ID = L.PROCESS_ID
AND A.PROJECT_ID = L.PROJECT_ID
AND A.RULE_ID = L.RULE_ID
AND A.START_TIME = L.START_TIME) RL
ON R.PROCESS_ID = RL.PROCESS_ID
AND DQR.RULE_ID = RL.RULE_ID;


REPLACE VIEW DQRM_TBL.VW_DQ_RESULT_SUMMARY
(PROJECT_ID
,RULE_NUMBER
,RULE_REVISION
,PROCESS_ID
,RULE_ID
,RULE_NAME
,RULE_DESC
,MEASURE_DATE
,MEASURE_TIME
,TOTAL_RECORDS_MEASURED
,TOTAL_DEVIATIONS_FOUND
,ACTUAL_THRESHOLD_PCT
,QUALITY_TRESHOLD_PCT
,THRESHOLD_FAILURE_FLAG
,LEGAL_ENT_NBR
,REGION_CODE
) 
AS 
LOCKING ROW FOR ACCESS
SELECT	
				 R.PROJECT_ID									 
				,R.RULE_NUMBER								
				,R.RULE_REVISION							
				,R.PROCESS_ID			
				,DQR.RULE_ID
				,DQR.RULE_NAME
				,DQR.RULE_DESCRIPTION
				,METRIC_DATE								
				,METRIC_TIME
				,COALESCE(CAST(ABSOLUTE_RECORD_NUM AS DECIMAL(12)), 0)	ABSOLUTE_RECORD_NUM
				,COALESCE(CAST(ABSOLUTE_DEVIATION_NUM AS DECIMAL(12)), 0) ABSOLUTE_DEVIATION_NUM
				,((ABSOLUTE_RECORD_NUM-ABSOLUTE_DEVIATION_NUM) / ABSOLUTE_RECORD_NUM) * 100  ACTUAL_THRESHOLD_PCT
				,DQR.QUALITY_THRESHOLD_PCT
				,CASE WHEN ACTUAL_THRESHOLD_PCT < QUALITY_THRESHOLD_PCT THEN 'Y'
					ELSE 'N' END THRESHOLD_FAILURE_FLAG
				,COALESCE(TRIM(LEGAL_ENTITY),' ') LEGAL_ENT_NBR
				,COALESCE(GEOC_REGN_CODE, ' ') REGION_CODE

 				
FROM	DQRM_TBL.VW_DQ_METRIC_RESULTS R
INNER JOIN DQRM_TBL.VW_DQ_DATA_QUALITY_RULE_DIM DQR
ON R.PROJECT_ID = DQR.PROJECT_ID
AND R.RULE_NUMBER = DQR.RULE_NUMBER
AND R.RULE_REVISION = DQR.RULE_REVISION
LEFT OUTER JOIN ICRM.LEGAL_ENT L
ON R.LEGAL_ENTITY = L.LEGAL_ENT_NBR;  	

ALTER PROCEDURE DQRM_TBL.DQ_PROCESS_EMAILS COMPILE;
7:52 AM 2/25/2017

9:20 AM 2/25/2017
