.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
CREATE TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_MDM_dqrm AS MDM.ATTRIBUTE_VALUES WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L2
CREATE TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_MDM_dqrm AS MDM.ATTRIBUTE_TYPES WITH DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L3
CREATE TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_HIERARCHY_MDM_dqrm AS MDM.ATTRIBUTE_TYPES_HIERARCHY WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L4
CREATE TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_RELN_MDM_dqrm AS MDM.ATTRIBUTE_TYPES_RELN WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L5
CREATE TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_HIERARCHY_MDM_dqrm AS MDM.ATTRIBUTE_VALUES_HIERARCHY WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L6
CREATE TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_RELN_MDM_dqrm AS MDM.ATTRIBUTE_VALUES_RELN WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L7
CREATE TABLE DEPLOY_WORK.RPT_ADDR_QLTY_MDM_dqrm AS MDM.RPT_ADDR_QLTY WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L8
CREATE TABLE DEPLOY_WORK.RPT_CNSMR_NBR_MDM_dqrm AS MDM.RPT_CNSMR_NBR WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L9
CREATE TABLE DEPLOY_WORK.RPT_DATA_NBR_MDM_dqrm AS MDM.RPT_DATA_NBR WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L10
CREATE TABLE DEPLOY_WORK.RPT_LOAD_NBR_MDM_dqrm AS MDM.RPT_LOAD_NBR WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L11
CREATE TABLE DEPLOY_WORK.TRILLIUM_OUTPUT_DUP_MDM_dqrm AS MDM.TRILLIUM_OUTPUT_DUP1 WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L12
CREATE TABLE DEPLOY_WORK.tss_cntry_table_map_MDM_dqrm AS MDM.tss_cntry_table_map WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L13
CREATE TABLE DEPLOY_WORK.ENV_NM_MDM_dqrm AS MDM.ENV_NM WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L14
RENAME TABLE MDM.ERR_PRSNA_STG TO ERR_PRSNA_STG_BKUP_dqrm;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L15
CREATE TABLE DEPLOY_WORK.upld_tmplt_prps_MDM_dqrm AS MDM.upld_tmplt_prps WITH DATA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



