.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1

CREATE MULTISET GLOBAL TEMPORARY TABLE MDM.INCTV_XML ,FALLBACK ,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     LOG
     (
      Loadid INTEGER,
      xmlfile XML)
NO PRIMARY INDEX 
ON COMMIT PRESERVE ROWS;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L2
CREATE SET TABLE MDM.INCTV_ITEM_STG ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      INCTV_NBR INTEGER NOT NULL,
      INCTV_ITEM_QTY INTEGER,
      INCTV_ITEM_DESC VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
      INCTV_ITEM_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      INCTV_ITEM_NBR INTEGER NOT NULL,
      PROD_ITEM_UPC VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      CATEG_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      SEG_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      BRAND_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      SUB_BRAND_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      ITEM_VERS_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      BRAND_FAMLY_ID VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      PROD_FAMLY_ID VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      GLOBAL_FORM_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC, 
CONSTRAINT INCTV_ITEM_STG_PK PRIMARY KEY ( INCTV_NBR ,INCTV_ITEM_NBR ));
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L3
CREATE SET TABLE MDM.INCTV_ITEM_STG_V ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      INCTV_NBR INTEGER NOT NULL,
      INCTV_ITEM_QTY INTEGER,
      INCTV_ITEM_DESC VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
      INCTV_ITEM_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      INCTV_ITEM_NBR INTEGER NOT NULL,
      PROD_ITEM_UPC VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      CATEG_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      SEG_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      BRAND_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      SUB_BRAND_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      ITEM_VERS_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      BRAND_FAMLY_ID VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      PROD_FAMLY_ID VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      GLOBAL_FORM_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      CHOICE INTEGER, 
CONSTRAINT INCTV_ITEM_STG_PK PRIMARY KEY ( INCTV_NBR ,INCTV_ITEM_NBR ))
;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L4
REPLACE VIEW MDM.INCTV_ITEM_STG_VIEW AS LOCKING ROW FOR ACCESS SELECT * FROM MDM.INCTV_ITEM_STG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L5
REPLACE VIEW MDM.INCTV_ITEM_STG_V_VIEW AS LOCKING ROW FOR ACCESS SELECT * FROM MDM.INCTV_ITEM_STG_V;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;