.logon $TDPID/$TDUSER,$TDPWD


.SET ERROROUT STDOUT;
.SET SESSION CHARSET 'UTF8';

DATABASE MDM;

.GOTO $Step


 .LABEL L0

--Deleting the Orphan records from Matched tables

CREATE TABLE MDM.MATCH_DATA_TEMP1 AS (
SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.REGIS_PRSNA
WHERE LEGAL_ENT_NBR IN (22,35,15,42)
GROUP BY 1,2)
WITH DATA
PRIMARY INDEX(MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR)
PARTITION BY LEGAL_ENT_NBR ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L1

DEL FROM ICRM_TBL.MATCHD_CNSMR_PRSNA_TRT
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L2


 DEL FROM ICRM_TBL.MATCHD_CNSMR_PRSNA
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L3


 DEL FROM ICRM_TBL.MATCHD_CNSMR_POSTL_ADDR
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L4


 DEL FROM ICRM_TBL.MATCHD_CNSMR_SOC_NET_ACCT
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L5

 DEL FROM ICRM_TBL.MATCHD_CNSMR_PHONE
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L6

 DEL FROM ICRM_TBL.MATCHD_CNSMR_EMAIL_ADDR
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L7

 DEL FROM ICRM_TBL.HSHLD_PRSNA
WHERE (HSHLD_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT HSHLD_PRSNA_ID,LEGAL_ENT_NBR 
FROM ICRM_TBL.MATCHD_CNSMR_PRSNA) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L8

DEL FROM ICRM_TBL.MATCHD_CNSMR_SCORE
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L9

DEL FROM ICRM_TBL.CNSMR_LIFE_DATA
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L10

DEL FROM ICRM_TBL.CNSMR_INTEL_ACTION_VAL
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L11

DEL FROM ICRM_TBL.CNSMR_MKTNG_PGM_DATA
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L12
 
DEL FROM ICRM_TBL.CNSMR_INTEL_COMM_VAL
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L13


DEL FROM ICRM_TBL.CNSMR_PRSNL_DATA
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L14

DEL FROM ICRM_TBL.CNSMR_BRAND_HIST
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L15

DEL FROM ICRM_TBL.CNSMR_LIFE_TRT
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L16

DEL FROM ICRM_TBL.CNSMR_PRSNL_TRT
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L17

DEL FROM ICRM_TBL.CNSMR_SEG_MBR
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L18

/*DEL FROM ICRM_TBL.CNSMR_CNTCT_SNPSH
WHERE (MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR) NOT IN 
(SELECT MATCHD_CNSMR_PRSNA_ID,LEGAL_ENT_NBR 
FROM MDM.MATCH_DATA_TEMP1) AND LEGAL_ENT_NBR IN (22,35,15,42);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L19
*/

DEL FROM ICRM_TBL.CNSMR_SCORE_RUN
WHERE (CNSMR_SCORE_RUN_ID,CNSMR_SCORE_NBR) NOT IN 
(SELECT CNSMR_SCORE_RUN_ID,CNSMR_SCORE_NBR
FROM ICRM_TBL.MATCHD_CNSMR_SCORE
UNION ALL
SELECT CNSMR_SCORE_RUN_ID,CNSMR_SCORE_NBR
FROM ICRM_TBL.MATCHD_CNSMR_SCORE_HIST
);

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L20

COLLECT STATS USER_WORK.MATCHD_CNSMR_PRSNA_TRT_MATCH
COLUMN MKTNG_PGM_NBR;
COLLECT STATS USER_WORK.MATCHD_CNSMR_PRSNA_TRT_MATCH
COLUMN REGIS_PRSNA_ID;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L21

INSERT INTO ICRM_TBL.MATCHD_CNSMR_PRSNA_TRT
(
MATCHD_CNSMR_PRSNA_ID         ,
LEGAL_ENT_NBR                 ,
TRT_NBR                       ,
MATCHD_PRSNA_TRT_DATE         ,
MATCHD_PRSNA_TRT_TXT          ,
MATCHD_PRSNA_TRT_SEQ_NBR      ,
DATA_SRCE_NBR                 ,
SYS_SOURCE                    ,
SYS_TARGET_ID                 ,
SYS_AUTH_ID                   ,
SYS_CREATED_BY                ,
SYS_CREATION_DATE             ,
SYS_LAST_MODIFIED_DATE        ,
SYS_ENT_STATE                 ,
SYS_LAST_MODIFIED_BY          ,
SYS_NC_TYPE                   ,
SYS_ERR_CODE                  ,
SYS_ERR_SVRTY                 
)
SELECT
B.MATCHD_CNSMR_PRSNA_ID         ,
B.LEGAL_ENT_NBR                 ,
A.TRT_NBR                       ,
A.MATCHD_PRSNA_TRT_DATE         ,
A.MATCHD_PRSNA_TRT_TXT          ,
A.MATCHD_PRSNA_TRT_SEQ_NBR      ,
A.DATA_SRCE_NBR                 ,
A.SYS_SOURCE                    ,
A.SYS_TARGET_ID                 ,
A.SYS_AUTH_ID                   ,
A.SYS_CREATED_BY                ,
A.SYS_CREATION_DATE             ,
A.SYS_LAST_MODIFIED_DATE        ,
A.SYS_ENT_STATE                 ,
A.SYS_LAST_MODIFIED_BY          ,
A.SYS_NC_TYPE                   ,
A.SYS_ERR_CODE                  ,
A.SYS_ERR_SVRTY                 
FROM 
USER_WORK.MATCHD_CNSMR_PRSNA_TRT_MATCH A
INNER JOIN MDM.REGIS_PRSNA B
ON A.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID
AND A.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND A.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM  WHERE LEGAL_ENT_NBR =42)
AND B.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM  WHERE LEGAL_ENT_NBR =42)
GROUP BY B.MATCHD_CNSMR_PRSNA_ID         ,
B.LEGAL_ENT_NBR                 ,
A.TRT_NBR                       ,
A.MATCHD_PRSNA_TRT_DATE         ,
A.MATCHD_PRSNA_TRT_TXT          ,
A.MATCHD_PRSNA_TRT_SEQ_NBR      ,
A.DATA_SRCE_NBR                 ,
A.SYS_SOURCE                    ,
A.SYS_TARGET_ID                 ,
A.SYS_AUTH_ID                   ,
A.SYS_CREATED_BY                ,
A.SYS_CREATION_DATE             ,
A.SYS_LAST_MODIFIED_DATE        ,
A.SYS_ENT_STATE                 ,
A.SYS_LAST_MODIFIED_BY          ,
A.SYS_NC_TYPE                   ,
A.SYS_ERR_CODE                  ,
A.SYS_ERR_SVRTY;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L22

 
INSERT INTO ICRM_TBL.MATCHD_CNSMR_PRSNA_TRT
(
MATCHD_CNSMR_PRSNA_ID         ,
LEGAL_ENT_NBR                 ,
TRT_NBR                       ,
MATCHD_PRSNA_TRT_DATE         ,
MATCHD_PRSNA_TRT_TXT          ,
MATCHD_PRSNA_TRT_SEQ_NBR      ,
DATA_SRCE_NBR                 ,
SYS_SOURCE                    ,
SYS_TARGET_ID                 ,
SYS_AUTH_ID                   ,
SYS_CREATED_BY                ,
SYS_CREATION_DATE             ,
SYS_LAST_MODIFIED_DATE        ,
SYS_ENT_STATE                 ,
SYS_LAST_MODIFIED_BY          ,
SYS_NC_TYPE                   ,
SYS_ERR_CODE                  ,
SYS_ERR_SVRTY                 
)
SELECT
B.MATCHD_CNSMR_PRSNA_ID         ,
B.LEGAL_ENT_NBR                 ,
A.TRT_NBR                       ,
A.MATCHD_PRSNA_TRT_DATE         ,
A.MATCHD_PRSNA_TRT_TXT          ,
A.MATCHD_PRSNA_TRT_SEQ_NBR      ,
A.DATA_SRCE_NBR                 ,
A.SYS_SOURCE                    ,
A.SYS_TARGET_ID                 ,
A.SYS_AUTH_ID                   ,
A.SYS_CREATED_BY                ,
A.SYS_CREATION_DATE             ,
A.SYS_LAST_MODIFIED_DATE        ,
A.SYS_ENT_STATE                 ,
A.SYS_LAST_MODIFIED_BY          ,
A.SYS_NC_TYPE                   ,
A.SYS_ERR_CODE                  ,
A.SYS_ERR_SVRTY                 
FROM 
USER_WORK.MATCHD_CNSMR_PRSNA_TRT_MATCH A
INNER JOIN MDM.REGIS_PRSNA B
ON A.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID
AND A.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND A.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM  WHERE LEGAL_ENT_NBR =35)
AND B.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM  WHERE LEGAL_ENT_NBR =35)
GROUP BY B.MATCHD_CNSMR_PRSNA_ID         ,
B.LEGAL_ENT_NBR                 ,
A.TRT_NBR                       ,
A.MATCHD_PRSNA_TRT_DATE         ,
A.MATCHD_PRSNA_TRT_TXT          ,
A.MATCHD_PRSNA_TRT_SEQ_NBR      ,
A.DATA_SRCE_NBR                 ,
A.SYS_SOURCE                    ,
A.SYS_TARGET_ID                 ,
A.SYS_AUTH_ID                   ,
A.SYS_CREATED_BY                ,
A.SYS_CREATION_DATE             ,
A.SYS_LAST_MODIFIED_DATE        ,
A.SYS_ENT_STATE                 ,
A.SYS_LAST_MODIFIED_BY          ,
A.SYS_NC_TYPE                   ,
A.SYS_ERR_CODE                  ,
A.SYS_ERR_SVRTY;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L23

 INSERT INTO ICRM_TBL.MATCHD_CNSMR_PRSNA_TRT
(
MATCHD_CNSMR_PRSNA_ID         ,
LEGAL_ENT_NBR                 ,
TRT_NBR                       ,
MATCHD_PRSNA_TRT_DATE         ,
MATCHD_PRSNA_TRT_TXT          ,
MATCHD_PRSNA_TRT_SEQ_NBR      ,
DATA_SRCE_NBR                 ,
SYS_SOURCE                    ,
SYS_TARGET_ID                 ,
SYS_AUTH_ID                   ,
SYS_CREATED_BY                ,
SYS_CREATION_DATE             ,
SYS_LAST_MODIFIED_DATE        ,
SYS_ENT_STATE                 ,
SYS_LAST_MODIFIED_BY          ,
SYS_NC_TYPE                   ,
SYS_ERR_CODE                  ,
SYS_ERR_SVRTY                 
)
SELECT
B.MATCHD_CNSMR_PRSNA_ID         ,
B.LEGAL_ENT_NBR                 ,
A.TRT_NBR                       ,
A.MATCHD_PRSNA_TRT_DATE         ,
A.MATCHD_PRSNA_TRT_TXT          ,
A.MATCHD_PRSNA_TRT_SEQ_NBR      ,
A.DATA_SRCE_NBR                 ,
A.SYS_SOURCE                    ,
A.SYS_TARGET_ID                 ,
A.SYS_AUTH_ID                   ,
A.SYS_CREATED_BY                ,
A.SYS_CREATION_DATE             ,
A.SYS_LAST_MODIFIED_DATE        ,
A.SYS_ENT_STATE                 ,
A.SYS_LAST_MODIFIED_BY          ,
A.SYS_NC_TYPE                   ,
A.SYS_ERR_CODE                  ,
A.SYS_ERR_SVRTY                 
FROM 
USER_WORK.MATCHD_CNSMR_PRSNA_TRT_MATCH A
INNER JOIN MDM.REGIS_PRSNA B
ON A.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID
AND A.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND A.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM  WHERE LEGAL_ENT_NBR =22)
AND B.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM  WHERE LEGAL_ENT_NBR =22)
GROUP BY B.MATCHD_CNSMR_PRSNA_ID         ,
B.LEGAL_ENT_NBR                 ,
A.TRT_NBR                       ,
A.MATCHD_PRSNA_TRT_DATE         ,
A.MATCHD_PRSNA_TRT_TXT          ,
A.MATCHD_PRSNA_TRT_SEQ_NBR      ,
A.DATA_SRCE_NBR                 ,
A.SYS_SOURCE                    ,
A.SYS_TARGET_ID                 ,
A.SYS_AUTH_ID                   ,
A.SYS_CREATED_BY                ,
A.SYS_CREATION_DATE             ,
A.SYS_LAST_MODIFIED_DATE        ,
A.SYS_ENT_STATE                 ,
A.SYS_LAST_MODIFIED_BY          ,
A.SYS_NC_TYPE                   ,
A.SYS_ERR_CODE                  ,
A.SYS_ERR_SVRTY;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L24

 INSERT INTO ICRM_TBL.MATCHD_CNSMR_PRSNA_TRT
(
MATCHD_CNSMR_PRSNA_ID         ,
LEGAL_ENT_NBR                 ,
TRT_NBR                       ,
MATCHD_PRSNA_TRT_DATE         ,
MATCHD_PRSNA_TRT_TXT          ,
MATCHD_PRSNA_TRT_SEQ_NBR      ,
DATA_SRCE_NBR                 ,
SYS_SOURCE                    ,
SYS_TARGET_ID                 ,
SYS_AUTH_ID                   ,
SYS_CREATED_BY                ,
SYS_CREATION_DATE             ,
SYS_LAST_MODIFIED_DATE        ,
SYS_ENT_STATE                 ,
SYS_LAST_MODIFIED_BY          ,
SYS_NC_TYPE                   ,
SYS_ERR_CODE                  ,
SYS_ERR_SVRTY                 
)
SELECT
B.MATCHD_CNSMR_PRSNA_ID         ,
B.LEGAL_ENT_NBR                 ,
A.TRT_NBR                       ,
A.MATCHD_PRSNA_TRT_DATE         ,
A.MATCHD_PRSNA_TRT_TXT          ,
A.MATCHD_PRSNA_TRT_SEQ_NBR      ,
A.DATA_SRCE_NBR                 ,
A.SYS_SOURCE                    ,
A.SYS_TARGET_ID                 ,
A.SYS_AUTH_ID                   ,
A.SYS_CREATED_BY                ,
A.SYS_CREATION_DATE             ,
A.SYS_LAST_MODIFIED_DATE        ,
A.SYS_ENT_STATE                 ,
A.SYS_LAST_MODIFIED_BY          ,
A.SYS_NC_TYPE                   ,
A.SYS_ERR_CODE                  ,
A.SYS_ERR_SVRTY                 
FROM 
USER_WORK.MATCHD_CNSMR_PRSNA_TRT_MATCH A
INNER JOIN MDM.REGIS_PRSNA B
ON A.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID
AND A.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND A.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM  WHERE LEGAL_ENT_NBR =15)
AND B.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM  WHERE LEGAL_ENT_NBR =15)
GROUP BY B.MATCHD_CNSMR_PRSNA_ID         ,
B.LEGAL_ENT_NBR                 ,
A.TRT_NBR                       ,
A.MATCHD_PRSNA_TRT_DATE         ,
A.MATCHD_PRSNA_TRT_TXT          ,
A.MATCHD_PRSNA_TRT_SEQ_NBR      ,
A.DATA_SRCE_NBR                 ,
A.SYS_SOURCE                    ,
A.SYS_TARGET_ID                 ,
A.SYS_AUTH_ID                   ,
A.SYS_CREATED_BY                ,
A.SYS_CREATION_DATE             ,
A.SYS_LAST_MODIFIED_DATE        ,
A.SYS_ENT_STATE                 ,
A.SYS_LAST_MODIFIED_BY          ,
A.SYS_NC_TYPE                   ,
A.SYS_ERR_CODE                  ,
A.SYS_ERR_SVRTY;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L25
