.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step



 .LABEL L1
CREATE SET TABLE DEPLOY_WORK.CNTNT_ELEM_DUP1 AS 
(SELECT * FROM MDM.CNTNT_ELEM )WITH NO DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L2
INSERT INTO DEPLOY_WORK.CNTNT_ELEM_DUP1
SEL * FROM MDM.CNTNT_ELEM
WHERE CNTNT_ELEM_ID IN 
(SEL CNTNT_ELEM_ID 
FROM MDM.CNTNT_ELEM 
GROUP BY 1 
HAVING COUNT(*)>1);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L3
DEL FROM MDM.CNTNT_ELEM
WHERE CNTNT_ELEM_ID IN 
(SEL CNTNT_ELEM_ID 
FROM MDM.CNTNT_ELEM 
GROUP BY 1 
HAVING COUNT(*)>1);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L4
CREATE SET TABLE DEPLOY_WORK.CNTNT_ELEM_DUP2 AS 
(SELECT * FROM MDM.CNTNT_ELEM )WITH NO DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 

.LABEL L5
INSERT INTO DEPLOY_WORK.CNTNT_ELEM_DUP2
SEL * FROM DEPLOY_WORK.CNTNT_ELEM_DUP1
QUALIFY RANK() OVER (PARTITION BY CNTNT_ELEM_ID,MKTNG_PGM_NBR ORDER BY  SYS_CREATION_DATE DESC ) = 1;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L6
INSERT INTO MDM.CNTNT_ELEM 
SEL * FROM DEPLOY_WORK.CNTNT_ELEM_DUP2
WHERE CNTNT_ELEM_ID IN 
(SEL CNTNT_ELEM_ID 
FROM DEPLOY_WORK.CNTNT_ELEM_DUP2
GROUP BY 1 
HAVING COUNT(*) = 1);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L7
DELETE FROM DEPLOY_WORK.CNTNT_ELEM_DUP2
WHERE CNTNT_ELEM_ID IN 
(SEL CNTNT_ELEM_ID 
FROM DEPLOY_WORK.CNTNT_ELEM_DUP2
GROUP BY 1 
HAVING COUNT(*) = 1);
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L8
CREATE SET TABLE DEPLOY_WORK.CNTNT_ELEM_DUP3 AS 
(SELECT * FROM MDM.CNTNT_ELEM )WITH NO DATA;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L9
INSERT INTO DEPLOY_WORK.CNTNT_ELEM_DUP3
SEL * FROM DEPLOY_WORK.CNTNT_ELEM_DUP2
QUALIFY RANK() OVER (PARTITION BY CNTNT_ELEM_ID ORDER BY  SYS_CREATION_DATE DESC ) = 1;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L10
INSERT INTO CNTNT_ELEM
SEL * FROM DEPLOY_WORK.CNTNT_ELEM_DUP2
QUALIFY RANK() OVER (PARTITION BY CNTNT_ELEM_ID ORDER BY  SYS_CREATION_DATE ) = 1;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  
 .LABEL L11
UPDATE DEPLOY_WORK.CNTNT_ELEM_DUP3
FROM (SELECT  old_id + row_num AS new_id,CNTNT_ELEM_ID
               FROM    (
        							SELECT  a.CNTNT_ELEM_ID ,
                						b.max_id AS old_id,
                						ROW_NUMBER() OVER (ORDER BY 1) AS row_num 
        							FROM    DEPLOY_WORK.CNTNT_ELEM_DUP3 a
                					CROSS JOIN
                					(SELECT MAX(CNTNT_ELEM_ID) AS max_id FROM CNTNT_ELEM) b
        						)main
			)temp

SET CNTNT_ELEM_ID = temp.new_id
WHERE temp.CNTNT_ELEM_ID = DEPLOY_WORK.CNTNT_ELEM_DUP3.CNTNT_ELEM_ID;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 .LABEL L12
INSERT INTO CNTNT_ELEM
SEL * FROM DEPLOY_WORK.CNTNT_ELEM_DUP3;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



.LABEL L13
CREATE VOLATILE TABLE MDM.TEMP AS
(SEL A.REGIS_PRSNA_ID, A.MKTNG_PGM_NBR,A.CNTCT_POINT_CATEG_CODE,
	(CASE 
		WHEN (PR_GEOCODE_FAIL IN ('0','9')
			AND CNTRY_CODE IN ('JPN','TWN','KOR','AUS','MYS','SGP','USA','CAN','IDN','THA','VNM'))
			OR (PR_GEOCODE_FAIL IN ('0','3')
			AND CNTRY_CODE IN ('NZL'))      
			OR CNTRY_CODE IN ('ARG','CHL','MEX','BRA')
			OR (A.PR_REV_GROUP IN ('0','000','001','002','003','005','008','009','010','012','019')
			AND  CNTRY_CODE NOT IN ('JPN','TWN','KOR','NZL','AUS','MYS',
				'SGP','USA','CAN','BRA','MEX','FRA','BEL','NLD','ITA','GRC','AUT','CHE','DEU','ESP','IRL'
				,'DNK','FIN','NOR','SWE','GBR','PRT','IDN','THA','VNM'))
			OR (PR_GEOCODE_FAIL = '0' AND A.PR_REV_GROUP IN ('000','002','005','007','008','009','010','014','018','020')
			AND CNTRY_CODE IN ('FRA'))
			OR (PR_GEOCODE_FAIL IN ('0','3') AND A.PR_REV_GROUP IN ('000','002','005','008','009','010','018')
			AND CNTRY_CODE IN ('IRL','AUT','ITA'))         
			OR (PR_GEOCODE_FAIL IN ('0') AND A.PR_REV_GROUP IN ('000','002','005','008','009','010','018')
			AND CNTRY_CODE IN ('CHE','DEU','BEL','NLD'))
			OR (PR_GEOCODE_FAIL IN ('0','3','8') AND A.PR_REV_GROUP IN ('000','002','005','008','009','010','018')
			AND CNTRY_CODE IN ('DNK','FIN','NOR'))   
			OR (PR_GEOCODE_FAIL IN ('0','3','8') AND A.PR_REV_GROUP IN ('000','002','005','007','008','009','010','018')
			AND CNTRY_CODE IN ('SWE'))       
			OR (PR_GEOCODE_FAIL = '0' AND A.PR_REV_GROUP IN ('000','002','005','008','009','010','014','018')
			AND CNTRY_CODE IN ('GBR')) 
		THEN 'Y'
		WHEN CNTRY_CODE='MYS' AND TRIM(COALESCE(A.POSTL_AREA_CODE,''))<>'' 
			AND (CHAR(TRIM(COALESCE(A.POSTL_AREA_CODE,'')))=5 
			AND SUBSTR(TRIM(COALESCE(A.POSTL_AREA_CODE,'')),1,2)<>'01'
			AND SUBSTR(TRIM(COALESCE(A.POSTL_AREA_CODE,'')),1,1)='0')
		THEN 'N'
		WHEN ((PR_GEOCODE_FAIL IS NULL OR TRIM(PR_GEOCODE_FAIL) = '') 
			AND (A.PR_REV_GROUP IS NULL OR TRIM(A.PR_REV_GROUP) = ''))
			OR  CNTRY_CODE IN ('HKG','GRC')
			OR  (PR_GEOCODE_FAIL NOT IN ('0','9')
			AND CNTRY_CODE IN ('JPN','TWN','KOR','NZL','AUS','MYS','SGP','IDN','THA','VNM'))
		THEN B.VALID_CNTCT_POINT_IND
		WHEN CNTRY_CODE IN ('ESP','PRT')
		THEN B.VALID_CNTCT_POINT_IND
		ELSE 'N'
	END )VALID_CNTCT_POINT_IND

FROM REGIS_PRSNA_POSTL_ADDR A
INNER JOIN PRSNA_POSTL_ADDR_ORIG B
ON A.REGIS_PRSNA_ID=B.REGIS_PRSNA_ID 
AND A.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND A.CNTCT_POINT_CATEG_CODE=B.CNTCT_POINT_CATEG_CODE
WHERE A.VALID_CNTCT_POINT_IND='')
WITH DATA
ON COMMIT PRESERVE ROWS;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  
  
.LABEL L14
COLLECT STATS COLUMN(REGIS_PRSNA_ID) ON  MDM.TEMP;
COLLECT STATS  COLUMN(VALID_CNTCT_POINT_IND) ON  MDM.TEMP;
COLLECT STATS  COLUMN(REGIS_PRSNA_ID,VALID_CNTCT_POINT_IND) ON  MDM.TEMP;
COLLECT STATS  ON  MDM.TEMP;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  
 
.LABEL L15
 
 UPDATE  REGIS_PRSNA_POSTL_ADDR
FROM MDM.TEMP AS temp
SET VALID_CNTCT_POINT_IND = temp.VALID_CNTCT_POINT_IND
WHERE REGIS_PRSNA_POSTL_ADDR.REGIS_PRSNA_ID=temp.REGIS_PRSNA_ID 
AND REGIS_PRSNA_POSTL_ADDR.MKTNG_PGM_NBR=temp.MKTNG_PGM_NBR
AND REGIS_PRSNA_POSTL_ADDR.CNTCT_POINT_CATEG_CODE=temp.CNTCT_POINT_CATEG_CODE;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 

.LABEL L16
UPDATE  ETL_CTRL.SOURCE_CONTROL
FROM MDM.DATA_SRCE A
SET DATA_SOURCE =A.DATA_SRCE_NAME,
DATA_SOURCE_DESC =A.DATA_SOURCE_DESC,
DATA_SOURCE_TYPE =A.DATA_SOURCE_TYPE,
SRC_BUS_NM =A.SRC_BUS_NM,
PII_DATA_IND =A.PII_DATA_IND
WHERE 
A.DATA_SRCE_NBR = ETL_CTRL.SOURCE_CONTROL.SOURCE_ID
AND A.SYS_LAST_MODIFIED_DATE IS NOT NULL;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 

.LABEL L17
UPDATE  ETL_CTRL.SOURCE_CONTROL 
FROM (
SELECT DATA_SRCE_NBR , WEB_SITE_URL_TXT ,CNTRY_CODE
FROM MDM.WEB_SITE 
QUALIFY RANK() OVER (PARTITION BY DATA_SRCE_NBR ORDER BY SYS_LAST_MODIFIED_DATE DESC,WEB_SITE_NBR DESC)=1
WHERE SYS_LAST_MODIFIED_DATE IS NOT NULL
) W
SET DATA_COLL = W.WEB_SITE_URL_TXT,
COUNTRY = W.CNTRY_CODE
WHERE W.DATA_SRCE_NBR = ETL_CTRL.SOURCE_CONTROL.SOURCE_ID ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
