REPLACE PROCEDURE MDM.RTN_DEL(IN RTN_RULE_ID INTEGER,IN DEL_COL VARCHAR(300),IN DEL_TBL VARCHAR(300),IN LOAD_ID INTEGER)
BEGIN
DECLARE V_RTN_RULE_ID INTEGER;
DECLARE V_DEL_COL VARCHAR(300);
DECLARE V_DEL_TBL VARCHAR(300);
DECLARE V_SQL VARCHAR(10000);
DECLARE V_DEBUG_MESSAGE VARCHAR(255);
DECLARE V_LOAD_ID INTEGER;
DECLARE V_TBL_NAME VARCHAR(300);
DECLARE V_TEMPORAL_FLAG VARCHAR(1);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
SET V_DEBUG_MESSAGE=SQLSTATE||' '||CAST( CURRENT_TIMESTAMP(1) AS CHAR(21));
UPDATE MDM.RTN_DELETE_LOAD_LOG
SET SYS_LAST_MODIFIED_DATE=CURRENT_TIMESTAMP(0),
STATUS='Failure',
SYS_ERR_CODE=V_SQL
WHERE MDM.RTN_DELETE_LOAD_LOG.RTN_RULE_ID=V_RTN_RULE_ID
AND MDM.RTN_DELETE_LOAD_LOG.TABL_NAME=V_TBL_NAME
AND CAST(MDM.RTN_DELETE_LOAD_LOG.SYS_SOURCE AS INTEGER)=V_LOAD_ID;
RESIGNAL SET MESSAGE_TEXT = V_DEBUG_MESSAGE;
END;

SET V_RTN_RULE_ID=RTN_RULE_ID;
SET V_DEL_COL=DEL_COL;
SET V_DEL_TBL=DEL_TBL;
SET V_LOAD_ID=LOAD_ID;

FOR
 TABLE_LST AS C1 CURSOR FOR
	SELECT TBL_NAME 
	FROM MDM.RTN_DELETE_REF
	WHERE RTN_RULE_ID=V_RTN_RULE_ID
	AND DEL_COL=V_DEL_COL
	ORDER BY SEQ_NBR DESC
DO


SET V_TBL_NAME=TABLE_LST.TBL_NAME;

INSERT INTO MDM.RTN_DELETE_LOAD_LOG
(RTN_RULE_ID,
TABL_NAME,
STATUS,
SYS_SOURCE,
SYS_CREATION_DATE)
SELECT
V_RTN_RULE_ID,
V_TBL_NAME,
'In Progress',
V_LOAD_ID,
CURRENT_TIMESTAMP(0);

SEL TEMPORALPROPERTY INTO :V_TEMPORAL_FLAG FROM DBC.TABLES WHERE DATABASENAME='ICRM_TBL' AND TABLENAME=V_TBL_NAME;

IF V_TEMPORAL_FLAG='T' THEN

SET V_SQL='NONTEMPORAL DELETE FROM '||V_TBL_NAME||' WHERE ('||V_DEL_COL||
	') IN (SELECT '||V_DEL_COL||' FROM '||V_DEL_TBL||');';
	
ELSE 	

SET V_SQL='DELETE FROM '||V_TBL_NAME||' WHERE ('||V_DEL_COL||
	') IN (SELECT '||V_DEL_COL||' FROM '||V_DEL_TBL||');';
	
END IF;	

CALL DBC.SYSEXECSQL(V_SQL);   

UPDATE MDM.RTN_DELETE_LOAD_LOG
SET SYS_LAST_MODIFIED_DATE=CURRENT_TIMESTAMP(0),
STATUS='Completed'
WHERE MDM.RTN_DELETE_LOAD_LOG.RTN_RULE_ID=V_RTN_RULE_ID
AND MDM.RTN_DELETE_LOAD_LOG.TABL_NAME=V_TBL_NAME
AND CAST(MDM.RTN_DELETE_LOAD_LOG.SYS_SOURCE AS INTEGER)=V_LOAD_ID;

END FOR;
END;

REPLACE PROCEDURE MDM.RTN_SEL(IN RTN_RULE_ID INTEGER,IN GROUP_ID VARCHAR(100),IN LOAD_ID INTEGER)
BEGIN
DECLARE V_RTN_RULE_ID INTEGER;
DECLARE V_SQL VARCHAR(10000);
DECLARE V_DEBUG_MESSAGE VARCHAR(255);
DECLARE V_GROUP_ID VARCHAR(100);
DECLARE V_LOAD_ID INTEGER;
DECLARE V_TBL_NAME VARCHAR(300);
DECLARE V_TBL_EXISTS VARCHAR(1);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
SET V_DEBUG_MESSAGE=SQLSTATE||' '||CAST( CURRENT_TIMESTAMP(1) AS CHAR(21));
UPDATE MDM.RTN_SELECT_LOAD_LOG
SET SYS_LAST_MODIFIED_DATE=CURRENT_TIMESTAMP(0),
STATUS='Failure',
SYS_ERR_CODE=V_SQL,
SYS_ERR_SVRTY=V_DEBUG_MESSAGE
WHERE MDM.RTN_SELECT_LOAD_LOG.RTN_RULE_ID=V_RTN_RULE_ID
AND MDM.RTN_SELECT_LOAD_LOG.TABL_NAME=V_TBL_NAME
AND CAST(MDM.RTN_SELECT_LOAD_LOG.SYS_SOURCE AS INTEGER)=V_LOAD_ID;
RESIGNAL SET MESSAGE_TEXT = V_DEBUG_MESSAGE;
END;
DECLARE CONTINUE  HANDLER FOR SQLSTATE '42000'      --SQLSTATE code for table doesnot exist
BEGIN      
SET v_debug_message ='Drop table error suppressed';
END; 
	
SET V_RTN_RULE_ID=RTN_RULE_ID;
SET V_GROUP_ID=GROUP_ID;
SET V_LOAD_ID=LOAD_ID;

DROP TABLE MDM.RTN_CNSMR_CHCE_DATETM;

 CREATE MULTISET TABLE MDM.RTN_CNSMR_CHCE_DATETM ,NO FALLBACK ,
      NO BEFORE JOURNAL,
      NO AFTER JOURNAL,
      CHECKSUM = DEFAULT,
      DEFAULT MERGEBLOCKRATIO
      (
       MKTNG_PGM_NBR INTEGER NOT NULL,
       REGIS_PRSNA_ID INTEGER NOT NULL,
       CNSMR_CHCE_DATETM TIMESTAMP(6) COMPRESS)
 PRIMARY INDEX ( MKTNG_PGM_NBR,REGIS_PRSNA_ID  )
 PARTITION BY MKTNG_PGM_NBR;

FOR
 TABLE_LST AS C1 CURSOR FOR
	SELECT TBL_NAME 
	FROM MDM.RTN_SELECT_REF
	WHERE RTN_RULE_ID=V_RTN_RULE_ID
	ORDER BY SEQ_NBR DESC
DO


SET V_TBL_NAME=TABLE_LST.TBL_NAME;

INSERT INTO MDM.RTN_SELECT_LOAD_LOG
(RTN_RULE_ID,
TABL_NAME,
STATUS,
SYS_SOURCE,
SYS_CREATION_DATE)
SELECT
V_RTN_RULE_ID,
V_TBL_NAME,
'In Progress',
V_LOAD_ID,
CURRENT_TIMESTAMP(0);

SET V_SQL='INSERT INTO MDM.RTN_CNSMR_CHCE_DATETM
SEL A.MKTNG_PGM_NBR,A.REGIS_PRSNA_ID,A.CNSMR_CHCE_DATETM FROM MDM.'||V_TBL_NAME||' A   
INNER JOIN MDM.RTN_RULES_DTL B
ON A.MKTNG_PGM_NBR=B.MKTNG_PGM_NBR
AND B.RTN_RULE_ID='||V_RTN_RULE_ID||'
AND B.GROUP_ID IN ('||V_GROUP_ID ||')
AND B.MKTNG_PGM_NBR IN (SEL MKTNG_PGM_NBR FROM MKTNG_PGM_LIST)
AND COALESCE(B.SYS_ENT_STATE,'||''''||''''||') = '||''''||'ACTIVE'||''''||'
INNER JOIN MDM.RTN_RULES C
ON B.RTN_RULE_ID=C.RTN_RULE_ID
AND COALESCE(C.SYS_ENT_STATE,'||''''||''''||') = '||''''||'ACTIVE'||''''||';';

CALL DBC.SYSEXECSQL(V_SQL);   

UPDATE MDM.RTN_SELECT_LOAD_LOG
SET SYS_LAST_MODIFIED_DATE=CURRENT_TIMESTAMP(0),
STATUS='Completed'
WHERE MDM.RTN_SELECT_LOAD_LOG.RTN_RULE_ID=V_RTN_RULE_ID
AND MDM.RTN_SELECT_LOAD_LOG.TABL_NAME=V_TBL_NAME
AND CAST(MDM.RTN_SELECT_LOAD_LOG.SYS_SOURCE AS INTEGER)=V_LOAD_ID;

END FOR;

COLLECT STATS ON MDM.RTN_CNSMR_CHCE_DATETM
COLUMN MKTNG_PGM_NBR;

COLLECT STATS ON MDM.RTN_CNSMR_CHCE_DATETM
COLUMN REGIS_PRSNA_ID;

END;