.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
DROP TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_MDM_561;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L2
DROP TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_MDM_561;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L3
DROP TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_HIERARCHY_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L4
DROP TABLE DEPLOY_WORK.ATTRIBUTE_TYPES_RELN_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L5
DROP TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_HIERARCHY_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L6
DROP TABLE DEPLOY_WORK.ATTRIBUTE_VALUES_RELN_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L7
DROP TABLE DEPLOY_WORK.RPT_ADDR_QLTY_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L8
DROP TABLE DEPLOY_WORK.RPT_CNSMR_NBR_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L9
DROP TABLE DEPLOY_WORK.RPT_DATA_NBR_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L10
DROP TABLE DEPLOY_WORK.RPT_LOAD_NBR_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L11
DROP TABLE DEPLOY_WORK.TRILLIUM_OUTPUT_DUP_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L12
DROP TABLE DEPLOY_WORK.tss_cntry_table_map_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L13
DROP TABLE DEPLOY_WORK.ENV_NM_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L14
DROP TABLE DEPLOY_WORK.upld_tmplt_prps_MDM_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L15
DROP TABLE DEPLOY_WORK.ERR_PRSNA_STG_561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L16
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_DUP1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L17
DROP TABLE DEPLOY_WORK.ID_SQR_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L18
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_SOC_NET_ACCT_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L19
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_POSTL_ADDR_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L20
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_EMAIL_ADDR_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L21
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_PHONE_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L22
DROP TABLE DEPLOY_WORK.PET_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L23
DROP TABLE DEPLOY_WORK.PET_TRT_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L24
DROP TABLE DEPLOY_WORK.DPEND_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L25
DROP TABLE DEPLOY_WORK.DPEND_TRT_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L26
DROP TABLE DEPLOY_WORK.PRSNA_TRT_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L27
DROP TABLE DEPLOY_WORK.CNSMR_AFFLTN_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L28
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L29
DROP TABLE DEPLOY_WORK.ERR_PRSNA_STG_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L30
DROP TABLE DEPLOY_WORK.TRILLIUM_MDM_REFERENCE_RG_R561;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;





