.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
DROP TABLE LD_INCTV;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L2
DROP TABLE LD_DATA_SRCE_MKTNG_PGM;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 .LABEL L3
CREATE MULTISET TABLE MDM.LD_INCTV ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      INCTV_NBR INTEGER,
      MKTNG_PGM_NBR INTEGER,
      INCTV_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      INCTV_DESC VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
      INCTV_VAL_AMT DECIMAL(9,2),
      INCTV_VAL_PCT DECIMAL(9,4),
      INCTV_START_DATE DATE FORMAT 'YY/MM/DD',
      INCTV_END_DATE DATE FORMAT 'YY/MM/DD',
      INCTV_EXPRN_DATETM TIMESTAMP(0),
      INCTV_EXPRN_DAY_CNT INTEGER,
      INCTV_CRTN_DATE DATE FORMAT 'YY/MM/DD',
      INCTV_STATUS_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      INCTV_TYPE_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      BRAND_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      COUPN_TYPE_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      ALT_SYS_INCTV_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      BUNDLE_PACK_IND CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      PREMARKET_OFFER_IND CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      EXT_INCTV_CD VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      COUPN_EXT_CD VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      INCTV_UOM_CD VARCHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC,
      TGT_DST_QTY INTEGER,
      CLRNG_HS_CD VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      EXTRN_COUPN_DATA_SRCE_NBR INTEGER,
      COUPN_UNIQUE_IND CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_TARGET_ID INTEGER,
      SYS_AUTH_ID VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_SOURCE VARCHAR(256) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATION_DATE TIMESTAMP(0),
      SYS_ENT_STATE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
      SYS_NC_TYPE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_CODE VARCHAR(10000) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LOAD_ID VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_WORKFLOW_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( INCTV_NBR );

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


 .LABEL L4

CREATE MULTISET TABLE MDM.LD_DATA_SRCE_MKTNG_PGM ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      DATA_SRCE_NBR INTEGER,
      MKTNG_PGM_NBR INTEGER,
      LOG_SOURCE_ID DECIMAL(18,0),
      LOG_UPDATE_USER VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOG_LOAD_ID VARCHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC,
      PREF_SRC_IND CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_TARGET_ID INTEGER,
      SYS_AUTH_ID VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_SOURCE VARCHAR(256) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATION_DATE TIMESTAMP(0),
      SYS_ENT_STATE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
      SYS_NC_TYPE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_CODE VARCHAR(10000) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LOAD_ID VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_WORKFLOW_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( DATA_SRCE_NBR );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 