.logon $TDPID/$TDUSER,$TDPWD

.SET ERRORLEVEL (3807) SEVERITY 0;
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
REPLACE VIEW MDM.CNSMR_ACTN AS LOCKING ROW FOR ACCESS SELECT * FROM ICRM_TBL.CNSMR_ACTN;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L2
REPLACE VIEW MDM.CNSMR_ACTN_SUB_TYPE AS SEL * FROM  icrm_tbl.CNSMR_ACTN_SUB_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L3
REPLACE VIEW MDM.CNSMR_AFFLTN (
REGIS_PRSNA_ID
,CNSMR_GRP_NBR
,MKTNG_PGM_NBR
,AFFLTN_START_DATE
,AFFLTN_END_DATE
,LEGAL_ENT_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
REGIS_PRSNA_ID
,CNSMR_GRP_NBR
,MKTNG_PGM_NBR
,AFFLTN_START_DATE
,AFFLTN_END_DATE
,LEGAL_ENT_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.CNSMR_AFFLTN;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L4
REPLACE VIEW MDM.CNSMR_GRP (
CNSMR_GRP_NBR
,CNSMR_GRP_NAME
,CNSMR_GRP_DESC
,CNSMR_GRP_TYPE_CODE
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
CNSMR_GRP_NBR
,CNSMR_GRP_NAME
,CNSMR_GRP_DESC
,CNSMR_GRP_TYPE_CODE
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.CNSMR_GRP;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L5
REPLACE VIEW MDM.CNSMR_GRP_TYPE (
CNSMR_GRP_TYPE_CODE
,CNSMR_GRP_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
CNSMR_GRP_TYPE_CODE
,CNSMR_GRP_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.CNSMR_GRP_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L6
REPLACE VIEW MDM.cnsmr_intel_proc (
PROC_ID
,PROC_NAME
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS  SELECT
PROC_ID
,PROC_NAME
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.cnsmr_intel_proc;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L7
REPLACE VIEW MDM.CNSMR_INTEL_TRUSTED_REF  (
LEGAL_ENT_NBR,
PROC_ID,
MKTNG_PGM_NBR,
TRT_NBR,
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY) AS LOCKING ROW FOR ACCESS  SELECT
LEGAL_ENT_NBR,
PROC_ID,
MKTNG_PGM_NBR,
TRT_NBR,
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
FROM iCRM_TBL.CNSMR_INTEL_TRUSTED_REF;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L8
REPLACE VIEW MDM.CNSMR_INTEL_TRUSTED_REF_VAL
(
LEGAL_ENT_NBR,
MKTNG_PGM_NBR,
ATTR_NAME,
ATTR_VAL,
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY 
) AS LOCKING ROW FOR ACCESS 
SELECT
LEGAL_ENT_NBR,
MKTNG_PGM_NBR,
ATTR_NAME,
ATTR_VAL,
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY 
FROM
ICRM_TBL.CNSMR_INTEL_TRUSTED_REF_VAL;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L9
REPLACE VIEW MDM.CNSMR_SCORE_REF (
CNSMR_SCORE_NBR,
CNSMR_SCORE_NAME,
CNSMR_SCORE_DESC,
IS_ACTIVE, 
HIST_RETEN_DAYS,  
SCORE_RUN_FREQ_CODE,
WKLY_RTN_IND,
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
CNSMR_SCORE_NBR,
CNSMR_SCORE_NAME,
CNSMR_SCORE_DESC,
IS_ACTIVE,
HIST_RETEN_DAYS,
SCORE_RUN_FREQ_CODE,
WKLY_RTN_IND,
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
FROM
iCRM_TBL.CNSMR_SCORE_REF;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L11
REPLACE VIEW MDM.CNTCT_OPT_PGM (
CNTCT_OPT_NBR
,MKTNG_PGM_NBR
,OPTED_MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
CNTCT_OPT_NBR
,MKTNG_PGM_NBR
,OPTED_MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.CNTCT_OPT_PGM;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L12
REPLACE VIEW MDM.CNTNT_ELEM
AS LOCKING ROW FOR ACCESS  SEQUENCED  TRANSACTIONTIME
SELECT * FROM iCRM_TBL.CNTNT_ELEM;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L12A
REPLACE VIEW MDM.CNTNT_ELEM_ITEM
AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME 
SELECT * FROM iCRM_TBL.CNTNT_ELEM_ITEM;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L12B
REPLACE VIEW MDM.CNTNT_ELEM_TRT
AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME 
SELECT * FROM iCRM_TBL.CNTNT_ELEM_TRT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L13
REPLACE VIEW MDM.CNTNT_ELEM_TYPE
AS LOCKING ROW FOR ACCESS SEL * FROM  icrm_tbl.cntnt_elem_type;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L14
REPLACE VIEW MDM.CNTRY
AS SEL * FROM  icrm_tbl.CNTRY;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L15
REPLACE VIEW MDM.COCRM_REF_DATA_CONFIG
AS LOCKING ROW FOR ACCESS 
SELECT *  FROM  iCRM_TBL.COCRM_REF_DATA_CONFIG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L16
REPLACE VIEW MDM.COUPN_TYPE
AS SEL * FROM  icrm_tbl.COUPN_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L17
REPLACE VIEW MDM.data_srce AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.data_srce;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L18
REPLACE VIEW MDM.DATA_SRCE_MKTNG_PGM AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.DATA_SRCE_MKTNG_PGM;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L19
REPLACE VIEW MDM.DPEND (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,DPEND_SEQ_NBR
,LEGAL_ENT_NBR
,DPEND_TYPE_CODE
,DPEND_NAME
,DPEND_GENDR_IND
,DPEND_BRTH_DATE
,DPEND_AGE_NBR
,DECEASED_IND
,OPTED_DPEND_IND
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,DPEND_SEQ_NBR
,LEGAL_ENT_NBR
,DPEND_TYPE_CODE
,DPEND_NAME
,DPEND_GENDR_IND
,DPEND_BRTH_DATE
,DPEND_AGE_NBR
,DECEASED_IND
,OPTED_DPEND_IND
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.DPEND;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L20
REPLACE VIEW MDM.DPEND_TRT (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,DPEND_SEQ_NBR
,DPEND_TRT_SEQ_NBR
,TRT_NBR
,DPEND_TRT_DATE
,DPEND_TRT_TXT
,LEGAL_ENT_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,DPEND_SEQ_NBR
,DPEND_TRT_SEQ_NBR
,TRT_NBR
,DPEND_TRT_DATE
,DPEND_TRT_TXT
,LEGAL_ENT_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.DPEND_TRT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L21
REPLACE VIEW MDM.DPEND_TYPE (
DPEND_TYPE_CODE
,DPEND_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
DPEND_TYPE_CODE
,DPEND_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.DPEND_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L22
REPLACE VIEW MDM.EMAIL_FORMT (
EMAIL_FORMT_CODE
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,EMAIL_FORMT_NAME
) AS LOCKING ROW FOR ACCESS SELECT
EMAIL_FORMT_CODE
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,EMAIL_FORMT_NAME
FROM iCRM_TBL.EMAIL_FORMT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L23
REPLACE VIEW MDM.ERR_CODE_DETAILS
AS
LOCKING ROW FOR ACCESS
SELECT LOAD_ID,
MKTNG_PGM_NBR,
SYS_ERR_CODE AS ERR_DESC,
COUNT(DISTINCT REGIS_CNSMR_ID_VAL) ERROR_CODE_NBR
FROM MDM.ERR_PRSNA_STG
GROUP BY 1,2,3;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L24
REPLACE VIEW MDM.GEOC_AREA_TYPE (
GEOC_AREA_TYPE_CODE
,GEOC_AREA_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
GEOC_AREA_TYPE_CODE
,GEOC_AREA_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.GEOC_AREA_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L25
REPLACE VIEW MDM.GEOC_REGN
AS SEL * FROM  icrm_tbl.GEOC_REGN;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L26
REPLACE VIEW MDM.GEOC_SUB_REGN
AS SEL * FROM  icrm_tbl.GEOC_SUB_REGN;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L27
REPLACE VIEW MDM.HSHLD_PRSNA (
HSHLD_PRSNA_ID
,LEGAL_ENT_NBR
,PRSNA_STATUS_CODE
,UNIVERSAL_OPT_OUT
,FAMLY_NAME
,NOTE_TXT
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
HSHLD_PRSNA_ID
,LEGAL_ENT_NBR
,PRSNA_STATUS_CODE
,UNIVERSAL_OPT_OUT
,FAMLY_NAME
,NOTE_TXT
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.HSHLD_PRSNA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L28
REPLACE VIEW MDM.INCTV (
INCTV_NBR
,MKTNG_PGM_NBR
,INCTV_NAME
,INCTV_DESC
,INCTV_VAL_AMT
,INCTV_VAL_PCT
,INCTV_START_DATE
,INCTV_END_DATE
,INCTV_EXPRN_DATETM
,INCTV_EXPRN_DAY_CNT
,INCTV_CRTN_DATE
,INCTV_STATUS_CODE
,INCTV_TYPE_CODE
,BRAND_NAME
,ALT_SYS_INCTV_ID
,COUPN_TYPE_CODE
,EXTRN_COUPN_DATA_SRCE_NBR
,COUPN_UNIQUE_IND
,BUNDLE_PACK_IND
,PREMARKET_OFFER_IND
,EXT_INCTV_CD
,COUPN_EXT_CD
,INCTV_UOM_CD
,TGT_DST_QTY
,CLRNG_HS_CD
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
INCTV_NBR
,MKTNG_PGM_NBR
,INCTV_NAME
,INCTV_DESC
,INCTV_VAL_AMT
,INCTV_VAL_PCT
,INCTV_START_DATE
,INCTV_END_DATE
,INCTV_EXPRN_DATETM
,INCTV_EXPRN_DAY_CNT
,INCTV_CRTN_DATE
,INCTV_STATUS_CODE
,INCTV_TYPE_CODE
,BRAND_NAME
,ALT_SYS_INCTV_ID
,COUPN_TYPE_CODE
,EXTRN_COUPN_DATA_SRCE_NBR
,COUPN_UNIQUE_IND
,BUNDLE_PACK_IND
,PREMARKET_OFFER_IND
,EXT_INCTV_CD
,COUPN_EXT_CD
,INCTV_UOM_CD
,TGT_DST_QTY
,CLRNG_HS_CD
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.INCTV;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L29
REPLACE VIEW MDM.INCTV_ITEM (
INCTV_NBR
,INCTV_ITEM_NBR
,INCTV_ITEM_NAME
,INCTV_ITEM_QTY
,INCTV_ITEM_DESC
,CATEG_CODE
,SEG_CODE
,BRAND_CODE
,SUB_BRAND_CODE
,ITEM_VERS_CODE
,GLOBAL_FORM_CODE
,PROD_ITEM_UPC
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
INCTV_NBR
,INCTV_ITEM_NBR
,INCTV_ITEM_NAME
,INCTV_ITEM_QTY
,INCTV_ITEM_DESC
,CATEG_CODE
,SEG_CODE
,BRAND_CODE
,SUB_BRAND_CODE
,ITEM_VERS_CODE
,GLOBAL_FORM_CODE
,PROD_ITEM_UPC
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.INCTV_ITEM;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L30
REPLACE VIEW MDM.LANG (
LANG_CODE
,LANG_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
LANG_CODE
,LANG_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.LANG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L31
REPLACE VIEW MDM.LEGAL_ENT (
LEGAL_ENT_NBR
,LEGAL_ENT_NAME
,LEGAL_ENT_SHORT_NAME
,LEGAL_ENT_DESC
,GEOC_REGN_CODE 
,GEOC_SUB_REGN_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME  SELECT
LEGAL_ENT_NBR
,LEGAL_ENT_NAME
,LEGAL_ENT_SHORT_NAME
,LEGAL_ENT_DESC
,GEOC_REGN_CODE 
,GEOC_SUB_REGN_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.LEGAL_ENT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L32
REPLACE VIEW MDM.LEGAL_ENT_TRAIT_MAP (
LEGAL_ENT_NBR,
TRT_NBR,
TRT_NAME,
TRT_DESC,
PREDFND_TRT_VAL_NBR,
PREDFND_TRT_DESC,
TRT_ENT_TYPE_CODE,        
TRT_TBL,
TRT_COL,
ATTR_TBL,
ATTR_COL,
LANG_CODE,
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
LEGAL_ENT_NBR,
TRT_NBR,
TRT_NAME,
TRT_DESC,
PREDFND_TRT_VAL_NBR,
PREDFND_TRT_DESC,
TRT_ENT_TYPE_CODE,        
TRT_TBL,
TRT_COL,
ATTR_TBL,
ATTR_COL,
LANG_CODE,
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
FROM
iCRM_TBL.LEGAL_ENT_TRAIT_MAP;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L33
REPLACE VIEW MDM.LOAD_INFO(                                                    
LOAD_ID                                                                       
,PROCESS_NAME                                                                  
,PROCESS_START_TIME                                                            
,PROCESS_END_TIME                                                              
,ERROR_MSG_TXT                                                                 
,STATUS                                                                        
,BATCH_ID                                                                      
,NC_TYPE         
,CNTRY_NAME
,SYS_TARGET_ID                                                                 
,SYS_AUTH_ID                                                                   
,SYS_SOURCE                                                                    
,SYS_CREATED_BY                                                                
,SYS_CREATION_DATE                                                             
,SYS_ENT_STATE                                                                 
,SYS_LAST_MODIFIED_BY                                                          
,SYS_LAST_MODIFIED_DATE                                                        
,SYS_NC_TYPE                                                                   
,SYS_ERR_CODE                                                                  
,SYS_ERR_SVRTY                                                                 
) AS LOCKING ROW FOR ACCESS SELECT                                              
LOAD_ID                                                                       
,PROCESS_NAME                                                                  
,PROCESS_START_TIME                                                            
,PROCESS_END_TIME                                                              
,ERROR_MSG_TXT                                                                 
,STATUS                                                                        
,BATCH_ID                                                                      
,NC_TYPE             
,CNTRY_NAME
,SYS_TARGET_ID                                                                 
,SYS_AUTH_ID                                                                   
,SYS_SOURCE                                                                    
,SYS_CREATED_BY                                                                
,SYS_CREATION_DATE                                                             
,SYS_ENT_STATE                                                                 
,SYS_LAST_MODIFIED_BY                                                          
,SYS_LAST_MODIFIED_DATE                                                        
,SYS_NC_TYPE                                                                   
,SYS_ERR_CODE                                                                  
,SYS_ERR_SVRTY                                                                 
FROM MDM.LOAD_INFO2;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L34
REPLACE VIEW MDM.MATCHD_CNSMR_EMAIL_ADDR (
MATCHD_CNSMR_PRSNA_ID
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,VALID_CNTCT_POINT_IND
,PREF_CNTCT_POINT_IND
,EMAIL_ADDR_TXT
,EMAIL_FORMT_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
MATCHD_CNSMR_PRSNA_ID
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,VALID_CNTCT_POINT_IND
,PREF_CNTCT_POINT_IND
,EMAIL_ADDR_TXT
,EMAIL_FORMT_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.MATCHD_CNSMR_EMAIL_ADDR;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L35
REPLACE VIEW MDM.MATCHD_CNSMR_PHONE (
MATCHD_CNSMR_PRSNA_ID
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,VALID_CNTCT_POINT_IND
,PREF_CNTCT_POINT_IND
,PHONE_CNTRY_NBR
,PHONE_AREA_NBR
,PHONE_EXCHG_NBR
,PHONE_LINE_NBR
,PHONE_EXTSN_NUM
,FULL_PHONE_NUM
,SMS_PREFR_IND
,SMS_AVAIL_START_TIME
,SMS_AVAIL_END_TIME
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
MATCHD_CNSMR_PRSNA_ID
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,VALID_CNTCT_POINT_IND
,PREF_CNTCT_POINT_IND
,PHONE_CNTRY_NBR
,PHONE_AREA_NBR
,PHONE_EXCHG_NBR
,PHONE_LINE_NBR
,PHONE_EXTSN_NUM
,FULL_PHONE_NUM
,SMS_PREFR_IND
,SMS_AVAIL_START_TIME
,SMS_AVAIL_END_TIME
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.MATCHD_CNSMR_PHONE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L36
REPLACE VIEW MDM.MATCHD_CNSMR_POSTL_ADDR (
 MATCHD_CNSMR_PRSNA_ID
 ,LEGAL_ENT_NBR
 ,CNTCT_POINT_CATEG_CODE
 ,VALID_CNTCT_POINT_IND
 ,PREF_CNTCT_POINT_IND
 ,ADDR_LINE_1_TXT
 ,ADDR_LINE_2_TXT
 ,ADDR_LINE_3_TXT
 ,STRET_NUM
 ,STRET_NAME
 ,APT_NUM
 ,PO_BOX_NUM
 ,CITY_NAME
 ,CITY_CODE
 ,POSTL_AREA_CODE
 ,LAT_MEAS
 ,LONG_MEAS
 ,TERR_NAME
 ,TERR_CODE
 ,CNTRY_CODE
,POSTL_ADDR_ID
 ,SYS_SOURCE
 ,SYS_TARGET_ID
 ,SYS_AUTH_ID
 ,SYS_CREATED_BY
 ,SYS_CREATION_DATE
 ,SYS_LAST_MODIFIED_DATE
 ,SYS_ENT_STATE
 ,SYS_LAST_MODIFIED_BY
 ,SYS_NC_TYPE
 ,SYS_ERR_CODE
 ,SYS_ERR_SVRTY
 ) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
 MATCHD_CNSMR_PRSNA_ID
 ,LEGAL_ENT_NBR
 ,CNTCT_POINT_CATEG_CODE
 ,VALID_CNTCT_POINT_IND
 ,PREF_CNTCT_POINT_IND
 ,ADDR_LINE_1_TXT
 ,ADDR_LINE_2_TXT
 ,ADDR_LINE_3_TXT
 ,STRET_NUM
 ,STRET_NAME
 ,APT_NUM
 ,PO_BOX_NUM
 ,CITY_NAME
 ,CITY_CODE
 ,POSTL_AREA_CODE
 ,LAT_MEAS
 ,LONG_MEAS
 ,TERR_NAME
 ,TERR_CODE
 ,CNTRY_CODE
,POSTL_ADDR_ID
 ,SYS_SOURCE
 ,SYS_TARGET_ID
 ,SYS_AUTH_ID
 ,SYS_CREATED_BY
 ,SYS_CREATION_DATE
 ,SYS_LAST_MODIFIED_DATE
 ,SYS_ENT_STATE
 ,SYS_LAST_MODIFIED_BY
 ,SYS_NC_TYPE
 ,SYS_ERR_CODE
 ,SYS_ERR_SVRTY
FROM iCRM_TBL.MATCHD_CNSMR_POSTL_ADDR;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L37
REPLACE VIEW MDM.MATCHD_CNSMR_PRSNA (
MATCHD_CNSMR_PRSNA_ID
,LEGAL_ENT_NBR
,HSHLD_PRSNA_ID
,HEAD_OF_HSHLD_IND
,UNIVERSAL_OPT_OUT
,NAME_PREFX_TXT
,GVN_NAME
,MID_NAME
,FAMLY_NAME
,NAME_SUFFX_TXT
,FULL_NAME
,GENDR_IND
,BRTH_DATE
,NOTE_TXT
,LATST_ACTVY_DATE
,PRSNA_STATUS_CODE
,CNSMR_USER_NAME
,LANG_CODE
,REGIS_DATE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
MATCHD_CNSMR_PRSNA_ID
,LEGAL_ENT_NBR
,HSHLD_PRSNA_ID
,HEAD_OF_HSHLD_IND
,UNIVERSAL_OPT_OUT
,NAME_PREFX_TXT
,GVN_NAME
,MID_NAME
,FAMLY_NAME
,NAME_SUFFX_TXT
,FULL_NAME
,GENDR_IND
,BRTH_DATE
,NOTE_TXT
,LATST_ACTVY_DATE
,PRSNA_STATUS_CODE
,CNSMR_USER_NAME
,LANG_CODE
,REGIS_DATETM
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.MATCHD_CNSMR_PRSNA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L38
REPLACE VIEW MDM.MATCHD_CNSMR_SOC_NETK_ACT AS SELECT * FROM icrm_tbl.MATCHD_CNSMR_SOC_NET_ACCT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L39
REPLACE VIEW MDM.MATCHD_CNSMR_TRT_REF
AS SEL * FROM  icrm_tbl.MATCHD_CNSMR_TRT_REF;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L40
REPLACE VIEW MDM.MATCHD_CNSMR_WF_USAGE_LOG AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.MATCHD_CNSMR_WF_USAGE_LOG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L41
REPLACE VIEW MDM.MKTNG_PGM (
MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,MKTNG_PGM_NAME
,MKTNG_PGM_SHORT_NAME
,MKTNG_PGM_DESC
,MKTNG_PGM_STATUS
,MKTNG_PGM_BUSN_NAME
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,MKTNG_PGM_NAME
,MKTNG_PGM_SHORT_NAME
,MKTNG_PGM_DESC
,MKTNG_PGM_STATUS
,MKTNG_PGM_BUSN_NAME
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.MKTNG_PGM;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L42
REPLACE VIEW MDM.MKTNG_PGM_CNTRY_BRAND (
MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,CNTRY_CODE
,BRAND_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,CNTRY_CODE
,BRAND_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.MKTNG_PGM_CNTRY_BRAND;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L43
REPLACE VIEW MDM.MKTNG_PGM_TRAIT_MAP (
MKTNG_PGM_NBR
,TRT_NBR
,TRT_NAME
,TRT_DESC
,PREDFND_TRT_VAL_NBR
,PREDFND_TRT_DESC
,TRT_ENT_TYPE_CODE
,LANG_CODE
,TRT_TBL
,TRT_COL
,ATTR_TBL
,ATTR_COL
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
MKTNG_PGM_NBR
,TRT_NBR
,TRT_NAME
,TRT_DESC
,PREDFND_TRT_VAL_NBR
,PREDFND_TRT_DESC
,TRT_ENT_TYPE_CODE
,LANG_CODE
,TRT_TBL
,TRT_COL
,ATTR_TBL
,ATTR_COL
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.MKTNG_PGM_TRAIT_MAP;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L44
REPLACE VIEW MDM.MTCHD_CNSMR_SCR_DMN_MAP (
CNSMR_SCORE_NBR, 
LEGAL_ENT_NBR,         
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
CNSMR_SCORE_NBR,
LEGAL_ENT_NBR,         
SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
FROM
iCRM_TBL.MTCHD_CNSMR_SCR_DMN_MAP;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L45
REPLACE VIEW MDM.OPT_OUT_NOT_FOUND AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.OPT_OUT_NOT_FOUND;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L46
REPLACE VIEW MDM.OPT_OUT_NOT_FOUND_XREF AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.OPT_OUT_NOT_FOUND_XREF;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L47
REPLACE VIEW MDM.PC_ENRICHDATA_CONFIG AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.PC_ENRICHDATA_CONFIG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L48
REPLACE VIEW MDM.PC_SOURCE_CONFIG AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.PC_SOURCE_CONFIG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L49
REPLACE VIEW MDM.PET (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,PET_SEQ_NBR
,LEGAL_ENT_NBR
,PET_NAME
,PET_GENDR_IND
,PET_BRTH_DATE
,PET_AGE_NBR
,DECEASED_IND
,PET_TYPE_CODE
,PET_BREED_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS 
SELECT
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,PET_SEQ_NBR
,LEGAL_ENT_NBR
,PET_NAME
,PET_GENDR_IND
,PET_BRTH_DATE
,PET_AGE_NBR
,DECEASED_IND
,PET_TYPE_CODE
,PET_BREED_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.PET;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L50
REPLACE VIEW MDM.PET_BREED (
PET_BREED_CODE
,PET_BREED_NAME
,PET_TYPE_CODE
,BREED_SIZE_CODE
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
PET_BREED_CODE
,PET_BREED_NAME
,PET_TYPE_CODE
,BREED_SIZE_CODE
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM ICRM_TBL.PET_BREED;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L51
REPLACE VIEW MDM.PET_BREED_SIZE (
BREED_SIZE_CODE
,BREED_SIZE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
BREED_SIZE_CODE
,BREED_SIZE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM ICRM_TBL.PET_BREED_SIZE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L52
REPLACE VIEW MDM.PET_LIFE_STAGE (
BREED_SIZE_CODE
,PET_TYPE_CODE
,LOWER_AGE_LIMIT
,UPPER_AGE_LIMIT
,PET_LIFE_STAGE_NAME
,PET_LIFE_STAGE_DESC
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
BREED_SIZE_CODE
,PET_TYPE_CODE
,LOWER_AGE_LIMIT
,UPPER_AGE_LIMIT
,PET_LIFE_STAGE_NAME
,PET_LIFE_STAGE_DESC
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM ICRM_TBL.PET_LIFE_STAGE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L53
REPLACE VIEW MDM.PET_TRT (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,PET_SEQ_NBR
,PET_TRT_SEQ_NBR
,TRT_NBR
,PET_TRT_DATE
,PET_TRT_TXT
,LEGAL_ENT_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,PET_SEQ_NBR
,PET_TRT_SEQ_NBR
,TRT_NBR
,PET_TRT_DATE
,PET_TRT_TXT
,LEGAL_ENT_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.PET_TRT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L54
REPLACE VIEW MDM.PET_TYPE (
PET_TYPE_CODE
,PET_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
PET_TYPE_CODE
,PET_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM ICRM_TBL.PET_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L55
REPLACE VIEW MDM.PREDFND_TRT_VAL (
TRT_NBR
,PREDFND_TRT_VAL_NBR
,PREDFND_TRT_DATE
,PREDFND_TRT_TXT
,PREDFND_TRT_VAL_NAME
,PREDFND_TRT_DESC
,LANG_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS 
SEQUENCED  TRANSACTIONTIME SELECT
TRT_NBR
,PREDFND_TRT_VAL_NBR
,PREDFND_TRT_DATE
,PREDFND_TRT_TXT
,PREDFND_TRT_VAL_NAME
,PREDFND_TRT_DESC
,LANG_CODE
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.PREDFND_TRT_VAL;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L56
REPLACE VIEW MDM.PRSNA_POSTL_ADDR_ORIG
AS LOCKING ROW FOR ACCESS SELECT
* FROM iCRM_TBL.PRSNA_POSTL_ADDR_ORIG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L57
REPLACE VIEW MDM.PRSNA_STATUS (
PRSNA_STATUS_CODE
,PRSNA_STATUS_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
PRSNA_STATUS_CODE
,PRSNA_STATUS_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.PRSNA_STATUS;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L58
REPLACE VIEW MDM.PRSNA_TRT (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,TRT_NBR
,PRSNA_TRT_SEQ_NBR
,LEGAL_ENT_NBR
,PRSNA_TRT_DATE
,PRSNA_TRT_TXT
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS 
SELECT 
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,TRT_NBR
,PRSNA_TRT_SEQ_NBR
,LEGAL_ENT_NBR
,PRSNA_TRT_DATE
,PRSNA_TRT_TXT
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.PRSNA_TRT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L59
REPLACE VIEW MDM.REGIS_PRSNA (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,MATCHD_CNSMR_PRSNA_ID
,REFERAL_MKTNG_PGM_NBR
,TRM_LEAD_KEY
,NAME_PREFX_TXT
,GVN_NAME
,MID_NAME
,FAMLY_NAME
,NAME_SUFFX_TXT
,FULL_NAME
,GENDR_IND
,BRTH_DATE
,LANG_CODE
,CNTRY_CODE
,EMAIL_SUPRSN_IND
,POSTL_SUPRSN_IND
,PHONE_SUPRSN_IND
,SOCL_NETWK_SUPRSN_IND
,NATIONAL_ID_NBR
,CNSMR_SENTIMENT
,LATST_ACTVY_DATE
,REGIS_CNSMR_ID_VAL
,CNSMR_USER_NAME
,REGIS_DATE
,PRSNA_STATUS_CODE
,LYLTY_PGM_NBR
,LYLTY_ACCT_NUM
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,data_srce_nbr
,DATA_ORIGIN_SRCE_NBR
,DATA_OP_SRCE_NAME
,PII_DATA_MINIMIZE_DATETM
,GVN_NAME_ALIAS
,FAMLY_NAME_ALIAS
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,MATCHD_CNSMR_PRSNA_ID
,REFERAL_MKTNG_PGM_NBR
,TRM_LEAD_KEY
,NAME_PREFX_TXT
,GVN_NAME
,MID_NAME
,FAMLY_NAME
,NAME_SUFFX_TXT
,FULL_NAME
,GENDR_IND
,BRTH_DATE
,LANG_CODE
,CNTRY_CODE
,EMAIL_SUPRSN_IND
,POSTL_SUPRSN_IND
,PHONE_SUPRSN_IND
,SOCL_NETWK_SUPRSN_IND
,NATIONAL_ID_NBR
,CNSMR_SENTIMENT
,LATST_ACTVY_DATE
,REGIS_CNSMR_ID_VAL
,CNSMR_USER_NAME
,REGIS_DATETM
,PRSNA_STATUS_CODE
,LYLTY_PGM_NBR
,LYLTY_ACCT_NUM
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,data_srce_nbr
,DATA_ORIGIN_SRCE_NBR
,DATA_OP_SRCE_NAME
,PII_DATA_MINIMIZE_DATETM
,GVN_NAME_ALIAS
,FAMLY_NAME_ALIAS
FROM iCRM_TBL.REGIS_PRSNA;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L60
REPLACE VIEW MDM.REGIS_PRSNA_EMAIL_ADDR (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,SUBSCRPTN_OPT_NBR
,SUBSCRPTN_OPT_IND
,CNSMR_CHCE_DATETM
,PREF_CNTCT_POINT_IND
,EMAIL_ADDR_TXT
,EMAIL_FORMT_CODE
,VALID_CNTCT_POINT_IND
,GUARDN_NAME
,GUARDN_EMAIL_ADDR_TXT
,GUARDN_CNSNT_IND
,ACNLGMT_DATE
,EMAIL_STATUS_CODE
,DATA_SRCE_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,LAST_RTN_DATETM
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,SUBSCRPTN_OPT_NBR
,SUBSCRPTN_OPT_IND
,CNSMR_CHCE_DATETM
,PREF_CNTCT_POINT_IND
,EMAIL_ADDR_TXT
,EMAIL_FORMT_CODE
,VALID_CNTCT_POINT_IND
,GUARDN_NAME
,GUARDN_EMAIL_ADDR_TXT
,GUARDN_CNSNT_IND
,ACNLGMT_DATE
,EMAIL_STATUS_CODE
,DATA_SRCE_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,LAST_RTN_DATETM
FROM iCRM_TBL.REGIS_PRSNA_EMAIL_ADDR;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L61
REPLACE VIEW MDM.REGIS_PRSNA_OPT_HIST 
 AS
 LOCKING ROW FOR ACCESS
 SELECT
 REGIS_PRSNA_ID                ,
 MKTNG_PGM_NBR                 ,
 LEGAL_ENT_NBR                 ,
 DATA_SRCE_NBR                 ,
 SUBSCRIPTION_NBR              ,
 FIRST_NAME                    ,
 LAST_NAME                     ,
 EMAIL_ADDR_TEXT               ,
 CONTACT_PHONE_NBR             ,
 SRC_ADDR_LINE_1_TXT           ,
 SRC_ADDR_LINE_2_TXT           ,
 SRC_ADDR_LINE_3_TXT           ,
 SRC_CITY_NAME                 ,
 SRC_STATE                     ,
 SRC_ZIP                       ,
 SRC_CNTRY_NAME                ,
 ADDR_LINE_1_TXT               ,
 ADDR_LINE_2_TXT               ,
 ADDR_LINE_3_TXT               ,
 CITY_NAME                     ,
 TERR_NAME                     ,
 POSTL_AREA_CODE               ,
 CNTRY_NAME                    ,
 OPT_IND                       ,
 OPT_TIME                  ,
 OPT_REASN_TXT             ,
 OPT_TYPE_CODE,
 LAST_ACTIVITY_TM              ,
 LOG_SOURCE_ID                 ,
 LOG_UPDATE_USER               ,
 LOG_LOAD_ID                  ,
 PE_OPTOUT_ID              ,
 NATIONAL_ID_NBR           ,
 CHANNEL_IND               ,
 OPT_LEVEL_IND             ,
 POSTL_ADDR_ID
FROM ICRM_TBL.REGIS_PRSNA_OPT_HIST ;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L62
REPLACE VIEW MDM.REGIS_PRSNA_PHONE (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,SUBSCRPTN_OPT_NBR
,SUBSCRPTN_OPT_IND
,CNSMR_CHCE_DATETM
,PREF_CNTCT_POINT_IND
,PHONE_CNTRY_NBR
,PHONE_AREA_NBR
,PHONE_EXCHG_NBR
,PHONE_LINE_NBR
,PHONE_EXTSN_NUM
,FULL_PHONE_NUM
,SMS_PREFR_IND
,SMS_AVAIL_START_TIME
,SMS_AVAIL_END_TIME
,VALID_CNTCT_POINT_IND
,GUARDN_NAME
,GUARDN_EMAIL_ADDR_TXT
,GUARDN_CNSNT_IND
,ACNLGMT_DATE
,PHONE_STATUS_CODE
,DATA_SRCE_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,LAST_RTN_DATETM
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,SUBSCRPTN_OPT_NBR
,SUBSCRPTN_OPT_IND
,CNSMR_CHCE_DATETM
,PREF_CNTCT_POINT_IND
,PHONE_CNTRY_NBR
,PHONE_AREA_NBR
,PHONE_EXCHG_NBR
,PHONE_LINE_NBR
,PHONE_EXTSN_NUM
,FULL_PHONE_NUM
,SMS_PREFR_IND
,SMS_AVAIL_START_TIME
,SMS_AVAIL_END_TIME
,VALID_CNTCT_POINT_IND
,GUARDN_NAME
,GUARDN_EMAIL_ADDR_TXT
,GUARDN_CNSNT_IND
,ACNLGMT_DATE
,PHONE_STATUS_CODE
,DATA_SRCE_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,LAST_RTN_DATETM
FROM iCRM_TBL.REGIS_PRSNA_PHONE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L63
REPLACE VIEW MDM.REGIS_PRSNA_POSTL_ADDR (
CNTCT_POINT_CATEG_CODE
,REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,WIN_KEY
,SUBSCRPTN_OPT_NBR
,SUBSCRPTN_OPT_IND
,CNSMR_CHCE_DATETM
,PREF_CNTCT_POINT_IND
,ADDR_LINE_1_TXT
,ADDR_LINE_2_TXT
,ADDR_LINE_3_TXT
,STRET_NUM
,STRET_NAME
,APT_NUM
,PO_BOX_NUM
,CITY_NAME
,CITY_CODE
,POSTL_AREA_CODE
,TERR_CODE
,CNTRY_CODE
,LAT_MEAS
,LONG_MEAS
,GL_ACCURACY
,GL_MATCH_FLG
,DR_CLEANSE_LVL
,VALID_CNTCT_POINT_IND
,GUARDN_NAME
,GUARDN_EMAIL_ADDR_TXT
,GUARDN_CNSNT_IND
,ACNLGMT_DATE
,POSTL_STATUS_CODE
,PR_GEOCODE_FAIL
,TQ_GOUT_MATCH_LEVEL
,PR_REV_GROUP
,DATA_SRCE_NBR
,TERR_NAME
,POSTL_ADDR_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,LAST_RTN_DATETM
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
CNTCT_POINT_CATEG_CODE
,REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,WIN_KEY
,SUBSCRPTN_OPT_NBR
,SUBSCRPTN_OPT_IND
,CNSMR_CHCE_DATETM
,PREF_CNTCT_POINT_IND
,ADDR_LINE_1_TXT
,ADDR_LINE_2_TXT
,ADDR_LINE_3_TXT
,STRET_NUM
,STRET_NAME
,APT_NUM
,PO_BOX_NUM
,CITY_NAME
,CITY_CODE
,POSTL_AREA_CODE
,TERR_CODE
,CNTRY_CODE
,LAT_MEAS
,LONG_MEAS
,GL_ACCURACY
,GL_MATCH_FLG
,DR_CLEANSE_LVL
,VALID_CNTCT_POINT_IND
,GUARDN_NAME
,GUARDN_EMAIL_ADDR_TXT
,GUARDN_CNSNT_IND
,ACNLGMT_DATE
,POSTL_STATUS_CODE
,PR_GEOCODE_FAIL
,TQ_GOUT_MATCH_LEVEL
,PR_REV_GROUP
,DATA_SRCE_NBR
,TERR_NAME
,POSTL_ADDR_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,LAST_RTN_DATETM
FROM iCRM_TBL.REGIS_PRSNA_POSTL_ADDR;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L64

REPLACE VIEW MDM.REGIS_PRSNA_SOC_NETK_ACT (
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,SUBSCRPTN_OPT_NBR
,SUBSCRPTN_OPT_IND
,CNSMR_CHCE_DATETM
,PREF_CNTCT_POINT_IND
,SOCIAL_NETWK_ACCT_ID_VAL
,VALID_CNTCT_POINT_IND
,GUARDN_NAME
,GUARDN_EMAIL_ADDR_TXT
,GUARDN_CNSNT_IND
,ACNLGMT_DATE
,SOC_NET_STATUS_CODE
,DATA_SRCE_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,LAST_RTN_DATETM 
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
REGIS_PRSNA_ID
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,CNTCT_POINT_CATEG_CODE
,SUBSCRPTN_OPT_NBR
,SUBSCRPTN_OPT_IND
,CNSMR_CHCE_DATETM
,PREF_CNTCT_POINT_IND
,SOCIAL_NETWK_ACCT_ID_VAL
,VALID_CNTCT_POINT_IND
,GUARDN_NAME
,GUARDN_EMAIL_ADDR_TXT
,GUARDN_CNSNT_IND
,ACNLGMT_DATE
,SOC_NET_STATUS_CODE
,DATA_SRCE_NBR
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
,LAST_RTN_DATETM
FROM iCRM_TBL.REGIS_PRSNA_SOC_NET_ACCT;

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L65
REPLACE VIEW MDM.REJECT_STRING AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.REJECT_STRING;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L66
REPLACE VIEW MDM.RETLR (
RETLR_NBR
,PARENT_RETLR_NBR
,RETLR_TYPE_CD
,RETLR_NAME
,RETLR_NAME_NTV
,DATA_SRCE_NBR
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY 
) AS LOCKING ROW FOR ACCESS SELECT
RETLR_NBR
,PARENT_RETLR_NBR
,RETLR_TYPE_CD
,RETLR_NAME
,RETLR_NAME_NTV
,DATA_SRCE_NBR
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.RETLR;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L67
REPLACE VIEW MDM.RETLR_TYPE (
RETLR_TYPE_CD
, RETLR_TYPE_NAME
, LOG_SOURCE_ID
, LOG_UPDATE_USER
, LOG_LOAD_ID
,SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
RETLR_TYPE_CD
, RETLR_TYPE_NAME
, LOG_SOURCE_ID
, LOG_UPDATE_USER
, LOG_LOAD_ID
,SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
FROM iCRM_TBL.RETLR_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L68
REPLACE VIEW MDM.RTN_EXTR_CONFIG (
MKTNG_PGM_NBR
,FULL_EXTR_IND
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME  SELECT
MKTNG_PGM_NBR
,FULL_EXTR_IND
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.RTN_EXTR_CONFIG;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L69
REPLACE VIEW MDM.RTN_RULES AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.RTN_RULES;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L70
REPLACE VIEW MDM.RTN_RULES_DTL AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.RTN_RULES_DTL;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L71
REPLACE VIEW MDM.SALES_CONTR(
CONTR_NBR
, MKTNG_PGM_NBR
,RETLR_NBR
, STORE_NBR
, LOG_SOURCE_ID
, LOG_UPDATE_USER
, LOG_LOAD_ID
,SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
CONTR_NBR
, MKTNG_PGM_NBR
,RETLR_NBR
, STORE_NBR
, LOG_SOURCE_ID
, LOG_UPDATE_USER
, LOG_LOAD_ID
,SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
FROM iCRM_TBL.SALES_CONTR;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L72
REPLACE VIEW MDM.STORE 
AS LOCKING ROW FOR ACCESS 
SELECT
STORE_NBR
,RETLR_NBR
,STORE_NAME
,STORE_NAME_NTV
,STORE_STATUS_CD
,STORE_TYPE_CODE
,ADDR_LINE_1_TXT
,ADDR_LINE_2_TXT
,ADDR_LINE_3_TXT
,STRET_NUM
,STRET_NAME
,APT_NUM
,PO_BOX_NUM
,CITY_CODE
,CITY_NAME
,TERR_CODE
,TERR_NAME
,CNTRY_CODE
,POSTL_AREA_CODE
,LAT_MEAS
,LONG_MEAS
,GL_ACCURACY
,GL_MATCH_FLG
,DR_CLEANSE_LVL
,DATA_SRCE_NBR
,ALT_STORE_ID
,STORE_PHN_NBR
,VALID_CNTCT_POINT_IND
,PR_GEOCODE_FAIL
,TQ_GOUT_MATCH_LEVEL
,PR_REV_GROUP
,POSTL_ADDR_ID
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.STORE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L73
REPLACE VIEW MDM.STORE_TYPE 
(
STORE_TYPE_CODE
,STORE_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SELECT
STORE_TYPE_CODE
,STORE_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.STORE_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



.LABEL L74
REPLACE VIEW MDM.SUBSCRPTN_OPT (
SUBSCRPTN_OPT_NBR
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,SUBSCRPTN_OPT_NAME
,SUBSCRPTN_OPT_STMT_TXT
,SUBSCRPTN_VERSION_NBR
,PARNTL_CNSNT_IND
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
SUBSCRPTN_OPT_NBR
,MKTNG_PGM_NBR
,LEGAL_ENT_NBR
,SUBSCRPTN_OPT_NAME
,SUBSCRPTN_OPT_STMT_TXT
,SUBSCRPTN_VERSION_NBR
,PARNTL_CNSNT_IND
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.SUBSCRPTN_OPT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



.LABEL L75
REPLACE VIEW MDM.SUBSCRPTN_OPT_TYPE (     
SUBSCRPTN_OPT_NBR    
,MKTNG_PGM_NBR    
,LEGAL_ENT_NBR    
,CNTCT_CHANL_TYPE_CODE    
,CNTCT_POINT_CATEG_CODE    
,SUBSCRPTN_OPT_FREQ_TXT    
,SYS_SOURCE    
,SYS_TARGET_ID    
,SYS_AUTH_ID    
,SYS_CREATED_BY    
,SYS_CREATION_DATE    
,SYS_LAST_MODIFIED_DATE    
,SYS_ENT_STATE    
,SYS_LAST_MODIFIED_BY    
,SYS_NC_TYPE    
,SYS_ERR_CODE    
,SYS_ERR_SVRTY    
) AS LOCKING ROW FOR ACCESS SELECT    
SUBSCRPTN_OPT_NBR    
,MKTNG_PGM_NBR    
,LEGAL_ENT_NBR    
,CNTCT_CHANL_TYPE_CODE     
,CNTCT_POINT_CATEG_CODE    
,SUBSCRPTN_OPT_FREQ_TXT    
,SYS_SOURCE    
,SYS_TARGET_ID    
,SYS_AUTH_ID    
,SYS_CREATED_BY    
,SYS_CREATION_DATE    
,SYS_LAST_MODIFIED_DATE    
,SYS_ENT_STATE    
,SYS_LAST_MODIFIED_BY    
,SYS_NC_TYPE    
,SYS_ERR_CODE    
,SYS_ERR_SVRTY    
FROM iCRM_TBL.SUBSCRPTN_OPT_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



.LABEL L76
REPLACE VIEW MDM.TERR (
TERR_CODE
,CNTRY_CODE
,TERR_CODE_NTV
,TERR_NAME
,TERR_NAME_NTV
,TERR_SHORT_NAME
,TERR_DESC
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
TERR_CODE
,CNTRY_CODE
,TERR_CODE_NTV
,TERR_NAME
,TERR_NAME_NTV
,TERR_SHORT_NAME
,TERR_DESC
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.TERR;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



.LABEL L77
REPLACE VIEW mdm.TRILLIUM_OUTPUT (                                              
MKTNG_PGM_NBR                                                                 
,REGIS_CNSMR_ID_VAL                                                            
,DR_ALIAS_CONTACT                                                              
,DR_FIRST_NAME                                                                 
,DR_MIDDLE_NAME                                                                
,DR_LAST_NAME                                                                  
,DR_MRMRS                                                                      
,DR_NAME_GENER                                                                 
,DR_NAME_SUFFIX                                                                
,DR_NAME_GENDER                                                                
,DR_COUNTRY_NAME                                                               
,DR_REGION_NAME                                                                
,DR_CITY_NAME                                                                  
,DR_POSTAL_CODE                                                                
,DR_STREET_NAME                                                                
,DR_HOUSE_NUMBER1                                                              
,DR_HOUSE_NUMBER2                                                              
,DR_POBOX_NUMBER                                                               
,DR_ADDRESS                                                                    
,DR_ADDRESS2                                                                   
,DR_ADDRESS3                                                            
,PR_REV_GROUP                                                                  
,GOUT_MATCH_LEVEL                                                              
,WINDOW_KEY_01                                                                 
,REFERENCE_HOUSEHOLD_ID                                                        
,REFERENCE_LEGALENTITYKEY                                                      
,REFERENCE_REGISTRATIONKEY                                                     
,LEGAL_ENT_NBR                                                                 
,BRTH_DATE                                                                     
,LANG_CODE                                                                     
,CNSMR_USER_NAME                                                               
,STATUS                                                                        
,FULL_NAME                                                                     
,PR_NAME_FORM_01                                                               
,DR_ALIAS_ACCOUNT                                                
,DR_BUSINESS_NAME 
,REGIS_DATE
,RECORD_IND
,RECENT_IND
,REGIS_PRSNA_ID 
,HH_FLAG
,LE_FLAG
,SYS_TARGET_ID                                                                 
,SYS_AUTH_ID                                                                   
,SYS_SOURCE                                                                    
,SYS_CREATED_BY                                                                
,SYS_CREATION_DATE                                                             
,SYS_ENT_STATE                                                                 
,SYS_LAST_MODIFIED_BY                                                          
,SYS_LAST_MODIFIED_DATE                                                        
,SYS_NC_TYPE                                                                   
,SYS_ERR_CODE                                                                  
,SYS_ERR_SVRTY              
,ADDRESS_CONTACT
,ADDRESS_SUBSCRPTN
,EMAIL_CONTACT
,EMAIL_SUBSCRPTN
,PHONE_CONTACT
,PHONE_SUBSCRPTN
) AS LOCKING ROW FOR ACCESS SELECT  
DISTINCT
MKTNG_PGM_NBR                                                                 
,REGIS_CNSMR_ID_VAL                                                            
,DR_ALIAS_CONTACT                                                              
,DR_FIRST_NAME                                                                 
,DR_MIDDLE_NAME                                                                
,DR_LAST_NAME                                                                  
,DR_MRMRS                                                                      
,DR_NAME_GENER                                                                 
,DR_NAME_SUFFIX                                                                
,DR_NAME_GENDER                                                                
,DR_COUNTRY_NAME                                                               
,DR_REGION_NAME                                                                
,DR_CITY_NAME                                                                  
,DR_POSTAL_CODE                                                                
,DR_STREET_NAME                                                                
,DR_HOUSE_NUMBER1                                                              
,DR_HOUSE_NUMBER2                                                              
,DR_POBOX_NUMBER                                                               
,DR_ADDRESS                                                                    
,DR_ADDRESS2                                                                   
,DR_ADDRESS3                                                                 
,PR_REV_GROUP                                                                  
,GOUT_MATCH_LEVEL                                                              
,WINDOW_KEY_01                                                                 
,REFERENCE_HOUSEHOLD_ID                                                        
,REFERENCE_LEGALENTITYKEY                                                      
,REFERENCE_REGISTRATIONKEY                                                     
,LEGAL_ENT_NBR                                                                 
,BRTH_DATE                                                                     
,LANG_CODE                                                                     
,CNSMR_USER_NAME                                                               
,STATUS                                                                        
,FULL_NAME                                                                     
,PR_NAME_FORM_01                                                               
,DR_ALIAS_ACCOUNT                                            
,DR_BUSINESS_NAME  
,REGIS_DATE
,RECORD_IND
,RECENT_IND 
,REGIS_PRSNA_ID
,HH_FLAG
,LE_FLAG
,SYS_TARGET_ID                                                                 
,SYS_AUTH_ID                                                                   
,SYS_SOURCE                                                                    
,SYS_CREATED_BY                                                                
,SYS_CREATION_DATE                                                             
,SYS_ENT_STATE                                                                 
,SYS_LAST_MODIFIED_BY                                                          
,SYS_LAST_MODIFIED_DATE                                                        
,SYS_NC_TYPE                                                                   
,SYS_ERR_CODE                                                                  
,SYS_ERR_SVRTY     
,ADDRESS_CONTACT
,ADDRESS_SUBSCRPTN
,EMAIL_CONTACT
,EMAIL_SUBSCRPTN
,PHONE_CONTACT
,PHONE_SUBSCRPTN
FROM mdm.TRILLIUM_OUTPUT1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;



.LABEL L78
REPLACE VIEW MDM.TRILLIUM_OUTPUT_DUP (                                              
MKTNG_PGM_NBR                                                                 
,REGIS_CNSMR_ID_VAL                                                            
,DR_ALIAS_CONTACT                                                              
,DR_FIRST_NAME                                                                 
,DR_MIDDLE_NAME                                                                
,DR_LAST_NAME                                                                  
,DR_MRMRS                                                                      
,DR_NAME_GENER                                                                 
,DR_NAME_SUFFIX                                                                
,DR_NAME_GENDER                                                                
,DR_COUNTRY_NAME                                                               
,DR_REGION_NAME                                                                
,DR_CITY_NAME                                                                  
,DR_POSTAL_CODE                                                                
,DR_STREET_NAME                                                                
,DR_HOUSE_NUMBER1                                                              
,DR_HOUSE_NUMBER2                                                              
,DR_POBOX_NUMBER                                                               
,DR_ADDRESS                                                                    
,DR_ADDRESS2                                                                   
,DR_ADDRESS3                                                                   
,CLEANSED_PHONE_1                                                              
,CLEANSED_EMAIL_1                                                              
,PR_REV_GROUP                                                                  
,GOUT_MATCH_LEVEL                                                              
,WINDOW_KEY_01                                                                 
,REFERENCE_HOUSEHOLD_ID                                                        
,REFERENCE_LEGALENTITYKEY                                                      
,REFERENCE_REGISTRATIONKEY                                                     
,LEGAL_ENT_NBR                                                                 
,BRTH_DATE                                                                     
,LANG_CODE                                                                     
,CNSMR_USER_NAME                                                               
,STATUS                                                                        
,FULL_NAME                                                                     
,DPEND_NAME                                                                    
,PET_NAME                                                                      
,PR_NAME_FORM_01                                                               
,DR_ALIAS_ACCOUNT                                                              
,REFERENCE_MATCHED_LEV1_PATTERN                                                
,REFERENCE_MATCHED_LEV2_PATTERN                                                
,DR_BUSINESS_NAME                                                              
,EMAIL_IND       
,REGIS_DATE
,RECORD_IND
,RECENT_IND
,DUP_REGIS_PRSNA_ID
,SYS_TARGET_ID                                                                 
,SYS_AUTH_ID                                                                   
,SYS_SOURCE                                                                    
,SYS_CREATED_BY                                                                
,SYS_CREATION_DATE                                                             
,SYS_ENT_STATE                                                                 
,SYS_LAST_MODIFIED_BY                                                          
,SYS_LAST_MODIFIED_DATE                                                        
,SYS_NC_TYPE                                                                   
,SYS_ERR_CODE                                                                  
,SYS_ERR_SVRTY                                                                 
) AS LOCKING ROW FOR ACCESS SELECT                                              
MKTNG_PGM_NBR                                                                 
,REGIS_CNSMR_ID_VAL                                                            
,DR_ALIAS_CONTACT                                                              
,DR_FIRST_NAME                                                                 
,DR_MIDDLE_NAME                                                                
,DR_LAST_NAME                                                                  
,DR_MRMRS                                                                      
,DR_NAME_GENER                                                                 
,DR_NAME_SUFFIX                                                                
,DR_NAME_GENDER                                                                
,DR_COUNTRY_NAME                                                               
,DR_REGION_NAME                                                                
,DR_CITY_NAME                                                                  
,DR_POSTAL_CODE                                                                
,DR_STREET_NAME                                                                
,DR_HOUSE_NUMBER1                                                              
,DR_HOUSE_NUMBER2                                                              
,DR_POBOX_NUMBER                                                               
,DR_ADDRESS                                                                    
,DR_ADDRESS2                                                                   
,DR_ADDRESS3                                                                   
,CLEANSED_PHONE_1                                                              
,CLEANSED_EMAIL_1                                                              
,PR_REV_GROUP                                                                  
,GOUT_MATCH_LEVEL                                                              
,WINDOW_KEY_01                                                                 
,REFERENCE_HOUSEHOLD_ID                                                        
,REFERENCE_LEGALENTITYKEY                                                      
,REFERENCE_REGISTRATIONKEY                                                     
,LEGAL_ENT_NBR                                                                 
,BRTH_DATE                                                                     
,LANG_CODE                                                                     
,CNSMR_USER_NAME                                                               
,STATUS                                                                        
,FULL_NAME                                                                     
,DPEND_NAME                                                                    
,PET_NAME                                                                      
,PR_NAME_FORM_01                                                               
,DR_ALIAS_ACCOUNT                                                              
,REFERENCE_MATCHED_LEV1_PATTERN                                                
,REFERENCE_MATCHED_LEV2_PATTERN                                                
,DR_BUSINESS_NAME                                                              
,EMAIL_IND     
,REGIS_DATE
,RECORD_IND
,RECENT_IND 
,DUP_REGIS_PRSNA_ID
,SYS_TARGET_ID                                                                 
,SYS_AUTH_ID                                                                   
,SYS_SOURCE                                                                    
,SYS_CREATED_BY                                                                
,SYS_CREATION_DATE                                                             
,SYS_ENT_STATE                                                                 
,SYS_LAST_MODIFIED_BY                                                          
,SYS_LAST_MODIFIED_DATE                                                        
,SYS_NC_TYPE                                                                   
,SYS_ERR_CODE                                                                  
,SYS_ERR_SVRTY                                                                 
FROM MDM.TRILLIUM_OUTPUT_DUP1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L79
REPLACE VIEW MDM.TRM_COUPN_LEADKEY_CNTRL AS LOCKING ROW FOR ACCESS SELECT * FROM iCRM_TBL.TRM_COUPN_LEADKEY_CNTRL;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L80
REPLACE VIEW MDM.TRT (
TRT_NBR
,TRT_ENT_TYPE_CODE
,TRT_NAME
,TRT_DESC
,TRT_DTTP_CODE
,PII_DATA_IND
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
) AS LOCKING ROW FOR ACCESS SEQUENCED  TRANSACTIONTIME SELECT
TRT_NBR
,TRT_ENT_TYPE_CODE
,TRT_NAME
,TRT_DESC
,TRT_DTTP_CODE
,PII_DATA_IND
,SYS_SOURCE
,SYS_TARGET_ID
,SYS_AUTH_ID
,SYS_CREATED_BY
,SYS_CREATION_DATE
,SYS_LAST_MODIFIED_DATE
,SYS_ENT_STATE
,SYS_LAST_MODIFIED_BY
,SYS_NC_TYPE
,SYS_ERR_CODE
,SYS_ERR_SVRTY
FROM iCRM_TBL.TRT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L81
REPLACE VIEW MDM.TRT_ENT_TYPE (
TRT_ENT_TYPE_CODE
,TRT_ENT_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
TRT_ENT_TYPE_CODE
,TRT_ENT_TYPE_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.TRT_ENT_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L82
REPLACE VIEW MDM.WEB_SITE(
WEB_SITE_NBR
, WEB_SITE_URL_TXT
, IS_WEB_STORE_IND
, DATA_SRCE_NBR
,CNTRY_CODE
, LOG_SOURCE_ID
, LOG_UPDATE_USER
, LOG_LOAD_ID
,SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY 
) AS LOCKING ROW FOR ACCESS SELECT
WEB_SITE_NBR
, WEB_SITE_URL_TXT
, IS_WEB_STORE_IND
, DATA_SRCE_NBR
,CNTRY_CODE
, LOG_SOURCE_ID
, LOG_UPDATE_USER
, LOG_LOAD_ID
,SYS_SOURCE,
SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_LAST_MODIFIED_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY 
FROM iCRM_TBL.WEB_SITE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L83
REPLACE VIEW MDM.BRAND (
BRAND_CODE
,BRAND_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
BRAND_CODE
,BRAND_NAME
,LOG_SOURCE_ID
,LOG_UPDATE_USER
,LOG_LOAD_ID
FROM iCRM_TBL.BRAND;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L84
CREATE MULTISET TABLE MDM.CNSMR_AFFLTN_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
CNSMR_GRP_NBR INTEGER NOT NULL,
AFFLTN_START_DATE DATE FORMAT 'YY/MM/DD',
AFFLTN_END_DATE DATE FORMAT 'YY/MM/DD',
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
NC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX CNSMR_AFFLTN_NUPI ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L85
CREATE MULTISET TABLE MDM.PRSNA_SOC_NETWK_ACCT_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
SOCIAL_NETWK_ACCT_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
PREFR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
VALID_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
NC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNTCT_OPTN_NBR DECIMAL(4,2),
CNTCT_OPTN_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNSMR_CHCE_DATETM TIMESTAMP(0),
GUARDN_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
GUARDN_EMAIL_ADDR_TXT VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
GUARDN_CNSNT_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
ACNLGMT_DATE DATE FORMAT 'YY/MM/DD',
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX PRSNA_S114_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L86
CREATE MULTISET TABLE MDM.PRSNA_PHONE_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
PHONE_CNTRY_NBR INTEGER,
PHONE_AREA_NBR INTEGER,
PHONE_EXCHG_NBR INTEGER,
PHONE_LINE_NBR INTEGER,
PHONE_EXTSN_NUM VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
FULL_PHONE_NUM VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
SMS_PREFR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
SMS_AVAIL_START_TIME TIME(6),
SMS_AVAIL_END_TIME TIME(6),
CNTCT_OPTN_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
PREFR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
VALID_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNTCT_OPTN_NBR DECIMAL(4,2),
CNSMR_CHCE_DATETM TIMESTAMP(0),
GUARDN_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
GUARDN_EMAIL_ADDR_TXT VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
GUARDN_CNSNT_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
ACNLGMT_DATE DATE FORMAT 'YY/MM/DD',
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX PRSNA_P116_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L87
CREATE MULTISET TABLE MDM.PET_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
PET_SEQ_NBR INTEGER NOT NULL,
PET_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
PET_GENDR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
PET_BRTH_DATE DATE FORMAT 'YY/MM/DD',
PET_AGE_NBR INTEGER,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX PET_STG_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L88
CREATE MULTISET TABLE MDM.PRSNA_EMAIL_ADDR_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
EMAIL_ADDR_TXT VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
EMAIL_FORMT_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNTCT_OPTN_NBR DECIMAL(4,2),
CNTCT_OPTN_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
PREFR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
VALID_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNSMR_CHCE_DATETM TIMESTAMP(0),
GUARDN_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
GUARDN_EMAIL_ADDR_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
GUARDN_CNSNT_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
ACNLGMT_DATE DATE FORMAT 'YY/MM/DD',
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX PRSNA_E117_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L89
CREATE MULTISET TABLE MDM.PET_TRT_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
PET_SEQ_NBR INTEGER NOT NULL,
TRT_ID INTEGER NOT NULL,
PET_TRT_DATE DATE FORMAT 'YY/MM/DD',
PET_TRT_INTEGRE INTEGER,
PET_TRT_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
PET_TRT_SEQ_NBR INTEGER NOT NULL,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX PET_TRT_STG_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L90
CREATE MULTISET TABLE MDM.PRSNA_POSTL_ADDR_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
CNTCT_POINT_CATEG_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
ADDR_LINE_1_TXT VARCHAR(500) CHARACTER SET UNICODE NOT CASESPECIFIC,
ADDR_LINE_2_TXT VARCHAR(500) CHARACTER SET UNICODE NOT CASESPECIFIC,
ADDR_LINE_3_TXT VARCHAR(500) CHARACTER SET UNICODE NOT CASESPECIFIC,
STRET_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
STRET_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
APT_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
PO_BOX_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
CITY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
TERR_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
POSTL_AREA_CODE VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
GEOC_AREA_TYPE_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
GEOC_AREA_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNTRY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
CNTCT_OPTN_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
PREFR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
VALID_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
NC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNTCT_OPTN_NBR DECIMAL(4,2),
CNSMR_CHCE_DATETM TIMESTAMP(0),
GUARDN_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
GUARDN_EMAIL_ADDR_TXT VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC,
GUARDN_CNSNT_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
ACNLGMT_DATE DATE FORMAT 'YY/MM/DD',
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX PRSNA_P115_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L91
CREATE MULTISET TABLE MDM.PRSNA_TRT_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
TRT_NBR INTEGER NOT NULL,
PRSNA_TRT_SEQ_NBR INTEGER NOT NULL,
PRSNA_TRT_DATE DATE FORMAT 'YY/MM/DD',
PRSNA_TRT_INTEGER INTEGER,
PRSNA_TRT_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX PRSNA_T113_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L92
CREATE MULTISET TABLE MDM.DPEND_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
DPEND_SEQ_NBR INTEGER NOT NULL,
DPEND_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
DPEND_GENDR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
DPEND_BRTH_DATE DATE FORMAT 'YY/MM/DD',
DPEND_AGE_NBR INTEGER,
DPEND_TYPE_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX DPEND_STG_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L93
CREATE SET TABLE MDM.PRSNA_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
USER_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
PRSNA_REG_DT TIMESTAMP(0) NOT NULL,
GVN_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
MID_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
FAMLY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
NAME_SUFFX_TXT CHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC,
FULL_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
GENDR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
BRTH_DATE DATE FORMAT 'YY/MM/DD',
LANG_CODE CHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC,
PRSNA_STTUS_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOYALTY_ACCT_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'LOYALTY_ACCT_ID',
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
WIN_KEY VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNTRY_CODE CHAR(3) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ),
LYLTY_ACCT_NUM VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
LYLTY_PGM_NBR SMALLINT,
NAME_PREFX_TXT VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC)
PRIMARY INDEX PRSNA_STG_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L94
CREATE MULTISET TABLE MDM.DPEND_TRT_STG ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER NOT NULL,
REGIS_CNSMR_ID_VAL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
DPEND_SEQ_NBR INTEGER NOT NULL,
TRT_NBR INTEGER NOT NULL,
DPEND_TRT_DATE DATE FORMAT 'YY/MM/DD',
DPEND_TRT_INTEGER INTEGER,
DPEND_TRT_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
DPEND_TRT_SEQ_NBR INTEGER NOT NULL,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BACKEND',
SYS_CREATED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_CREATION_DATE TIMESTAMP(0),
SYS_ENT_STATE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ))
PRIMARY INDEX DPEND_T124_PK ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL ,
SYS_SOURCE );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L95
CREATE SET TABLE MDM.err_prsna_stg ,NO FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO
(
MKTNG_PGM_NBR INTEGER,
REGIS_CNSMR_ID_VAL VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
USER_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
PRSNA_REG_DT TIMESTAMP(0),
GVN_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
MID_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
FAMLY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
NAME_SUFFX_TXT CHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC,
FULL_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
GENDR_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
BRTH_DATE DATE FORMAT 'YY/MM/DD',
LANG_CODE CHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC,
PRSNA_STTUS_CODE CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
RECORD_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
LOAD_ID DECIMAL(18,0),
LOAD_TS TIMESTAMP(0),
MDM_LOAD_IND CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
WIN_KEY VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYNC_STATUS VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
CNTRY_CODE CHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_TARGET_ID INTEGER,
SYS_AUTH_ID VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_SOURCE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'BackEnd',
SYS_ERROR_ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
(START WITH 1 
INCREMENT BY 2 
MINVALUE 1 
MAXVALUE 2147483647 
NO CYCLE),
SYS_ERROR_TIME TIMESTAMP(0),
SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ),
SYS_NC_TYPE VARCHAR(25) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_DOCUMENT VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC DEFAULT 'PRSNA_STG',
SYS_LOAD_ID VARCHAR(32) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_WORKFLOW_ID VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
SYS_ERR_CODE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
LYLTY_ACCT_NUM VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
LYLTY_PGM_NBR SMALLINT,
NAME_PREFX_TXT VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC)
PRIMARY INDEX ( MKTNG_PGM_NBR ,REGIS_CNSMR_ID_VAL );
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L96
REPLACE VIEW extrn_coupn_status as locking row for access select * from icrm_tbl.extrn_coupn_status;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L97
REPLACE VIEW DATA_SRCE_SUBS_OPT_TYPE as locking row for access select * from icrm_tbl.DATA_SRCE_SUBSCRPTN_OPT_TYPE;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L98
REPLACE VIEW DATA_SRCE_SUBS_OPT
	  (
	  DATA_SRCE_NBR ,
      MKTNG_PGM_NBR ,
      SUBSCRPTN_OPT_NBR ,
      LEGAL_ENT_NBR ,
      SUBSCRPTN_OPT_NAME ,
      SUBSCRPTN_OPT_STMT_TXT ,
      SUBSCRPTN_VERSION_NBR ,
      PARNTL_CNSNT_IND ,
      SUBSCRPTN_OPT_START_DATE ,
      SUBSCRPTN_OPT_END_DATE ,
      SYS_SOURCE  ,
      SYS_TARGET_ID ,
      SYS_AUTH_ID  ,
      SYS_CREATED_BY  ,
      SYS_CREATION_DATE ,
      SYS_LAST_MODIFIED_DATE ,
      SYS_ENT_STATE ,
      SYS_LAST_MODIFIED_BY ,
      SYS_NC_TYPE ,
      SYS_ERR_CODE ,
      SYS_ERR_SVRTY 
	  )
	  AS LOCKING ROW FOR ACCESS 
SEQUENCED  TRANSACTIONTIME 
SELECT
	  
	    DATA_SRCE_NBR ,
      MKTNG_PGM_NBR ,
      SUBSCRPTN_OPT_NBR ,
      LEGAL_ENT_NBR ,
      SUBSCRPTN_OPT_NAME ,
      SUBSCRPTN_OPT_STMT_TXT ,
      SUBSCRPTN_VERSION_NBR ,
      PARNTL_CNSNT_IND ,
      SUBSCRPTN_OPT_START_DATE ,
      SUBSCRPTN_OPT_END_DATE ,
      SYS_SOURCE  ,
      SYS_TARGET_ID ,
      SYS_AUTH_ID  ,
      SYS_CREATED_BY  ,
      SYS_CREATION_DATE ,
      SYS_LAST_MODIFIED_DATE ,
      SYS_ENT_STATE ,
      SYS_LAST_MODIFIED_BY ,
      SYS_NC_TYPE ,
      SYS_ERR_CODE ,
      SYS_ERR_SVRTY 
	  from icrm_tbl.DATA_SRCE_SUBSCRPTN_OPT;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L99
REPLACE VIEW MDM.REGIS_PRSNA_OPT_OUT_HIST 
AS
LOCKING ROW FOR ACCESS
SELECT
REGIS_PRSNA_ID                ,
MKTNG_PGM_NBR                 ,
LEGAL_ENT_NBR                 ,
DATA_SRCE_NBR                 ,
SUBSCRIPTION_NBR              ,
FIRST_NAME                    ,
LAST_NAME                     ,
EMAIL_ADDR_TEXT               ,
CONTACT_PHONE_NBR             ,
SRC_ADDR_LINE_1_TXT           ,
SRC_ADDR_LINE_2_TXT           ,
SRC_ADDR_LINE_3_TXT           ,
SRC_CITY_NAME                 ,
SRC_STATE                     ,
SRC_ZIP                       ,
SRC_CNTRY_NAME                ,
ADDR_LINE_1_TXT               ,
ADDR_LINE_2_TXT               ,
ADDR_LINE_3_TXT               ,
CITY_NAME                     ,
TERR_NAME                     ,
POSTL_AREA_CODE               ,
CNTRY_NAME                    ,
OPT_IND                       ,
OPT_TIME                  ,
OPT_REASN_TXT             ,
OPT_TYPE_CODE,
LAST_ACTIVITY_TM              ,
LOG_SOURCE_ID                 ,
LOG_UPDATE_USER               ,
LOG_LOAD_ID                  ,
PE_OPTOUT_ID              ,
NATIONAL_ID_NBR           ,
CHANNEL_IND               ,
OPT_LEVEL_IND             ,
POSTL_ADDR_ID
FROM ICRM_TBL.REGIS_PRSNA_OPT_HIST 
;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L100

REPLACE VIEW MDM.NCOA_ADDR_STG (
 
 MATCHD_CNSMR_PRSNA_ID,
 MKTNG_PGM_NBR,
 REGIS_PRSNA_ID,
 NEW_ADDRESS1,
 NEW_ADDRESS2,
 NEW_CITY,
 NEW_STATE,
 NEW_ZIP,
 NEW_COUNTRY,
 NCOA_DROP,
 DECEASED,
 DMA_DO_NOT_MAIL,
 NEW_ADDRESS_PRESENT,
 ADDR_LINE_1_TXT,
 ADDR_LINE_2_TXT,
 ADDR_LINE_3_TXT,
 STRET_NAME,
 STRET_NUM,
 APT_NUM,
 CITY_NAME,
 TERR_NAME,
 POSTL_AREA_CODE,
 CNTRY_NAME,
 WIN_KEY,
 LOAD_ID,
 LOAD_TS,
 MDM_LOAD_IND
 ,GL_ACCURACY  
 ,GL_MATCH_FLG  
 ,GL_LATITUDE  
 ,GL_LONGITUDE  
 ,DR_CLEANSE_LVL 
 ,VALID_CNTCT_POINT_IND
 ,PR_GEOCODE_FAIL 
 ,PR_REV_GROUP
 ,POSTL_ADDR_ID
 ) AS LOCKING ROW FOR ACCESS SELECT
 MATCHD_CNSMR_PRSNA_ID,
 MKTNG_PGM_NBR,
 REGIS_PRSNA_ID,
 NEW_ADDRESS1,
 NEW_ADDRESS2,
 NEW_CITY,
 NEW_STATE,
 NEW_ZIP,
 NEW_COUNTRY,
 NCOA_DROP,
 DECEASED,
 DMA_DO_NOT_MAIL,
 NEW_ADDRESS_PRESENT,
 ADDR_LINE_1_TXT,
 ADDR_LINE_2_TXT,
 ADDR_LINE_3_TXT,
 STRET_NAME,
 STRET_NUM,
 APT_NUM,
 CITY_NAME,
 TERR_NAME,
 POSTL_AREA_CODE,
 CNTRY_NAME,
 WIN_KEY,
 LOAD_ID,
 LOAD_TS,
 MDM_LOAD_IND
 ,GL_ACCURACY  
 ,GL_MATCH_FLG  
 ,GL_LATITUDE  
 ,GL_LONGITUDE  
 ,DR_CLEANSE_LVL 
 ,VALID_CNTCT_POINT_IND
 ,PR_GEOCODE_FAIL 
 ,PR_REV_GROUP
 ,POSTL_ADDR_ID
FROM  ICRM_STAGE_TBL.NCOA_ADDR_STG;

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 .LABEL L101
 REPLACE VIEW MDM.STORE_STG (
 RETLR_NAME, RETLR_NAME_NTV, PARENT_RETLR_NAME, PARENT_RETLR_NAME_NTV,
                                 STORE_NAME, STORE_NAME_NTV, STORE_PHN_NBR, STORE_TYPE_CODE, ALT_STORE_ID,
                                 DATA_SRCE_NBR, ADDR_LINE_1_TEXT, ADDR_LINE_2_TEXT, ADDR_LINE_3_TEXT,
                                 CITY_NAME, CITY_CODE, TERR_NAME, TERR_CODE, POSTL_AREA_CODE,
                                 CNTRY_CODE, ADDR_LINE_1, ADDR_LINE_2, ADDR_LINE_3, CITY, TERR,
                                 POSTL_AREA_CD, CNTRY_CD, STORE_STATUS_CD, LONG_MEAS, LAT_MEAS,
                                 GL_ACCURACY, GL_MATCH_FLG, DR_CLEANSE_LVL, LOAD_ID, LOAD_TS,
                                 MDM_LOAD_IND,POSTL_ADDR_ID
 
 ) AS LOCKING ROW FOR ACCESS SELECT                RETLR_NAME, RETLR_NAME_NTV, PARENT_RETLR_NAME, PARENT_RETLR_NAME_NTV,
                                 STORE_NAME, STORE_NAME_NTV, STORE_PHN_NBR, STORE_TYPE_CODE, ALT_STORE_ID,
                                 DATA_SRCE_NBR, ADDR_LINE_1_TEXT, ADDR_LINE_2_TEXT, ADDR_LINE_3_TEXT,
                                 CITY_NAME, CITY_CODE, TERR_NAME, TERR_CODE, POSTL_AREA_CODE,
                                 CNTRY_CODE, ADDR_LINE_1, ADDR_LINE_2, ADDR_LINE_3, CITY, TERR,
                                 POSTL_AREA_CD, CNTRY_CD, STORE_STATUS_CD, LONG_MEAS, LAT_MEAS,
                                 GL_ACCURACY, GL_MATCH_FLG, DR_CLEANSE_LVL, LOAD_ID, LOAD_TS,
                                 MDM_LOAD_IND,POSTL_ADDR_ID
FROM   ICRM_STAGE_TBL.STORE_STG;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L102
 REPLACE VIEW MDM.REG_OPT_OUT_STG 
 AS LOCKING ROW FOR ACCESS
 SELECT
 OPTOUT_ID                     ,
 MKTNG_PGM_NBR                 ,
 SUBSCRPTN_OPT_NBR             ,
 FNAME                         ,
 LNAME                         ,
 EMAIL                         ,
 PHONE                         ,
 S_ADD1                        ,
 S_ADD2                        ,
 S_ADD3                        ,
 S_CITY                        ,
 S_STATE                       ,
 S_ZIP                         ,
 S_COUNTRY                     ,
 OPT_OUT_DTTIME                ,
 ADDR_LINE_1_TXT               ,
 ADDR_LINE_2_TXT               ,
 ADDR_LINE_3_TXT               ,
 CITY_NAME                     ,
 TERR_NAME                     ,
 POSTL_AREA_CODE               ,
 CNTRY_CODE                    ,
 LOAD_ID                       ,
 LOAD_TS                       ,
 MDM_LOAD_IND                  ,
 POSTL_ADDR_ID,
 LEGAL_ENT_NBR
 FROM ICRM_STAGE_TBL.REG_OPT_OUT_STG
;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
  .LABEL L103
 
 REPLACE VIEW MDM.REQSTD_INCTV (
  CNSMR_ACTN_ID
 ,TRM_LEAD_KEY
 ,INCTV_NBR
 ,MKTNG_PGM_NBR
 ,PROD_ITEM_UPC
 ,ORDER_NUM
 ,ORDER_STATUS
 ,SHIPPED_DATE
 ,COURIER_URL
 ,TRACKING_NUM
 ,LOG_SOURCE_ID
 ,LOG_UPDATE_USER
 ,LOG_LOAD_ID
) AS LOCKING ROW FOR ACCESS SELECT
  CNSMR_ACTN_ID
 ,TRM_LEAD_KEY
 ,INCTV_NBR
 ,MKTNG_PGM_NBR
 ,PROD_ITEM_UPC
 ,ORDER_NUM
 ,ORDER_STATUS
 ,SHIPPED_DATE
 ,COURIER_URL
 ,TRACKING_NUM
 ,LOG_SOURCE_ID
 ,LOG_UPDATE_USER
 ,LOG_LOAD_ID
FROM iCRM_TBL.REQSTD_INCTV;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;