.logon $TDPID/$TDUSER,$TDPWD

.SET ERRORLEVEL (3807) SEVERITY 0;
.SET ERRORLEVEL (3854) SEVERITY 0; 
.SET ERRORLEVEL (5313) SEVERITY 0;
.SET ERRORLEVEL (3853) SEVERITY 0; 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1 
 DROP TABLE CNSMR_ACTN                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L2 
 DROP TABLE CNSMR_ACTN_SUB_TYPE           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L3 
 DROP TABLE CNSMR_AFFLTN                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L4 
 DROP TABLE CNSMR_GRP                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L5 
 DROP TABLE CNSMR_GRP_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L6 
 DROP TABLE cnsmr_intel_proc              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L7 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L8 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF_VAL   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L9 
 DROP TABLE CNSMR_SCORE_REF               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L10 
 DROP TABLE CNTCT_CHANL_TYPE              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L11 
 DROP TABLE CNTCT_OPT_PGM                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L12 
 DROP TABLE CNTNT_ELEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L13 
 DROP TABLE CNTNT_ELEM_ITEM               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L14 
 DROP TABLE CNTNT_ELEM_TRT                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L15 
 DROP TABLE CNTNT_ELEM_TYPE               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L16 
 DROP TABLE CNTRY                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L17 
 DROP TABLE COCRM_REF_DATA_CONFIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L18 
 DROP TABLE COUPN_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L19 
 DROP TABLE data_srce                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L20 
 DROP TABLE DATA_SRCE_MKTNG_PGM           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L21 
 DROP TABLE DPEND                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L22 
 DROP TABLE DPEND_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L23 
 DROP TABLE DPEND_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L24 
 DROP TABLE EMAIL_FORMT                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L25 
 DROP TABLE ERR_CODE_DETAILS              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L26 
 DROP TABLE GEOC_AREA_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L27 
 DROP TABLE GEOC_REGN                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L28 
 DROP TABLE GEOC_SUB_REGN                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L29 
 DROP TABLE HSHLD_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L30 
 DROP TABLE INCTV                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L31 
 DROP TABLE INCTV_ITEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L32 
 DROP TABLE LANG                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L33 
 DROP TABLE LEGAL_ENT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L34
 DROP TABLE LEGAL_ENT_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L35 
 DROP TABLE LOAD_INFO                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L36 
 DROP TABLE MATCHD_CNSMR_EMAIL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L37 
 DROP TABLE MATCHD_CNSMR_PHONE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L38 
 DROP TABLE MATCHD_CNSMR_POSTL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L39 
 DROP TABLE MATCHD_CNSMR_PRSNA            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L40 
 DROP TABLE MATCHD_CNSMR_SOC_NETK_ACT     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L41 
 DROP TABLE MATCHD_CNSMR_TRT_REF          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L42 
 DROP TABLE MATCHD_CNSMR_WF_USAGE_LOG     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L43 
 DROP TABLE MKTNG_PGM                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L44 
 DROP TABLE MKTNG_PGM_CNTRY_BRAND         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L45 
 DROP TABLE MKTNG_PGM_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L46 
 DROP TABLE MTCHD_CNSMR_SCR_DMN_MAP       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L47 
 DROP TABLE OPT_OUT_NOT_FOUND             ; 
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L48 
 DROP TABLE OPT_OUT_NOT_FOUND_XREF        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L49 
 DROP TABLE PC_ENRICHDATA_CONFIG          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L50 
 DROP TABLE PC_SOURCE_CONFIG              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L51 
 DROP TABLE PET                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L52 
 DROP TABLE PET_BREED                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L53 
 DROP TABLE PET_BREED_SIZE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L54 
 DROP TABLE PET_LIFE_STAGE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L55 
 DROP TABLE PET_TRT                       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L56 
 DROP TABLE PET_TYPE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L57 
 DROP TABLE PREDFND_TRT_VAL               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L58 
 DROP TABLE PRSNA_POSTL_ADDR_ORIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L59 
 DROP TABLE PRSNA_STATUS                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L60 
 DROP TABLE PRSNA_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L61 
 DROP TABLE REGIS_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L62 
 DROP TABLE REGIS_PRSNA_EMAIL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L63 
 DROP TABLE REGIS_PRSNA_OPT_HIST          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L64 
 DROP TABLE REGIS_PRSNA_PHONE             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L65 
 DROP TABLE REGIS_PRSNA_POSTL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L66 
 DROP TABLE REGIS_PRSNA_SOC_NETK_ACT      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L67 
 DROP TABLE REJECT_STRING                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L68
 DROP TABLE RETLR                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L69 
 DROP TABLE RETLR_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L70 
 DROP TABLE RTN_EXTR_CONFIG               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L71 
 DROP TABLE RTN_RULES                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L72 
 DROP TABLE RTN_RULES_DTL                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L73 
 DROP TABLE SALES_CONTR                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L74 
 DROP TABLE STORE                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L75 
 DROP TABLE STORE_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L76 
 DROP TABLE SUBSCRPTN_OPT                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L77 
 DROP TABLE SUBSCRPTN_OPT_TYPE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L78 
 DROP TABLE TERR                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L79 
 DROP TABLE TRILLIUM_OUTPUT               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L80 
 DROP TABLE TRILLIUM_OUTPUT_DUP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L81 
 DROP TABLE TRM_COUPN_LEADKEY_CNTRL       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L82 
 DROP TABLE TRT                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L83 
 DROP TABLE TRT_ENT_TYPE                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L84 
 DROP TABLE WEB_SITE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L85 
 DROP TABLE BRAND; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L86 
 DROP TABLE CNSMR_AFFLTN_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L87 
 DROP TABLE PRSNA_SOC_NETWK_ACCT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L88 
 DROP TABLE PRSNA_PHONE_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L89 
 DROP TABLE PET_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L90 
 DROP TABLE PRSNA_EMAIL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L91 
 DROP TABLE PET_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L92 
 DROP TABLE PRSNA_POSTL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L93 
 DROP TABLE PRSNA_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L94 
 DROP TABLE DPEND_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L95 
 DROP TABLE PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L96 
 DROP TABLE DPEND_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L97 
 DROP TABLE ERR_PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L98 
 DROP table extrn_coupn_status; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  
 
 
  .LABEL LL11 
 DROP TABLE CNSMR_ACTN                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL12 
 DROP TABLE CNSMR_ACTN_SUB_TYPE           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL13 
 DROP TABLE CNSMR_AFFLTN                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL14 
 DROP TABLE CNSMR_GRP                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL15 
 DROP TABLE CNSMR_GRP_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL16 
 DROP TABLE cnsmr_intel_proc              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL17 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL18 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF_VAL   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL19 
 DROP TABLE CNSMR_SCORE_REF               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L110 
 DROP TABLE CNTCT_CHANL_TYPE              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L111 
 DROP TABLE CNTCT_OPT_PGM                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L112 
 DROP TABLE CNTNT_ELEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L113 
 DROP TABLE CNTNT_ELEM_ITEM               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L114 
 DROP TABLE CNTNT_ELEM_TRT                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L115 
 DROP TABLE CNTNT_ELEM_TYPE               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L116 
 DROP TABLE CNTRY                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L117 
 DROP TABLE COCRM_REF_DATA_CONFIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L118 
 DROP TABLE COUPN_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L119 
 DROP TABLE data_srce                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L120 
 DROP TABLE DATA_SRCE_MKTNG_PGM           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L121 
 DROP TABLE DPEND                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L122 
 DROP TABLE DPEND_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L123 
 DROP TABLE DPEND_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L124 
 DROP TABLE EMAIL_FORMT                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L125 
 DROP TABLE ERR_CODE_DETAILS              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L126 
 DROP TABLE GEOC_AREA_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L127 
 DROP TABLE GEOC_REGN                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L128 
 DROP TABLE GEOC_SUB_REGN                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L129 
 DROP TABLE HSHLD_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L130 
 DROP TABLE INCTV                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L131 
 DROP TABLE INCTV_ITEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L132 
 DROP TABLE LANG                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L133 
 DROP TABLE LEGAL_ENT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L134
 DROP TABLE LEGAL_ENT_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L135 
 DROP TABLE LOAD_INFO                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L136 
 DROP TABLE MATCHD_CNSMR_EMAIL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L137 
 DROP TABLE MATCHD_CNSMR_PHONE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L138 
 DROP TABLE MATCHD_CNSMR_POSTL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L139 
 DROP TABLE MATCHD_CNSMR_PRSNA            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L140 
 DROP TABLE MATCHD_CNSMR_SOC_NETK_ACT     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L141 
 DROP TABLE MATCHD_CNSMR_TRT_REF          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L142 
 DROP TABLE MATCHD_CNSMR_WF_USAGE_LOG     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L143 
 DROP TABLE MKTNG_PGM                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L144 
 DROP TABLE MKTNG_PGM_CNTRY_BRAND         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L145 
 DROP TABLE MKTNG_PGM_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L146 
 DROP TABLE MTCHD_CNSMR_SCR_DMN_MAP       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L147 
DROP TABLE OPT_OUT_NOT_FOUND             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L148 
 DROP TABLE OPT_OUT_NOT_FOUND_XREF        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L149 
 DROP TABLE PC_ENRICHDATA_CONFIG          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L150 
 DROP TABLE PC_SOURCE_CONFIG              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L151 
 DROP TABLE PET                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L152 
 DROP TABLE PET_BREED                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L153 
 DROP TABLE PET_BREED_SIZE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L154 
 DROP TABLE PET_LIFE_STAGE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L155 
 DROP TABLE PET_TRT                       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L156 
 DROP TABLE PET_TYPE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L157 
 DROP TABLE PREDFND_TRT_VAL               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L158 
 DROP TABLE PRSNA_POSTL_ADDR_ORIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L159 
 DROP TABLE PRSNA_STATUS                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L160 
 DROP TABLE PRSNA_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L161 
 DROP TABLE REGIS_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L162 
 DROP TABLE REGIS_PRSNA_EMAIL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L163 
 DROP TABLE REGIS_PRSNA_OPT_HIST          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L164 
 DROP TABLE REGIS_PRSNA_PHONE             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L165 
 DROP TABLE REGIS_PRSNA_POSTL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L166 
 DROP TABLE REGIS_PRSNA_SOC_NETK_ACT      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L167 
 DROP TABLE REJECT_STRING                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L168
 DROP TABLE RETLR                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L169 
 DROP TABLE RETLR_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L170 
 DROP TABLE RTN_EXTR_CONFIG               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L171 
 DROP TABLE RTN_RULES                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L172 
 DROP TABLE RTN_RULES_DTL                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L173 
 DROP TABLE SALES_CONTR                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L174 
 DROP TABLE STORE                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L175 
 DROP TABLE STORE_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L176 
 DROP TABLE SUBSCRPTN_OPT                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L177 
 DROP TABLE SUBSCRPTN_OPT_TYPE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L178 
 DROP TABLE TERR                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L179 
 DROP TABLE TRILLIUM_OUTPUT               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L180 
 DROP TABLE TRILLIUM_OUTPUT_DUP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L181 
 DROP TABLE TRM_COUPN_LEADKEY_CNTRL       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L182 
 DROP TABLE TRT                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L183 
 DROP TABLE TRT_ENT_TYPE                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L184 
 DROP TABLE WEB_SITE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L185 
 DROP TABLE BRAND; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L186 
 DROP TABLE CNSMR_AFFLTN_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L187 
 DROP TABLE PRSNA_SOC_NETWK_ACCT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L188 
 DROP TABLE PRSNA_PHONE_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L189 
 DROP TABLE PET_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L190 
 DROP TABLE PRSNA_EMAIL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L191 
 DROP TABLE PET_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L192 
 DROP TABLE PRSNA_POSTL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L193 
 DROP TABLE PRSNA_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L194 
 DROP TABLE DPEND_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L195 
 DROP TABLE PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L196 
 DROP TABLE DPEND_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L197 
 DROP TABLE ERR_PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L198 
 DROP table extrn_coupn_status; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
  
  .LABEL LL21 
 DROP TABLE CNSMR_ACTN                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL22 
 DROP TABLE CNSMR_ACTN_SUB_TYPE           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL23 
 DROP TABLE CNSMR_AFFLTN                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL24 
 DROP TABLE CNSMR_GRP                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL25 
 DROP TABLE CNSMR_GRP_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL26 
 DROP TABLE cnsmr_intel_proc              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL27 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL28 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF_VAL   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL29 
 DROP TABLE CNSMR_SCORE_REF               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L210 
 DROP TABLE CNTCT_CHANL_TYPE              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L211 
 DROP TABLE CNTCT_OPT_PGM                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L212 
 DROP TABLE CNTNT_ELEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L213 
 DROP TABLE CNTNT_ELEM_ITEM               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L214 
 DROP TABLE CNTNT_ELEM_TRT                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L215 
 DROP TABLE CNTNT_ELEM_TYPE               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L216 
 DROP TABLE CNTRY                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L217 
 DROP TABLE COCRM_REF_DATA_CONFIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L218 
 DROP TABLE COUPN_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L219 
 DROP TABLE data_srce                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L220 
 DROP TABLE DATA_SRCE_MKTNG_PGM           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L221 
 DROP TABLE DPEND                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L222 
 DROP TABLE DPEND_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L223 
 DROP TABLE DPEND_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L224 
 DROP TABLE EMAIL_FORMT                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L225 
 DROP TABLE ERR_CODE_DETAILS              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L226 
 DROP TABLE GEOC_AREA_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L227 
 DROP TABLE GEOC_REGN                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L228 
 DROP TABLE GEOC_SUB_REGN                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L229 
 DROP TABLE HSHLD_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L230 
 DROP TABLE INCTV                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L231 
 DROP TABLE INCTV_ITEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L232 
 DROP TABLE LANG                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L233 
 DROP TABLE LEGAL_ENT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L234
 DROP TABLE LEGAL_ENT_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L235 
 DROP TABLE LOAD_INFO                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L236 
 DROP TABLE MATCHD_CNSMR_EMAIL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L237 
 DROP TABLE MATCHD_CNSMR_PHONE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L238 
 DROP TABLE MATCHD_CNSMR_POSTL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L239 
 DROP TABLE MATCHD_CNSMR_PRSNA            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L240 
 DROP TABLE MATCHD_CNSMR_SOC_NETK_ACT     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L241 
 DROP TABLE MATCHD_CNSMR_TRT_REF          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L242 
 DROP TABLE MATCHD_CNSMR_WF_USAGE_LOG     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L243 
 DROP TABLE MKTNG_PGM                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L244 
 DROP TABLE MKTNG_PGM_CNTRY_BRAND         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L245 
 DROP TABLE MKTNG_PGM_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L246 
 DROP TABLE MTCHD_CNSMR_SCR_DMN_MAP       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L247 
 DROP TABLE OPT_OUT_NOT_FOUND             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L248 
 DROP TABLE OPT_OUT_NOT_FOUND_XREF        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L249 
 DROP TABLE PC_ENRICHDATA_CONFIG          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L250 
 DROP TABLE PC_SOURCE_CONFIG              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L251 
 DROP TABLE PET                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L252 
 DROP TABLE PET_BREED                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L253 
 DROP TABLE PET_BREED_SIZE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L254 
 DROP TABLE PET_LIFE_STAGE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L255 
 DROP TABLE PET_TRT                       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L256 
 DROP TABLE PET_TYPE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L257 
 DROP TABLE PREDFND_TRT_VAL               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L258 
 DROP TABLE PRSNA_POSTL_ADDR_ORIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L259 
 DROP TABLE PRSNA_STATUS                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L260 
 DROP TABLE PRSNA_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L261 
 DROP TABLE REGIS_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L262 
 DROP TABLE REGIS_PRSNA_EMAIL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L263 
 DROP TABLE REGIS_PRSNA_OPT_HIST          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L264 
 DROP TABLE REGIS_PRSNA_PHONE             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L265 
 DROP TABLE REGIS_PRSNA_POSTL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L266 
 DROP TABLE REGIS_PRSNA_SOC_NETK_ACT      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L267 
 DROP TABLE REJECT_STRING                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L268
 DROP TABLE RETLR                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L269 
 DROP TABLE RETLR_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L270 
 DROP TABLE RTN_EXTR_CONFIG               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L271 
 DROP TABLE RTN_RULES                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L272 
 DROP TABLE RTN_RULES_DTL                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L273 
 DROP TABLE SALES_CONTR                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L274 
 DROP TABLE STORE                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L275 
 DROP TABLE STORE_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L276 
 DROP TABLE SUBSCRPTN_OPT                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L277 
 DROP TABLE SUBSCRPTN_OPT_TYPE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L278 
 DROP TABLE TERR                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L279 
 DROP TABLE TRILLIUM_OUTPUT               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L280 
 DROP TABLE TRILLIUM_OUTPUT_DUP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L281 
 DROP TABLE TRM_COUPN_LEADKEY_CNTRL       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L282 
 DROP TABLE TRT                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L283 
 DROP TABLE TRT_ENT_TYPE                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L284 
 DROP TABLE WEB_SITE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L285 
 DROP TABLE BRAND; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L286 
 DROP TABLE CNSMR_AFFLTN_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L287 
 DROP TABLE PRSNA_SOC_NETWK_ACCT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L288 
 DROP TABLE PRSNA_PHONE_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L289 
 DROP TABLE PET_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L290 
 DROP TABLE PRSNA_EMAIL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L291 
 DROP TABLE PET_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L292 
 DROP TABLE PRSNA_POSTL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L293 
 DROP TABLE PRSNA_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L294 
 DROP TABLE DPEND_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L295 
 DROP TABLE PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L296 
 DROP TABLE DPEND_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L297 
 DROP TABLE ERR_PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L298 
 DROP table extrn_coupn_status; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

  
  .LABEL LL31 
 DROP TABLE CNSMR_ACTN                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL32 
 DROP TABLE CNSMR_ACTN_SUB_TYPE           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL33 
 DROP TABLE CNSMR_AFFLTN                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL34 
 DROP TABLE CNSMR_GRP                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL35 
 DROP TABLE CNSMR_GRP_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL36 
 DROP TABLE cnsmr_intel_proc              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL37 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL38 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF_VAL   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL39 
 DROP TABLE CNSMR_SCORE_REF               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L310 
 DROP TABLE CNTCT_CHANL_TYPE              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L311 
 DROP TABLE CNTCT_OPT_PGM                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L312 
 DROP TABLE CNTNT_ELEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L313 
 DROP TABLE CNTNT_ELEM_ITEM               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L314 
 DROP TABLE CNTNT_ELEM_TRT                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L315 
 DROP TABLE CNTNT_ELEM_TYPE               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L316 
 DROP TABLE CNTRY                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L317 
 DROP TABLE COCRM_REF_DATA_CONFIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L318 
 DROP TABLE COUPN_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L319 
 DROP TABLE data_srce                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L320 
 DROP TABLE DATA_SRCE_MKTNG_PGM           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L321 
 DROP TABLE DPEND                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L322 
 DROP TABLE DPEND_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L323 
 DROP TABLE DPEND_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L324 
 DROP TABLE EMAIL_FORMT                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L325 
 DROP TABLE ERR_CODE_DETAILS              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L326 
 DROP TABLE GEOC_AREA_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L327 
 DROP TABLE GEOC_REGN                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L328 
 DROP TABLE GEOC_SUB_REGN                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L329 
 DROP TABLE HSHLD_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L330 
 DROP TABLE INCTV                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L331 
 DROP TABLE INCTV_ITEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L332 
 DROP TABLE LANG                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L333 
 DROP TABLE LEGAL_ENT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L334
 DROP TABLE LEGAL_ENT_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L335 
 DROP TABLE LOAD_INFO                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L336 
 DROP TABLE MATCHD_CNSMR_EMAIL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L337 
 DROP TABLE MATCHD_CNSMR_PHONE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L338 
 DROP TABLE MATCHD_CNSMR_POSTL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L339 
 DROP TABLE MATCHD_CNSMR_PRSNA            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L340 
 DROP TABLE MATCHD_CNSMR_SOC_NETK_ACT     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L341 
 DROP TABLE MATCHD_CNSMR_TRT_REF          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L342 
 DROP TABLE MATCHD_CNSMR_WF_USAGE_LOG     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L343 
 DROP TABLE MKTNG_PGM                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L344 
 DROP TABLE MKTNG_PGM_CNTRY_BRAND         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L345 
 DROP TABLE MKTNG_PGM_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L346 
 DROP TABLE MTCHD_CNSMR_SCR_DMN_MAP       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L347 
 DROP TABLE OPT_OUT_NOT_FOUND             ; 
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L348 
 DROP TABLE OPT_OUT_NOT_FOUND_XREF        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L349 
 DROP TABLE PC_ENRICHDATA_CONFIG          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L350 
 DROP TABLE PC_SOURCE_CONFIG              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L351 
 DROP TABLE PET                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L352 
 DROP TABLE PET_BREED                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L353 
 DROP TABLE PET_BREED_SIZE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L354 
 DROP TABLE PET_LIFE_STAGE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L355 
 DROP TABLE PET_TRT                       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L356 
 DROP TABLE PET_TYPE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L357 
 DROP TABLE PREDFND_TRT_VAL               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L358 
 DROP TABLE PRSNA_POSTL_ADDR_ORIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L359 
 DROP TABLE PRSNA_STATUS                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L360 
 DROP TABLE PRSNA_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L361 
 DROP TABLE REGIS_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L362 
 DROP TABLE REGIS_PRSNA_EMAIL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L363 
 DROP TABLE REGIS_PRSNA_OPT_HIST          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L364 
 DROP TABLE REGIS_PRSNA_PHONE             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L365 
 DROP TABLE REGIS_PRSNA_POSTL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L366 
 DROP TABLE REGIS_PRSNA_SOC_NETK_ACT      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L367 
 DROP TABLE REJECT_STRING                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L368
 DROP TABLE RETLR                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L369 
 DROP TABLE RETLR_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L370 
 DROP TABLE RTN_EXTR_CONFIG               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L371 
 DROP TABLE RTN_RULES                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L372 
 DROP TABLE RTN_RULES_DTL                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L373 
 DROP TABLE SALES_CONTR                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L374 
 DROP TABLE STORE                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L375 
 DROP TABLE STORE_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L376 
 DROP TABLE SUBSCRPTN_OPT                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L377 
 DROP TABLE SUBSCRPTN_OPT_TYPE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L378 
 DROP TABLE TERR                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L379 
 DROP TABLE TRILLIUM_OUTPUT               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L380 
 DROP TABLE TRILLIUM_OUTPUT_DUP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L381 
 DROP TABLE TRM_COUPN_LEADKEY_CNTRL       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L382 
 DROP TABLE TRT                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L383 
 DROP TABLE TRT_ENT_TYPE                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L384 
 DROP TABLE WEB_SITE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L385 
 DROP TABLE BRAND; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L386 
 DROP TABLE CNSMR_AFFLTN_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L387 
 DROP TABLE PRSNA_SOC_NETWK_ACCT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L388 
 DROP TABLE PRSNA_PHONE_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L389 
 DROP TABLE PET_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L390 
 DROP TABLE PRSNA_EMAIL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L391 
 DROP TABLE PET_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L392 
 DROP TABLE PRSNA_POSTL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L393 
 DROP TABLE PRSNA_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L394 
 DROP TABLE DPEND_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L395 
 DROP TABLE PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L396 
 DROP TABLE DPEND_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L397 
 DROP TABLE ERR_PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L398 
 DROP table extrn_coupn_status; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

  
  .LABEL LL41 
 DROP TABLE CNSMR_ACTN                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL42 
 DROP TABLE CNSMR_ACTN_SUB_TYPE           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL43 
 DROP TABLE CNSMR_AFFLTN                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL44 
 DROP TABLE CNSMR_GRP                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL45 
 DROP TABLE CNSMR_GRP_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL46 
 DROP TABLE cnsmr_intel_proc              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL47 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL48 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF_VAL   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL49 
 DROP TABLE CNSMR_SCORE_REF               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L410 
 DROP TABLE CNTCT_CHANL_TYPE              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L411 
 DROP TABLE CNTCT_OPT_PGM                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L412 
 DROP TABLE CNTNT_ELEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L413 
 DROP TABLE CNTNT_ELEM_ITEM               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L414 
 DROP TABLE CNTNT_ELEM_TRT                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L415 
 DROP TABLE CNTNT_ELEM_TYPE               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L416 
 DROP TABLE CNTRY                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L417 
 DROP TABLE COCRM_REF_DATA_CONFIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L418 
 DROP TABLE COUPN_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L419 
 DROP TABLE data_srce                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L420 
 DROP TABLE DATA_SRCE_MKTNG_PGM           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L421 
 DROP TABLE DPEND                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L422 
 DROP TABLE DPEND_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L423 
 DROP TABLE DPEND_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L424 
 DROP TABLE EMAIL_FORMT                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L425 
 DROP TABLE ERR_CODE_DETAILS              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L426 
 DROP TABLE GEOC_AREA_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L427 
 DROP TABLE GEOC_REGN                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L428 
 DROP TABLE GEOC_SUB_REGN                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L429 
 DROP TABLE HSHLD_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L430 
 DROP TABLE INCTV                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L431 
 DROP TABLE INCTV_ITEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L432 
 DROP TABLE LANG                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L433 
 DROP TABLE LEGAL_ENT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L434
 DROP TABLE LEGAL_ENT_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L435 
 DROP TABLE LOAD_INFO                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L436 
 DROP TABLE MATCHD_CNSMR_EMAIL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L437 
 DROP TABLE MATCHD_CNSMR_PHONE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L438 
 DROP TABLE MATCHD_CNSMR_POSTL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L439 
 DROP TABLE MATCHD_CNSMR_PRSNA            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L440 
 DROP TABLE MATCHD_CNSMR_SOC_NETK_ACT     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L441 
 DROP TABLE MATCHD_CNSMR_TRT_REF          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L442 
 DROP TABLE MATCHD_CNSMR_WF_USAGE_LOG     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L443 
 DROP TABLE MKTNG_PGM                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L444 
 DROP TABLE MKTNG_PGM_CNTRY_BRAND         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L445 
 DROP TABLE MKTNG_PGM_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L446 
 DROP TABLE MTCHD_CNSMR_SCR_DMN_MAP       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L447 
 DROP TABLE OPT_OUT_NOT_FOUND             ; 
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L448 
 DROP TABLE OPT_OUT_NOT_FOUND_XREF        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L449 
 DROP TABLE PC_ENRICHDATA_CONFIG          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L450 
 DROP TABLE PC_SOURCE_CONFIG              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L451 
 DROP TABLE PET                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L452 
 DROP TABLE PET_BREED                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L453 
 DROP TABLE PET_BREED_SIZE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L454 
 DROP TABLE PET_LIFE_STAGE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L455 
 DROP TABLE PET_TRT                       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L456 
 DROP TABLE PET_TYPE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L457 
 DROP TABLE PREDFND_TRT_VAL               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L458 
 DROP TABLE PRSNA_POSTL_ADDR_ORIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L459 
 DROP TABLE PRSNA_STATUS                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L460 
 DROP TABLE PRSNA_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L461 
 DROP TABLE REGIS_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L462 
 DROP TABLE REGIS_PRSNA_EMAIL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L463 
 DROP TABLE REGIS_PRSNA_OPT_HIST          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L464 
 DROP TABLE REGIS_PRSNA_PHONE             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L465 
 DROP TABLE REGIS_PRSNA_POSTL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L466 
 DROP TABLE REGIS_PRSNA_SOC_NETK_ACT      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L467 
 DROP TABLE REJECT_STRING                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L468
 DROP TABLE RETLR                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L469 
 DROP TABLE RETLR_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L470 
 DROP TABLE RTN_EXTR_CONFIG               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L471 
 DROP TABLE RTN_RULES                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L472 
 DROP TABLE RTN_RULES_DTL                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L473 
 DROP TABLE SALES_CONTR                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L474 
 DROP TABLE STORE                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L475 
 DROP TABLE STORE_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L476 
 DROP TABLE SUBSCRPTN_OPT                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L477 
 DROP TABLE SUBSCRPTN_OPT_TYPE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L478 
 DROP TABLE TERR                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L479 
 DROP TABLE TRILLIUM_OUTPUT               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L480 
 DROP TABLE TRILLIUM_OUTPUT_DUP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L481 
 DROP TABLE TRM_COUPN_LEADKEY_CNTRL       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L482 
 DROP TABLE TRT                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L483 
 DROP TABLE TRT_ENT_TYPE                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L484 
 DROP TABLE WEB_SITE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L485 
 DROP TABLE BRAND; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L486 
 DROP TABLE CNSMR_AFFLTN_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L487 
 DROP TABLE PRSNA_SOC_NETWK_ACCT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L488 
 DROP TABLE PRSNA_PHONE_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L489 
 DROP TABLE PET_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L490 
 DROP TABLE PRSNA_EMAIL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L491 
 DROP TABLE PET_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L492 
 DROP TABLE PRSNA_POSTL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L493 
 DROP TABLE PRSNA_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L494 
 DROP TABLE DPEND_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L495 
 DROP TABLE PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L496 
 DROP TABLE DPEND_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L497 
 DROP TABLE ERR_PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L498 
 DROP table extrn_coupn_status; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
  
  
  .LABEL LL51 
 DROP TABLE CNSMR_ACTN                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL52 
 DROP TABLE CNSMR_ACTN_SUB_TYPE           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL53 
 DROP TABLE CNSMR_AFFLTN                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL54 
 DROP TABLE CNSMR_GRP                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL55 
 DROP TABLE CNSMR_GRP_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL56 
 DROP TABLE cnsmr_intel_proc              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL57 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL58 
 DROP TABLE CNSMR_INTEL_TRUSTED_REF_VAL   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL LL59 
 DROP TABLE CNSMR_SCORE_REF               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L510 
 DROP TABLE CNTCT_CHANL_TYPE              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L511 
 DROP TABLE CNTCT_OPT_PGM                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L512 
 DROP TABLE CNTNT_ELEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L513 
 DROP TABLE CNTNT_ELEM_ITEM               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L514 
 DROP TABLE CNTNT_ELEM_TRT                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L515 
 DROP TABLE CNTNT_ELEM_TYPE               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L516 
 DROP TABLE CNTRY                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L517 
 DROP TABLE COCRM_REF_DATA_CONFIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L518 
 DROP TABLE COUPN_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L519 
 DROP TABLE data_srce                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L520 
 DROP TABLE DATA_SRCE_MKTNG_PGM           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L521 
 DROP TABLE DPEND                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L522 
 DROP TABLE DPEND_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L523 
 DROP TABLE DPEND_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L524 
 DROP TABLE EMAIL_FORMT                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L525 
 DROP TABLE ERR_CODE_DETAILS              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L526 
 DROP TABLE GEOC_AREA_TYPE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L527 
 DROP TABLE GEOC_REGN                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L528 
 DROP TABLE GEOC_SUB_REGN                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L529 
 DROP TABLE HSHLD_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L530 
 DROP TABLE INCTV                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L531 
 DROP TABLE INCTV_ITEM                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L532 
 DROP TABLE LANG                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L533 
 DROP TABLE LEGAL_ENT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L534
 DROP TABLE LEGAL_ENT_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L535 
 DROP TABLE LOAD_INFO                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L536 
 DROP TABLE MATCHD_CNSMR_EMAIL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L537 
 DROP TABLE MATCHD_CNSMR_PHONE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L538 
 DROP TABLE MATCHD_CNSMR_POSTL_ADDR       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L539 
 DROP TABLE MATCHD_CNSMR_PRSNA            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L540 
 DROP TABLE MATCHD_CNSMR_SOC_NETK_ACT     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L541 
 DROP TABLE MATCHD_CNSMR_TRT_REF          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L542 
 DROP TABLE MATCHD_CNSMR_WF_USAGE_LOG     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L543 
 DROP TABLE MKTNG_PGM                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L544 
 DROP TABLE MKTNG_PGM_CNTRY_BRAND         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L545 
 DROP TABLE MKTNG_PGM_TRAIT_MAP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L546 
 DROP TABLE MTCHD_CNSMR_SCR_DMN_MAP       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L547 
 DROP TABLE OPT_OUT_NOT_FOUND             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L548 
 DROP TABLE OPT_OUT_NOT_FOUND_XREF        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L549 
 DROP TABLE PC_ENRICHDATA_CONFIG          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L550 
 DROP TABLE PC_SOURCE_CONFIG              ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L551 
 DROP TABLE PET                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L552 
 DROP TABLE PET_BREED                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L553 
 DROP TABLE PET_BREED_SIZE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L554 
 DROP TABLE PET_LIFE_STAGE                ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L555 
 DROP TABLE PET_TRT                       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L556 
 DROP TABLE PET_TYPE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L557 
 DROP TABLE PREDFND_TRT_VAL               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L558 
 DROP TABLE PRSNA_POSTL_ADDR_ORIG         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L559 
 DROP TABLE PRSNA_STATUS                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L560 
 DROP TABLE PRSNA_TRT                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L561 
 DROP TABLE REGIS_PRSNA                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L562 
 DROP TABLE REGIS_PRSNA_EMAIL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L563 
 DROP TABLE REGIS_PRSNA_OPT_HIST          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L564 
 DROP TABLE REGIS_PRSNA_PHONE             ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L565 
 DROP TABLE REGIS_PRSNA_POSTL_ADDR        ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L566 
 DROP TABLE REGIS_PRSNA_SOC_NETK_ACT      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L567 
 DROP TABLE REJECT_STRING                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L568
 DROP TABLE RETLR                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L569 
 DROP TABLE RETLR_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L570 
 DROP TABLE RTN_EXTR_CONFIG               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L571 
 DROP TABLE RTN_RULES                     ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L572 
 DROP TABLE RTN_RULES_DTL                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L573 
 DROP TABLE SALES_CONTR                   ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L574 
 DROP TABLE STORE                         ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L575 
 DROP TABLE STORE_TYPE                    ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L576 
 DROP TABLE SUBSCRPTN_OPT                 ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L577 
 DROP TABLE SUBSCRPTN_OPT_TYPE            ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L578 
 DROP TABLE TERR                          ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L579 
 DROP TABLE TRILLIUM_OUTPUT               ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L580 
 DROP TABLE TRILLIUM_OUTPUT_DUP           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L581 
 DROP TABLE TRM_COUPN_LEADKEY_CNTRL       ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L582 
 DROP TABLE TRT                           ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L583 
 DROP TABLE TRT_ENT_TYPE                  ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L584 
 DROP TABLE WEB_SITE                      ; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L585 
 DROP TABLE BRAND; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L586 
 DROP TABLE CNSMR_AFFLTN_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L587 
 DROP TABLE PRSNA_SOC_NETWK_ACCT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L588 
 DROP TABLE PRSNA_PHONE_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L589 
 DROP TABLE PET_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L590 
 DROP TABLE PRSNA_EMAIL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L591 
 DROP TABLE PET_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L592 
 DROP TABLE PRSNA_POSTL_ADDR_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L593 
 DROP TABLE PRSNA_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L594 
 DROP TABLE DPEND_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L595 
 DROP TABLE PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L596 
 DROP TABLE DPEND_TRT_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L597 
 DROP TABLE ERR_PRSNA_STG; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L598 
 DROP table extrn_coupn_status; 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 
 