
.logon $TDPID/$TDUSER,$TDPWD


.SET ERROROUT STDOUT;
.SET SESSION CHARSET 'UTF8';

DATABASE MDM;
.GOTO $Step


.LABEL L0
DROP TABLE DEPLOY_WORK.PRSNA_TRT_DUP1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L1
DROP TABLE DEPLOY_WORK.PRSNA_TRT_DUP2;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L2
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_POSTL_ADDR_DUP1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L3
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_POSTL_ADDR_DUP2;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L4
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_EMAIL_ADDR_DUP1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L5
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_EMAIL_ADDR_DUP2;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L6
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_PHONE_DUP1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L7
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_PHONE_DUP2;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L8
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_SOC_NET_ACCT_DUP1;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L9
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_SOC_NET_ACCT_DUP2;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L10
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_POSTL_ADDR_572;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L11
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_EMAIL_ADDR_572;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L12
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_PHONE_572;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L13
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_SOC_NET_ACCT_572;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L14
DROP TABLE DEPLOY_WORK.PRSNA_TRT_572;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


.LABEL L15
DROP TABLE DEPLOY_WORK.REGIS_PRSNA_572;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;


