.logon $TDPID/$TDUSER,$TDPWD
 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
INSERT INTO MDM.ATTRIBUTE_VALUES SEL * FROM DEPLOY_WORK.ATTRIBUTE_VALUES_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L2
INSERT INTO MDM.ATTRIBUTE_TYPES SEL * FROM DEPLOY_WORK.ATTRIBUTE_TYPES_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L3
INSERT INTO MDM.ATTRIBUTE_TYPES_HIERARCHY SEL * FROM DEPLOY_WORK.ATTRIBUTE_TYPES_HIERARCHY_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L4
INSERT INTO MDM.ATTRIBUTE_VALUES_HIERARCHY SEL * FROM DEPLOY_WORK.ATTRIBUTE_VALUES_HIERARCHY_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L5
INSERT INTO MDM.ATTRIBUTE_TYPES_RELN SEL * FROM DEPLOY_WORK.ATTRIBUTE_TYPES_RELN_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L6
INSERT INTO MDM.ATTRIBUTE_VALUES_RELN SEL * FROM DEPLOY_WORK.ATTRIBUTE_VALUES_RELN_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L7
INSERT INTO MDM.RPT_ADDR_QLTY SEL * FROM DEPLOY_WORK.RPT_ADDR_QLTY_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L8
INSERT INTO MDM.RPT_CNSMR_NBR SEL * FROM DEPLOY_WORK.RPT_CNSMR_NBR_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L9
INSERT INTO MDM.RPT_DATA_NBR SEL * FROM DEPLOY_WORK.RPT_DATA_NBR_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L10
INSERT INTO MDM.RPT_LOAD_NBR SEL * FROM DEPLOY_WORK.RPT_LOAD_NBR_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L11
INSERT INTO MDM.tss_cntry_table_map SEL * FROM DEPLOY_WORK.tss_cntry_table_map_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L12
INSERT INTO MDM.ENV_NM SEL * FROM DEPLOY_WORK.ENV_NM_MDM_56;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L13
DROP TABLE MDM.ERR_PRSNA_STG;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L14
RENAME TABLE MDM.ERR_PRSNA_STG_BKUP_56 TO ERR_PRSNA_STG;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L15
DEL FROM upld_tmplt_prps WHERE NAME='EntityINCTVTemplate';
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L16
DEL FROM upld_tmplt_prps WHERE NAME='EntityCNTNT_ELEMTemplate';
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L17
INSERT INTO MDM.upld_tmplt_prps SEL * FROM DEPLOY_WORK.upld_tmplt_prps_MDM_56 WHERE NAME='EntityINCTVTemplate';
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L18
INSERT INTO MDM.upld_tmplt_prps SEL * FROM DEPLOY_WORK.upld_tmplt_prps_MDM_56 WHERE NAME='EntityCNTNT_ELEMTemplate';
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L19
UPDATE upld_tmplt SET API_NAME='excelCntntUpload',service_name='BCM_MASTER' WHERE display_name='CNTNT_ELEM';
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L20
UPDATE upld_tmplt SET API_NAME='excelInctvUpload',service_name='BCM_MASTER' WHERE display_name='INCTV';
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 .LABEL L21
update upld_tmplt
set service_name='BCM_MASTER',
API_NAME='subscriptionOptExcelUpload'
WHERE NAME='EntitySUBSCRPTN_OPTTemplate';
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L22
DROP TABLE MDM.GT_STORE;								
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L23 
DROP TABLE MDM.LD_STORE;								
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;								
.LABEL L24								
CREATE SET GLOBAL TEMPORARY TABLE MDM.GT_STORE ,NO FALLBACK ,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     LOG
     (
      STORE_NBR FLOAT NOT NULL,
      RETLR_NBR INTEGER,
      STORE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STORE_STATUS_CD CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      ADDR_LINE_1_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ADDR_LINE_2_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ADDR_LINE_3_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STRET_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STRET_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STORE_TYPE_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      CITY_CODE INTEGER,
      TERR_CODE CHAR(8) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CNTRY_CODE CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC,
      POSTL_AREA_CODE VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      LAT_MEAS DECIMAL(8,6),
      LONG_MEAS DECIMAL(9,6),
      DATA_SRCE_NBR INTEGER,
      LOG_SOURCE_ID DECIMAL(18,0),
      LOG_UPDATE_USER VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOG_LOAD_ID VARCHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC,
      STORE_NAME_NTV VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      APT_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PO_BOX_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CITY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TERR_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      GL_MATCH_FLG VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DR_CLEANSE_LVL INTEGER,
      ALT_STORE_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      STORE_PHN_NBR VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID_CNTCT_POINT_IND CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      PR_GEOCODE_FAIL VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      TQ_GOUT_MATCH_LEVEL VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      PR_REV_GROUP VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      GL_ACCURACY INTEGER,
      SYS_TARGET_ID INTEGER,
      SYS_AUTH_ID VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_SOURCE VARCHAR(256) CHARACTER SET LATIN NOT CASESPECIFIC DEFAULT 'BackEnd',
      SYS_CREATED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATION_DATE TIMESTAMP(0),
      SYS_ENT_STATE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ),
      SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
      SYS_NC_TYPE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_CODE VARCHAR(10000) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ),
      SYS_FILTER VARCHAR(60) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_WORKFLOW_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LOAD_ID VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC, 
CONSTRAINT STORE_PK PRIMARY KEY ( STORE_NBR ))

ON COMMIT DELETE ROWS;                        
                                
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;  
.LABEL L25  
CREATE MULTISET TABLE MDM.LD_STORE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      STORE_NBR FLOAT,
      RETLR_NBR INTEGER,
      STORE_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STORE_STATUS_CD CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      ADDR_LINE_1_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ADDR_LINE_2_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ADDR_LINE_3_TXT VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STRET_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STRET_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      STORE_TYPE_CODE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      CITY_CODE INTEGER,
      TERR_CODE CHAR(8) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CNTRY_CODE CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC,
      POSTL_AREA_CODE VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      LAT_MEAS DECIMAL(8,6),
      LONG_MEAS DECIMAL(9,6),
      DATA_SRCE_NBR INTEGER,
      LOG_SOURCE_ID DECIMAL(18,0),
      LOG_UPDATE_USER VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOG_LOAD_ID VARCHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC,
      STORE_NAME_NTV VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      APT_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PO_BOX_NUM VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CITY_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      TERR_NAME VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      GL_MATCH_FLG VARCHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DR_CLEANSE_LVL INTEGER,
      ALT_STORE_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      STORE_PHN_NBR VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALID_CNTCT_POINT_IND CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      PR_GEOCODE_FAIL VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      TQ_GOUT_MATCH_LEVEL VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      PR_REV_GROUP VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      GL_ACCURACY INTEGER,
      SYS_TARGET_ID INTEGER,
      SYS_AUTH_ID VARCHAR(1000) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_SOURCE VARCHAR(256) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATION_DATE TIMESTAMP(0),
      SYS_ENT_STATE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LAST_MODIFIED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
      SYS_NC_TYPE VARCHAR(25) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_CODE VARCHAR(10000) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LOAD_ID VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_WORKFLOW_ID VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( STORE_NBR );
								
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L26
 REPLACE VIEW MDM.ERR_CODE_DETAILS
AS
LOCKING ROW FOR ACCESS
SELECT LOAD_ID,
MKTNG_PGM_NBR,
SYS_ERR_CODE AS ERR_DESC,
COUNT(DISTINCT REGIS_CNSMR_ID_VAL) ERROR_CODE_NBR
FROM MDM.ERR_PRSNA_STG
GROUP BY 1,2,3;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
