.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
REPLACE VIEW MDM.REGIS_PRSNA_RTN_PRE_RUN_RPT AS SEL * FROM  icrm_tbl.REGIS_PRSNA_RTN_PRE_RUN_RPT;


 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L2


CREATE SET TABLE MDM.MKTNG_PGM_BRAND_GRP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CNTCT_NBR INTEGER NOT NULL,
      MKTNG_PGM_NBR INTEGER NOT NULL,
      MKTNG_PGM_GRP VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      BRAND_CODE VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      BRAND_NAME VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SYS_SOURCE VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_TARGET_ID INTEGER,
      SYS_AUTH_ID VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATED_BY VARCHAR(70) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_CREATION_DATE TIMESTAMP(0),
      SYS_LAST_MODIFIED_DATE TIMESTAMP(0),
      SYS_ENT_STATE VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_LAST_MODIFIED_BY VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_NC_TYPE VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_CODE VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      SYS_ERR_SVRTY VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX MKTNG_PGM_NUPI ( CNTCT_NBR ,MKTNG_PGM_NBR ,MKTNG_PGM_GRP );


 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L3
 INSERT INTO ATTRIBUTE_TYPES 
(ATTRIBUTE_TYPE_ID,ATTRIBUTE_TYPE,DISPLAY_NAME,DATA_TYPE,DATA_FORMAT,DATA_LENGTH,SELECTION_METHOD,
AV_CODE_FLAG,AV_SHORT_NAME_FLAG,USER_MANAGED_FLAG,SYS_SOURCE,SYS_CREATION_DATE,SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,SYS_LAST_MODIFIED_DATE) 
VALUES 
(
(SEL MAX(ATTRIBUTE_TYPE_ID)+1 FROM ATTRIBUTE_TYPES),'RR13-Number of Reports to Retain','RR13-Number of Reports to Retain','Text','YYYY-MM-DD',20,'Default','Y','Y','C','Backend',CURRENT_TIMESTAMP(0),
'ACTIVE','RELEASE 6.3',CURRENT_TIMESTAMP(0)
)
;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 
 .LABEL L4
INSERT INTO ATTRIBUTE_VALUES
(AV_ID,ATTRIBUTE_TYPE_ID,ACTIVE_FLAG,AV_DESCRIPTION,AV_CODE,AV_SHORT_NAME,SYS_SOURCE,SYS_CREATED_BY,SYS_CREATION_DATE,SYS_ENT_STATE)
VALUES
(
3,(SEL MAX(ATTRIBUTE_TYPE_ID) FROM ATTRIBUTE_TYPES),'Y','RR13-Number of Reports to Retain','RR13','RR13-Number of Reports to Retain','Backend','RELEASE 6.3',CURRENT_TIMESTAMP(0),'ACTIVE'
)
;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

   .LABEL L5 
 REPLACE VIEW MDM.PUBLISH_ORIGAMI_RPT
( 
DATE_AS_OF,
REPORT_NAME,
PUBLISH_IND
) 
AS
LOCKING ROW FOR ACCESS 
SELECT
DATE_AS_OF,
REPORT_NAME,
PUBLISH_IND
FROM BI_INSIGHT.BI_PUBLISH_ORIGAMI_RPT_V A;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L6
 
 REPLACE VIEW MDM.BI_SOURCE_ORIGAMI_V
( 
DATE_AS_OF,
CNTRY_CODE,
COUNTRY,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MKTNG_PGM_DESC ,
CONSUMER_GENDER,
CONSUMER_AGE_GROUP,
DPEND_CNT ,
DATA_SRCE_NBR ,
DATA_SOURCE ,
ONLINE_CONTACT ,
OFFLINE_CONTACT ,
MOBILE_CONTACT ,
ANY_CONTACT ,
CUMM_VALID_OPT_IN ,
MONTHLY_VALID_OPT_IN ,
MONTHLY_OPT_OUT ,
NEW_INDIVIDUAL ,
NEW_DEPENDENT ,
STRATEGIC_TARGET ,
TOTAL_ACTIVE  ,
CONTACTED_CONSUMER  ,
TOTAL_ACTION ,
TRIAL_N_PURCHASE ,
INSRT_DT
) 
AS
LOCKING ROW FOR ACCESS 
SELECT
A.DATE_AS_OF,
CNTRY_CODE,
COUNTRY,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MKTNG_PGM_DESC ,
CONSUMER_GENDER,
CONSUMER_AGE_GROUP,
DPEND_CNT   ,
DATA_SRCE_NBR ,
DATA_SOURCE ,
ONLINE_CONTACT ,
OFFLINE_CONTACT ,
MOBILE_CONTACT ,
ANY_CONTACT ,
CUMM_VALID_OPT_IN ,
MONTHLY_VALID_OPT_IN ,
MONTHLY_OPT_OUT ,
NEW_INDIVIDUAL ,
NEW_DEPENDENT ,
STRATEGIC_TARGET ,
TOTAL_ACTIVE  ,
CONTACTED_CONSUMER ,
TOTAL_ACTION ,
TRIAL_N_PURCHASE ,
INSRT_DT
FROM BI_INSIGHT.BI_SOURCE_ORIGAMI_V A
INNER JOIN MDM.PUBLISH_ORIGAMI_RPT POR
ON A.DATE_AS_OF = POR.DATE_AS_OF
AND POR.REPORT_NAME = 'BI_SOURCE_ORIGAMI'
AND PUBLISH_IND = 'Y';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 .LABEL L7

REPLACE VIEW MDM.BI_BABYCARE_REACH_DETAIL_ORIGAMI_V
(
DATE_AS_OF,
COUNTRY ,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MKTNG_PGM_DESC ,
DPEND_AGE_GROUP ,
ONLINE_CONTACT ,
OFFLINE_CONTACT ,
MOBILE_CONTACT ,
ANY_CONTACT ,
CUMM_VALID_OPT_IN 
)
AS
LOCKING ROW FOR ACCESS 
SELECT
A.DATE_AS_OF,
COUNTRY ,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MKTNG_PGM_DESC ,
DPEND_AGE_GROUP ,
ONLINE_CONTACT ,
OFFLINE_CONTACT ,
MOBILE_CONTACT ,
ANY_CONTACT ,
CUMM_VALID_OPT_IN 
FROM BI_INSIGHT.BI_BABYCARE_REACH_DETAIL_ORIGAMI_V A
INNER JOIN MDM.PUBLISH_ORIGAMI_RPT POR
ON A.DATE_AS_OF = POR.DATE_AS_OF
AND POR.REPORT_NAME = 'BI_BABYCARE_REACH_DETAIL_ORIGAMI'
AND PUBLISH_IND = 'Y';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 .LABEL L8

REPLACE VIEW MDM.BI_ONLINE_CAMPAIGN_ORIGAMI_V
(
DATE_AS_OF,
COUNTRY ,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MKTNG_PGM_DESC ,
CAMPAIGN_NAME ,
OBJECTIVE ,
AUTOMATED ,
MULTI_STEP ,
ONLINE_CONTACT ,
OFFLINE_CONTACT ,
MOBILE_CONTACT ,
ANY_CONTACT ,
UNQ_SENT ,
UNQ_DELIVERED ,
UNQ_OPENED ,
UNQ_CLICKED ,
OPT_OUT ,
INSRT_DT 
)
AS
LOCKING ROW FOR ACCESS 
SELECT
A.DATE_AS_OF,
COUNTRY ,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MKTNG_PGM_DESC ,
CAMPAIGN_NAME ,
OBJECTIVE ,
AUTOMATED ,
MULTI_STEP ,
ONLINE_CONTACT ,
OFFLINE_CONTACT ,
MOBILE_CONTACT ,
ANY_CONTACT ,
UNQ_SENT ,
UNQ_DELIVERED ,
UNQ_OPENED ,
UNQ_CLICKED ,
OPT_OUT ,
INSRT_DT
FROM BI_INSIGHT.BI_ONLINE_CAMPAIGN_ORIGAMI_V A
INNER JOIN MDM.PUBLISH_ORIGAMI_RPT POR
ON A.DATE_AS_OF = POR.DATE_AS_OF
AND POR.REPORT_NAME = 'BI_ONLINE_CAMPAIGN_ORIGAMI'
AND PUBLISH_IND = 'Y';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 .LABEL L9

REPLACE VIEW MDM.BI_CONSUMER_ACTION_ORIGAMI_V
(
DATE_AS_OF,
COUNTRY ,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MKTNG_PGM_DESC ,
ONLINE_CONTACT,
OFFLINE_CONTACT,
MOBILE_CONTACT,
ANY_CONTACT ,
CNSMR_ACTN_TYPE_NAME ,
CNSMR_ACTN_SUB_TYPE_CODE ,
CNSMR_ACTN_SUB_TYPE_NAME ,
TOTAL_NO_CNSMR_ACTN_MONTHLY ,
CUMM_NON_UNQ_CNT  ,
UNIQUE_NO_CNSMR_ACTN_MONTHLY ,
STRATEGIC_MONTHLY_UNQ_CNT ,
INSRT_DT 
)
AS
LOCKING ROW FOR ACCESS 
SELECT
A.DATE_AS_OF,
COUNTRY ,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MKTNG_PGM_DESC ,
ONLINE_CONTACT,
OFFLINE_CONTACT,
MOBILE_CONTACT,
ANY_CONTACT ,
CNSMR_ACTN_TYPE_NAME ,
CNSMR_ACTN_SUB_TYPE_CODE ,
CNSMR_ACTN_SUB_TYPE_NAME ,
TOTAL_NO_CNSMR_ACTN_MONTHLY ,
CUMM_NON_UNQ_CNT  ,
UNIQUE_NO_CNSMR_ACTN_MONTHLY ,
STRATEGIC_MONTHLY_UNQ_CNT ,
INSRT_DT
FROM BI_INSIGHT.BI_CONSUMER_ACTION_ORIGAMI_V A
INNER JOIN MDM.PUBLISH_ORIGAMI_RPT POR
ON A.DATE_AS_OF = POR.DATE_AS_OF
AND POR.REPORT_NAME = 'BI_CONSUMER_ACTION_ORIGAMI'
AND PUBLISH_IND = 'Y';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 .LABEL L10

REPLACE VIEW MDM.BI_JOLT_CRM_EXPORT_CAMPAIGN_V
(
DATE_AS_OF,
COUNTRY ,
MASTER_MKTNG_PGM_NBR,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
CAMPAIGN_NAME ,
BRAND ,
MNTHLY_UNIQUE_OPENED ,
MNTHLY_UNIQUE_CLICKED ,
MNTHLY_UNIQUE_DELIVERED ,
YTD_UNIQUE_OPENED ,
YTD_UNIQUE_CLICKED 
)
AS
LOCKING ROW FOR ACCESS 
SELECT
A.DATE_AS_OF,
COUNTRY ,
MASTER_MKTNG_PGM_NBR,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
CAMPAIGN_NAME ,
BRAND ,
MNTHLY_UNIQUE_OPENED ,
MNTHLY_UNIQUE_CLICKED ,
MNTHLY_UNIQUE_DELIVERED ,
YTD_UNIQUE_OPENED ,
YTD_UNIQUE_CLICKED 
FROM BI_INSIGHT.BI_JOLT_CRM_EXPORT_CAMPAIGN_V A
INNER JOIN MDM.PUBLISH_ORIGAMI_RPT POR
ON A.DATE_AS_OF = POR.DATE_AS_OF
AND POR.REPORT_NAME = 'BI_JOLT_CRM_EXPORT_CAMPAIGN'
AND PUBLISH_IND = 'Y';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

 .LABEL L11
REPLACE VIEW MDM.BI_JOLT_CRM_EXPORT_NEW_V
(
DATE_AS_OF,
LEGAL_ENT_NAME,
COUNTRY ,
MASTER_MKTNG_PGM_NBR ,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MNTHLY_TOTAL_ACTIVE ,
MNTHLY_ONLINE_CONTACT ,
MNTHLY_UNIQUE_OPENED ,
MNTHLY_UNIQUE_CLICKED ,
MNTHLY_UNIQUE_DELIVERED ,
MNTHLY_UNIQUE_OPENED_FEMALE ,
MNTHLY_UNIQUE_CLICKED_FEMALE ,
MNTHLY_UNIQUE_DELIEVRED_FEMALE ,
MNTHLY_ONLINE_CONTACT_FEMALE ,
MONTHLY_VALID_OPT_INS ,
MNTHLY_REGISTERED ,
MNTHLY_TOTAL_UNIQUE_TRIALISTS ,
MNTHLY_UNIQUE_TRIALISTS_PI ,
MNTHLY_UNIQUE_TRIALISTS_RR ,
MNTHLY_UNIQUE_TRIALISTS_RC ,
MNTHLY_UNIQUE_TRIALISTS_RS_FT ,
MNTHLY_UNIQUE_TRIALISTS_RS_WOM ,
MNTHLY_UNIQUE_TRIALISTS_ST ,
YTD_TOTAL_ACTIVE ,
YTD_UNIQUE_OPENED ,
YTD_UNIQUE_CLICKED ,
YTD_UNIQUE_DELIVERED ,
YTD_UNIQUE_OPENED_FEMALE ,
YTD_UNIQUE_CLICKED_FEMALE ,
YTD_UNIQUE_DELIVERED_FEMALE ,
YTD_ONLINE_CONTACT_FEMALE ,
YTD_ONLINE_CONTACT ,
YTD_VALID_OPT_INS ,
YTD_REGISTERED ,
YTD_TOTAL_UNIQUE_TRIALISTS ,
YTD_UNIQUE_TRIALISTS_PI ,
YTD_UNIQUE_TRIALISTS_RR ,
YTD_UNIQUE_TRIALISTS_RC ,
YTD_UNIQUE_TRIALISTS_RS_FT ,
YTD_UNIQUE_TRIALISTS_RS_WOM ,
YTD_UNIQUE_TRIALISTS_ST
)
AS
LOCKING ROW FOR ACCESS 
SELECT
A.DATE_AS_OF,
LEGAL_ENT_NAME,
COUNTRY ,
MASTER_MKTNG_PGM_NBR ,
MKTNG_PGM_NBR ,
MKTNG_PGM_NAME ,
MNTHLY_TOTAL_ACTIVE ,
MNTHLY_ONLINE_CONTACT ,
MNTHLY_UNIQUE_OPENED ,
MNTHLY_UNIQUE_CLICKED ,
MNTHLY_UNIQUE_DELIVERED ,
MNTHLY_UNIQUE_OPENED_FEMALE ,
MNTHLY_UNIQUE_CLICKED_FEMALE ,
MNTHLY_UNIQUE_DELIEVRED_FEMALE ,
MNTHLY_ONLINE_CONTACT_FEMALE ,
MONTHLY_VALID_OPT_INS ,
MNTHLY_REGISTERED ,
MNTHLY_TOTAL_UNIQUE_TRIALISTS ,
MNTHLY_UNIQUE_TRIALISTS_PI ,
MNTHLY_UNIQUE_TRIALISTS_RR ,
MNTHLY_UNIQUE_TRIALISTS_RC ,
MNTHLY_UNIQUE_TRIALISTS_RS_FT ,
MNTHLY_UNIQUE_TRIALISTS_RS_WOM ,
MNTHLY_UNIQUE_TRIALISTS_ST ,
YTD_TOTAL_ACTIVE ,
YTD_UNIQUE_OPENED ,
YTD_UNIQUE_CLICKED ,
YTD_UNIQUE_DELIVERED ,
YTD_UNIQUE_OPENED_FEMALE ,
YTD_UNIQUE_CLICKED_FEMALE ,
YTD_UNIQUE_DELIVERED_FEMALE ,
YTD_ONLINE_CONTACT_FEMALE ,
YTD_ONLINE_CONTACT ,
YTD_VALID_OPT_INS ,
YTD_REGISTERED ,
YTD_TOTAL_UNIQUE_TRIALISTS ,
YTD_UNIQUE_TRIALISTS_PI ,
YTD_UNIQUE_TRIALISTS_RR ,
YTD_UNIQUE_TRIALISTS_RC ,
YTD_UNIQUE_TRIALISTS_RS_FT ,
YTD_UNIQUE_TRIALISTS_RS_WOM ,
YTD_UNIQUE_TRIALISTS_ST 
FROM BI_INSIGHT.BI_JOLT_CRM_EXPORT_NEW_V A
INNER JOIN MDM.PUBLISH_ORIGAMI_RPT POR
ON A.DATE_AS_OF = POR.DATE_AS_OF
AND POR.REPORT_NAME = 'BI_JOLT_CRM_EXPORT_NEW'
AND PUBLISH_IND = 'Y';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 