.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step
 
.LABEL L1
REPLACE VIEW DEPLOY_WORK.V_SRC_EMAIL_DETAIL_R62BKP  
AS   
LOCKING ROW FOR ACCESS   
SELECT DISTINCT A.SOURCE_ID,   
A.REQ_MAIL_ID,   
A.AGN_CON_MAIL_ID,   
B.LOAD_ID   
FROM ETL_CTRL.SOURCE_CONTROL A   
INNER JOIN ETL_CTRL.LOAD_CONTROL B   
ON A.SOURCE_ID = B.SOURCE_ID   
AND B.LOAD_TYPE='ETL'   
AND B.LOAD_ID IN(SEL LOAD_ID FROM MDM.MDM_LOAD_CONTROL)   
INNER JOIN MDM.LOAD_INFO LI   
ON B.LOAD_ID = LI.LOAD_ID   
AND LI.PROCESS_NAME='Wrapper'   
AND LI.STATUS = 'Success';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L2

REPLACE VIEW DEPLOY_WORK.V_RPT_LOAD_NBR_R62BKP
AS   
LOCKING ROW FOR ACCESS   
SELECT    
A.LOAD_ID,   
B.SOURCE_ID,   
B.REQ_MAIL_ID,   
B.DATA_SOURCE,   
A.MKTNG_PGM_NBR,   
A.LEGAL_ENT_NBR,   
M.MKTNG_PGM_NAME,   
L.LEGAL_ENT_NAME,   
STAGING_NBR,   
C.STG_REJECT_CNT,   
C.STG_REJECT_DESC,   
ERROR_NBR,   
ACTIVE_NBR,   
DUPLICATE_NBR,   
WEBSITE_REGIS_NBR,
PHONE_OPT_IN,   
PHONE_OPT_OUT,   
EMAIL_OPT_IN,   
EMAIL_OPT_OUT,   
POSTAL_OPT_IN,   
POSTAL_OPT_OUT,   
SOCIAL_OPT_IN,   
SOCIAL_OPT_OUT,   
LOADSTATUS AS LOAD_SUCCESS,    
CAST(LOADSTARTTS AS DATE FORMAT 'mm/dd/yyyy') AS START_DATE,   
CAST(LOADENDTS AS DATE FORMAT 'mm/dd/yyyy') AS END_DATE   
FROM RPT_LOAD_NBR A   
LEFT OUTER JOIN (   
SELECT b.SOURCE_ID,   
b.DATA_SOURCE,   
b.REQ_MAIL_ID,   
a.LOAD_ID,   
LOADSTATUS,   
MIN(LOADSTARTTS) LOADSTARTTS,   
MAX(LOADENDTS) LOADENDTS   
FROM   
ETL_CTRL.LOAD_CONTROL a   
INNER JOIN ETL_CTRL.SOURCE_CONTROL b   
ON b.SOURCE_ID=a.SOURCE_ID   
AND LOADSTATUS='Success'   
GROUP BY 1,2,3,4,5   
) B   
ON A.LOAD_ID=B.LOAD_ID   
LEFT OUTER JOIN   
(SELECT LOAD_ID,   
 (CASE WHEN SOURCECNT = TARGETCNT   
   THEN 0
   ELSE  REJECTSCNT END)AS STG_REJECT_CNT,
FailedReason AS STG_REJECT_DESC   
FROM   
 ETL_CTRL.LOAD_CONTROL  
WHERE LOAD_TYPE='ETL'   
)C   
ON B.LOAD_ID=C.LOAD_ID   
LEFT OUTER JOIN MKTNG_PGM M   
ON M.MKTNG_PGM_NBR = A.MKTNG_PGM_NBR   
LEFT OUTER JOIN LEGAL_ENT L   
ON L.LEGAL_ENT_NBR = A.LEGAL_ENT_NBR   
;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L3

REPLACE VIEW DEPLOY_WORK.Format_Control_R62BKP (
FORMAT_ID                     
,FORMAT_NAME                   
,FILE_TYPE                     
,FILE_DELIMITER                
,FILE_NAMING                   
,FORMAT_OWNER                  
,OWNER_EMAIL_ID                
,InboundDir    
	) AS LOCKING ROW FOR ACCESS SELECT
FORMAT_ID                     
,FORMAT_NAME                   
,FILE_TYPE                     
,FILE_DELIMITER                
,FILE_NAMING                   
,FORMAT_OWNER                  
,OWNER_EMAIL_ID                
,InboundDir
FROM etl_ctrl.Format_Control;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L4

REPLACE VIEW DEPLOY_WORK.SOURCE_CONTROL_R62BKP (
SOURCE_ID, DATA_SOURCE, REQ_NAME, REQ_MAIL_ID, DATA_TRANS,
                   DATA_COLL, AGENCY_REQ_NM, AGN_CON_MAIL_ID, REQUEST_DT, PG_APPR_DT,
                   AGENCY_APPR_DT, PROD_DT, BRAND, AGN_CON_NAME, ADDRESS_1, ADDRESS_2,
                   CITY, STATE, COUNTRY, POSTAL_CODE, PHONE_NUMBER
                   ) AS LOCKING ROW FOR ACCESS SELECT
SOURCE_ID, DATA_SOURCE, REQ_NAME, REQ_MAIL_ID, DATA_TRANS,
                   DATA_COLL, AGENCY_REQ_NM, AGN_CON_MAIL_ID, REQUEST_DT, PG_APPR_DT,
                   AGENCY_APPR_DT, PROD_DT, BRAND, AGN_CON_NAME, ADDRESS_1, ADDRESS_2,
                   CITY, STATE, COUNTRY, POSTAL_CODE, PHONE_NUMBER
                   FROM ETL_CTRL.SOURCE_CONTROL;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
				   
.LABEL L5
UPDATE UPLD_TMPLT SET SERVICE_NAME='BCM_MASTER', API_NAME='excelAGNCYMSTRRequest' WHERE DISPLAY_NAME='AGNCY_MSTR';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L6
 
 INSERT INTO ID_SQR (DOC_NAME, SEQ_NR) VALUES ('AGENCY_NBR_SEQ',1);
 
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L7
 
 INSERT INTO ID_SQR (DOC_NAME, SEQ_NR) VALUES ('HNDLR_ID_SEQ',1);
 
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
.LABEL L8
 
 REPLACE VIEW MDM.GDPR_BRODCAST_HIST_V
(EXTRACT_ID
,GDPR_CASE_ID
,GDPR_CASE_RQST_TYPE
,CNTRY_CODE
,SUPPLIER_QUAD
,SENT_TIMESTAMP
,SYS_LAST_MODIFIED_DATE
,LOAD_ID
,GDPR_RQST_STATUS_CD
)
AS 
LOCKING ROW FOR ACCESS  SEL
GBH.EXTRACT_ID
,GBH.GDPR_CASE_ID
,GBH.GDPR_CASE_RQST_TYPE
,GBH.CNTRY_CODE
,GBH.SUPPLIER_QUAD
,GBH.SENT_TIMESTAMP
,GBH.SYS_LAST_MODIFIED_DATE
,GBH.LOAD_ID
,GBH.GDPR_RQST_STATUS_CD 
FROM iCRM_STAGE_TBL.GDPR_BRODCAST_HIST GBH;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 
.LABEL L9

REPLACE VIEW MDM.V_AGNCY_EMAIL_DETAIL  (SOURCE_ID        ,             
REQ_MAIL_ID                   ,
AGN_CON_MAIL_ID          ,     
LOAD_ID                       )
AS   
LOCKING ROW FOR ACCESS   
SELECT DISTINCT AGNCY.AGNCY_NBR AS SOURCE_ID,   
CNTCT.EMAIL_ADDR_TXT AS REQ_MAIL_ID,   
CNTCT.EMAIL_ADDR_TXT AS AGN_CON_MAIL_ID,    
B.LOAD_ID AS LOAD_ID
FROM AGNCY INNER JOIN AGNCY_CNTCT
ON AGNCY_CNTCT.AGNCY_NBR = AGNCY.AGNCY_NBR
AND AGNCY_CNTCT.CNTCT_NBR = AGNCY.RQSTR_CNTCT_NBR
INNER JOIN CNTCT
ON AGNCY_CNTCT.CNTCT_NBR = CNTCT.CNTCT_NBR   
INNER JOIN ETL_CTRL.LOAD_CONTROL B   
ON AGNCY.AGNCY_NBR = B.SOURCE_ID   
AND B.LOAD_TYPE='ETL'   
AND B.LOAD_ID IN(SEL LOAD_ID FROM MDM.MDM_LOAD_CONTROL)   
INNER JOIN MDM.LOAD_INFO LI   
ON B.LOAD_ID = LI.LOAD_ID   
AND LI.PROCESS_NAME='Wrapper'   
AND LI.STATUS = 'Success';

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
.LABEL L10

 REPLACE VIEW MDM.V_SRC_EMAIL_DETAIL   (SOURCE_ID        ,             
REQ_MAIL_ID                   ,
AGN_CON_MAIL_ID          ,     
LOAD_ID                       )
AS   
LOCKING ROW FOR ACCESS   
SELECT DISTINCT AGNCY.AGNCY_NBR AS SOURCE_ID,   
CNTCT1.EMAIL_ADDR_TXT AS REQ_MAIL_ID,   
OReplace(tdstats.udfconcat(Trim(CNTCT.EMAIL_ADDR_TXT )),'"','') AS AGN_CON_MAIL_ID,     
B.LOAD_ID AS LOAD_ID
FROM MDM.AGNCY AGNCY LEFT JOIN MDM.AGNCY_CNTCT AGNCY_CNTCT
ON AGNCY_CNTCT.AGNCY_NBR = AGNCY.AGNCY_NBR
LEFT JOIN MDM.CNTCT CNTCT
ON AGNCY_CNTCT.CNTCT_NBR = CNTCT.CNTCT_NBR
LEFT JOIN MDM.CNTCT CNTCT1
 ON CNTCT1.CNTCT_NBR = AGNCY.RQSTR_CNTCT_NBR  --                    CHANGED JOIN AS PER SRI
INNER JOIN ETL_CTRL.LOAD_CONTROL B   
ON AGNCY.AGNCY_NBR = B.SOURCE_ID   
AND B.LOAD_TYPE='ETL'   
AND B.LOAD_ID IN(SEL LOAD_ID FROM MDM.MDM_LOAD_CONTROL)   
INNER JOIN MDM.LOAD_INFO LI   
ON B.LOAD_ID = LI.LOAD_ID   
AND LI.PROCESS_NAME='Wrapper'   
AND LI.STATUS = 'Success'
GROUP BY 1,2,4;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
.LABEL L11

REPLACE VIEW MDM.V_RPT_LOAD_NBR (
LOAD_ID                       
,SOURCE_ID                     
,REQ_MAIL_ID                   
,DATA_SOURCE                   
,MKTNG_PGM_NBR                 
,LEGAL_ENT_NBR                 
,MKTNG_PGM_NAME                
,LEGAL_ENT_NAME                
,STAGING_NBR                   
,STG_REJECT_CNT                
,STG_REJECT_DESC               
,ERROR_NBR                     
,ACTIVE_NBR                    
,DUPLICATE_NBR                 
,WEBSITE_REGIS_NBR             
,PHONE_OPT_IN                  
,PHONE_OPT_OUT                 
,EMAIL_OPT_IN                  
,EMAIL_OPT_OUT                 
,POSTAL_OPT_IN                 
,POSTAL_OPT_OUT                
,SOCIAL_OPT_IN                 
,SOCIAL_OPT_OUT                
,LOAD_SUCCESS                  
,START_DATE                    
,END_DATE                      

)
AS   
LOCKING ROW FOR ACCESS   
SELECT     DISTINCT
A.LOAD_ID,   
AGNCY.AGNCY_NBR,   
OREPLACE(tdstats.udfconcat(TRIM(CNTCT.EMAIL_ADDR_TXT )),'"','')  AS EMAIL_ADDR_TXT,   
B.AGNCY_NM,   
A.MKTNG_PGM_NBR,   
A.LEGAL_ENT_NBR,   
M.MKTNG_PGM_NAME,   
L.LEGAL_ENT_NAME,   
STAGING_NBR,   
C.STG_REJECT_CNT,   
C.STG_REJECT_DESC,   
ERROR_NBR,   
ACTIVE_NBR,   
DUPLICATE_NBR,   
WEBSITE_REGIS_NBR,
PHONE_OPT_IN,   
PHONE_OPT_OUT,   
EMAIL_OPT_IN,   
EMAIL_OPT_OUT,   
POSTAL_OPT_IN,   
POSTAL_OPT_OUT,   
SOCIAL_OPT_IN,   
SOCIAL_OPT_OUT,   
LOADSTATUS AS LOAD_SUCCESS,    
CAST(LOADSTARTTS AS DATE FORMAT 'mm/dd/yyyy') AS START_DATE,   
CAST(LOADENDTS AS DATE FORMAT 'mm/dd/yyyy') AS END_DATE   
FROM MDM.RPT_LOAD_NBR A   
LEFT OUTER JOIN ( SELECT AGNCY.AGNCY_NBR
      ,AGNCY.AGNCY_NM
      ,CNTCT.EMAIL_ADDR_TXT
      ,A.LOAD_ID
      ,A.LOADSTATUS
      ,MIN(LOADSTARTTS) LOADSTARTTS 
      ,MAX(LOADENDTS) LOADENDTS 
FROM   
ETL_CTRL.LOAD_CONTROL A  INNER JOIN MDM.AGNCY 
ON AGNCY.AGNCY_NBR = A.SOURCE_ID    
AND A.LOADSTATUS='Success'   
INNER JOIN MDM.CNTCT 
ON CNTCT.CNTCT_NBR = AGNCY.RQSTR_CNTCT_NBR  --                    CHANGED JOIN AS PER SRI
GROUP BY 1,2,3,4,5  
) B   
ON A.LOAD_ID=B.AGNCY_NBR   
LEFT OUTER JOIN   
(SELECT LOAD_ID,   
 (CASE WHEN SOURCECNT = TARGETCNT   
   THEN 0
   ELSE  REJECTSCNT END)AS STG_REJECT_CNT,
FailedReason AS STG_REJECT_DESC   
FROM   
 ETL_CTRL.LOAD_CONTROL  
WHERE LOAD_TYPE='ETL'   
)C   
ON B.AGNCY_NBR=C.LOAD_ID   
LEFT OUTER JOIN MKTNG_PGM M   
ON M.MKTNG_PGM_NBR = A.MKTNG_PGM_NBR   
LEFT OUTER JOIN LEGAL_ENT L   
ON L.LEGAL_ENT_NBR = A.LEGAL_ENT_NBR   
GROUP BY 1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
;


 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
.LABEL L12
REPLACE VIEW MDM. Format_Control    (
FORMAT_ID                     
,FORMAT_NAME                   
,FILE_TYPE                     
,FILE_DELIMITER                
,FILE_NAMING                   
,FORMAT_OWNER                  
,OWNER_EMAIL_ID                
,InboundDir    
		) AS LOCKING ROW FOR ACCESS SELECT

DISTINCT 
INTRFC.INTRFC_NBR 	
,INTRFC.INTRFC_NM
,INTRFC.FILE_TYPE
,INTRFC.FILE_DELIMITER
,INTRFC.FILE_NAMING
, COALESCE(CNTCT.FIRST_NM,'')||' '||COALESCE(CNTCT.LAST_NM,'')   AS  FORMAT_OWNER
,CNTCT.EMAIL_ADDR_TXT
,Null
FROM MDM.INTRFC 
LEFT JOIN MDM.CNTCT
ON CNTCT.CNTCT_NBR = INTRFC.INTRFC_CNTCT_NBR ;

 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
.LABEL L13
REPLACE VIEW MDM.SOURCE_CONTROL        
 AS
  LOCKING ROW FOR ACCESS SELECT 
                 AGNCY.AGNCY_NBR AS SOURCE_ID
                 ,AGNCY.AGNCY_NM AS DATA_SOURCE
                 ,CNTCT1.FIRST_NM||' '||CNTCT1.LAST_NM AS REQ_NAME
                 ,CNTCT1.EMAIL_ADDR_TXT AS REQ_MAIL_ID
                 ,case when AGNCY.TRNS_IND ='Y' then AGNCY.AGNCY_NM end AS DATA_TRANS
                 ,case when AGNCY.SPLR_IND ='Y'  then AGNCY.AGNCY_NM end AS DATA_COLL
                ,cast(Oreplace(tdstats.udfconcat(CNTCT.FIRST_NM||' ' ||CNTCT.LAST_NM),'"','') as varchar(1000)) AS AGENCY_REQ_NM
               	 ,cast(OReplace(tdstats.udfconcat(Trim(CNTCT.EMAIL_ADDR_TXT )),'"','') as varchar(1000))     AS AGN_CON_MAIL_ID
                 ,AGNCY.REQSTD_DT AS REQUEST_DT
                 ,AGNCY.ACTV_DT AS PG_APPR_DT
                 ,null AS AGENCY_APPR_DT
                 ,AGNCY.ACTV_DT AS PROD_DT
                ,cast(Oreplace(tdstats.udfconcat(AGNCY_INTRFC.BRAND_SPLR_LST),'"','') as varchar(1000)) as BRAND_SPLR_LST
                 ,cast(Oreplace(tdstats.udfconcat(CNTCT.FIRST_NM||' ' ||CNTCT.LAST_NM),'"','') as varchar(1000)) AS AGN_CON_NAME
                    ,coalesce(CNTCT.ADDR_LINE_1_TXT,'') AS ADDRESS_1
                 ,coalesce(CNTCT.ADDR_LINE_2_TXT,'') AS ADDRESS_2
                 ,coalesce(CNTCT.CITY_NAME,'') AS CITY
                 ,coalesce(CNTCT.TERR_NAME,'') AS STATE
                 ,coalesce(CNTCT.CNTRY_CODE,'') AS COUNTRY
                 ,coalesce(CNTCT.POSTL_AREA_CODE,'') AS POSTAL_CODE
                 ,coalesce(CNTCT.FULL_PHONE_NUM,'') AS PHONE_NUMBER

FROM MDM.AGNCY LEFT OUTER JOIN MDM.AGNCY_CNTCT
ON AGNCY_CNTCT.AGNCY_NBR = AGNCY.AGNCY_NBR
LEFT OUTER JOIN MDM.CNTCT
ON AGNCY_CNTCT.CNTCT_NBR = CNTCT.CNTCT_NBR
LEFT OUTER JOIN MDM.CNTCT CNTCT1
ON CNTCT.CNTCT_NBR = AGNCY.RQSTR_CNTCT_NBR  
LEFT OUTER JOIN MDM.AGNCY_INTRFC
ON  AGNCY.AGNCY_NBR = AGNCY_INTRFC.AGNCY_NBR

GROUP BY 1,2,3,4,5,6,9,10,11,12,15,16,17,18,19,20,21 ;
 
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L14
 ALTER TABLE MDM.GDPR_PROPS
  ADD EMAIL_RTTM_SUFFIX VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC;

  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L15
UPDATE MDM.GDPR_PROPS
SET EMAIL_RTTM_SUFFIX='@invalid.rttm.pg.com'
WHERE ENV_NM='GRS';

   .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 
  .LABEL L16
  INSERT INTO ID_SQR (DOC_NAME, SEQ_NR) VALUES ('CNTCT_ID_SEQ',1);
 
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L17
  INSERT INTO ID_SQR (DOC_NAME, SEQ_NR) VALUES ('AGNCY_INTRFC_ID_SEQ',1);
 
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;