

.logon $TDPID/$TDUSER,$TDPWD

.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1
REPLACE VIEW MDM.V_SAMPLE (                                                                                                   
MKTNG_PGM_NBR
,REGIS_PRSNA_ID
,CNSMR_ACTN_TYPE_CODE
,CNSMR_ACTN_NUM
,LEGAL_ENT_NBR
,CNSMR_ACTN_ID
,INCTV_NBR
,PROD_ITEM_NUM
,ORDER_NUM
,ORDER_STATUS
,SHIPPED_DATE
,COURIER_URL
,TRACKING_NBR
 ,SYS_TARGET_ID,
 SYS_AUTH_ID,
 SYS_SOURCE,
 SYS_CREATED_BY,
 SYS_CREATION_DATE,
 SYS_ENT_STATE,
 SYS_LAST_MODIFIED_BY,
 SYS_LAST_MODIFIED_DATE,
 SYS_NC_TYPE,
 SYS_ERR_CODE,
 SYS_ERR_SVRTY
)AS LOCKING ROW FOR ACCESS
SELECT
CA.MKTNG_PGM_NBR
,CA.REGIS_PRSNA_ID
,CA.CNSMR_ACTN_TYPE_CODE
,CA.CNSMR_ACTN_NUM
,CA.LEGAL_ENT_NBR
,RQI.CNSMR_ACTN_ID
,RQI.INCTV_NBR
,RQI.PROD_ITEM_UPC
,RQI.ORDER_NUM
,RQI.ORDER_STATUS
,RQI.SHIPPED_DATE
,RQI.COURIER_URL
,RQI.TRACKING_NUM
,NULL (INTEGER)   AS  SYS_TARGET_ID,
NULL (VARCHAR(25))  AS SYS_AUTH_ID,
NULL (VARCHAR(25))  AS SYS_SOURCE,
NULL (VARCHAR(70))  AS SYS_CREATED_BY,
NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE,
'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE,
NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY,
NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE, 
NULL (VARCHAR(25))  AS SYS_NC_TYPE,
NULL (VARCHAR(10000))  AS SYS_ERR_CODE,
NULL (VARCHAR(30))  AS SYS_ERR_SVRTY                                                           
FROM REQSTD_INCTV RQI
LEFT JOIN
CNSMR_ACTN CA
ON
RQI.CNSMR_ACTN_ID=CA.CNSMR_ACTN_ID
WHERE CA.CNSMR_ACTN_TYPE_CODE = 'RS'
AND RQI.ORDER_STATUS = 'D'
;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L2
REPLACE VIEW MDM.V_COUPON_REDEEMED (                                                                                      
MKTNG_PGM_NBR	
,REGIS_PRSNA_ID	
,CNSMR_ACTN_TYPE_CODE
,CNSMR_ACTN_NUM
,LEGAL_ENT_NBR
,CNSMR_ACTN_ID
,COUPN_SERL_NUM
,RDMPT_DATETM
,COUPN_STATUS_CODE
,STORE_NAME
,REDEMPTN_VALUE
,SYS_TARGET_ID,
SYS_AUTH_ID,
SYS_SOURCE,
SYS_CREATED_BY,
SYS_CREATION_DATE,
SYS_ENT_STATE,
SYS_LAST_MODIFIED_BY,
SYS_LAST_MODIFIED_DATE,
SYS_NC_TYPE,
SYS_ERR_CODE,
SYS_ERR_SVRTY
)
AS LOCKING ROW FOR ACCESS 
SELECT
CA.MKTNG_PGM_NBR
,CA.REGIS_PRSNA_ID
,CA.CNSMR_ACTN_TYPE_CODE
,CA.CNSMR_ACTN_NUM
,CA.LEGAL_ENT_NBR
,RDM.CNSMR_ACTN_ID
,RDM.COUPN_SERL_NUM
,RDM.RDMPT_DATETM
,RDM.COUPN_STATUS_CODE
,RDM.ALT_STORE_NAME
,RDM.REDEMPTN_VALUE
,NULL (INTEGER)   AS  SYS_TARGET_ID,
NULL (VARCHAR(25))  AS SYS_AUTH_ID,
NULL (VARCHAR(25))  AS SYS_SOURCE,
NULL (VARCHAR(70))  AS SYS_CREATED_BY,
NULL (TIMESTAMP(0))  AS SYS_CREATION_DATE,
'ACTIVE'  (VARCHAR(25))  AS  SYS_ENT_STATE,
NULL (VARCHAR(70))  AS SYS_LAST_MODIFIED_BY,
NULL (TIMESTAMP(0))  AS SYS_LAST_MODIFIED_DATE, 
NULL (VARCHAR(25))  AS SYS_NC_TYPE,
NULL (VARCHAR(10000))  AS SYS_ERR_CODE,
NULL (VARCHAR(30))  AS SYS_ERR_SVRTY                                                         
FROM MDM.COUPN_INSTN_REDEMPTN RDM
LEFT JOIN
MDM.CNSMR_ACTN CA
ON
RDM.CNSMR_ACTN_ID=CA.CNSMR_ACTN_ID
WHERE COUPN_STATUS_CODE = 'CD' 
;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L3
 REPLACE VIEW MDM.CURR_LYLTY_TRANS_DATA AS
 LOCKING ROW FOR ACCESS 
 SELECT 
 LAS.MKTNG_PGM_NBR, 
 LAS.LYLTY_ACCT_NUM, 
 LAS.LYLTY_PGM_NBR, 
 LTRE.LYLTY_TRANX_DATETM AS LYLTY_ACCT_STMT_DATE, 
 CASE LTRE.LYLTY_TRANX_TYPE_CODE 
 WHEN 'E' THEN 'EARN'
 WHEN 'B' THEN 'BURN'
 ELSE NULL
 END AS LYLTY_TRANX_TYPE_NAME, 
 LTRE.EARND_PTS_QTY, 
 LTRE.RDMD_PTS_QTY, 
 LRE.LYLTY_REWARD_NAME 
 FROM 
 MDM.LYLTY_ACCT_DETAILS LAS 
 LEFT OUTER JOIN MDM.LYLTY_TRANX LTRE 
 ON LAS.LYLTY_ACCT_NUM=LTRE.LYLTY_ACCT_NUM
 AND LAS.MKTNG_PGM_NBR= LTRE.MKTNG_PGM_NBR
 AND LAS.LYLTY_PGM_NBR=LTRE.LYLTY_PGM_NBR
 AND LYLTY_TRANX_TYPE_CODE IN ('E' , 'B') 
 LEFT OUTER JOIN MDM.LYLTY_REWARD LRE 
 ON LTRE.MKTNG_PGM_NBR= LRE.MKTNG_PGM_NBR 
 AND LTRE.LYLTY_PGM_NBR=LRE.LYLTY_PGM_NBR
 AND LTRE.LYLTY_REWARD_CODE = LRE.LYLTY_REWARD_CODE
QUALIFY rank() over (partition by LAS.LYLTY_ACCT_NUM, LAS.MKTNG_PGM_NBR, LTRE.LYLTY_TRANX_TYPE_CODE ORDER BY LTRE.LYLTY_TRANX_NUM DESC)=1;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
 
 .LABEL L4
 REPLACE VIEW MDM.LYLTY_ACCT_DETAILS AS LOCK ROW FOR ACCESS
 SEL 
 LAS.*,
 LL.LYLTY_LVL_NAME
 FROM
 MDM.LYLTY_ACCT_STMT LAS
 LEFT OUTER JOIN MDM.LYLTY_LVL LL 
 ON
 LAS.MKTNG_PGM_NBR = LL.MKTNG_PGM_NBR
 AND
 LAS.LYLTY_PGM_NBR = LL.LYLTY_PGM_NBR
 AND
 LAS.LYLTY_LVL_CODE =LL.LYLTY_LVL_CODE
 QUALIFY RANK() OVER (PARTITION BY LAS.LYLTY_ACCT_NUM, LAS.MKTNG_PGM_NBR ORDER BY LAS.LYLTY_ACCT_STMT_DATE DESC)=1
;
.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;