.logon $TDPID/$TDUSER,$TDPWD


.SET ERROROUT STDOUT;
.SET SESSION CHARSET 'UTF8';

DATABASE MDM;
.GOTO $Step


.LABEL L0
CREATE TABLE DEPLOY_WORK.SCHDL_CNTRY_SCHDLIN_BKP AS MDM.SCHDL_CNTRY WITH DATA AND STATS;

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L0A
CREATE TABLE DEPLOY_WORK.SCHDL_ID_SCHDLIN_BKP AS MDM.SCHDL_ID WITH DATA AND STATS;

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
	  
.LABEL L1
INS MDM.SCHDL_CNTRY(SCHDL_ID,CNTRY_NM)
SEL 100,'AFR' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'ARB' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'AUS' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'AUT' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'BEL' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'BGR' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'BRA' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'CAN' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'CHE' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'CHN' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'CZE' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'DEU' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'DNK' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'EGY' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'ESP' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'FIN' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'FRA' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'GBR' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'GRC' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'HKG' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'HRV' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'HUN' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'IND' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'IRL' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'ISR' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'ITA' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'JPN' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'KOR' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'LAT' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'MYS' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'NLD' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'NOR' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'NZL' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'OTH' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'PAK' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'PHL' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'POL' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'PRT' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'ROU' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'RUS' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'SGP' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'SWE' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'TUR' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'TWN' FROM MDM.LOAD_INFO GROUP BY 1 UNION
SEL 100,'USA' FROM MDM.LOAD_INFO GROUP BY 1 ;

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.LABEL L2
INS SCHDL_ID
(SCHDL_ID,SCHDL_STRT_TM,SCHDL_END_TM)
VALUES(100,'00:00:00','23:59:59');

.IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;