.logon $TDPID/$TDUSER,$TDPWD

.SET ERRORLEVEL (3807) SEVERITY 0;
.SET ERRORLEVEL (3854) SEVERITY 0; 
.SET ERRORLEVEL (5313) SEVERITY 0;
.SET ERRORLEVEL (3853) SEVERITY 0; 
.SET ERROROUT STDOUT ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.SET SESSION CHARSET 'UTF8' ;
 .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

.GOTO $Step

.LABEL L1 
DROP TABLE MDM.AGNCY_CNTCT;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L2
DROP TABLE MDM.AGNCY;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L3
DROP TABLE MDM.AGNCY_STATUS;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L4
DROP TABLE MDM.CNTCT;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;
.LABEL L5
DROP table GDPR_RQST_TYPE;
  .IF ERRORLEVEL > 0 THEN .QUIT ERRORCODE;

