
CREATE MULTISET TABLE MDM.TEST_CNSMR_SCORE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SYS_ERR_CODE VARCHAR(50000) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( SYS_ERR_CODE );

-------------------------------------------------------------------------------
REPLACE PROCEDURE mdm.SP_CNSMR_SCORE(IN LEGAL_ENT_NBR INTEGER)
BEGIN  
DECLARE V_SQL VARCHAR(30000);
DECLARE V_SQL1 VARCHAR(30000);
DECLARE V_SQL2 VARCHAR(30000);
DECLARE V_LEGAL_ENT_NBR INTEGER;
DECLARE V_DEBUG_MESSAGE VARCHAR(255); 
DECLARE V_CNSMR_SCORE_NBR INTEGER;
DECLARE V_CNSMR_SCORE_NAME VARCHAR(300);
DECLARE V_COL_DSPL_TYPE_TXT VARCHAR(300);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
RESIGNAL SET MESSAGE_TEXT = V_DEBUG_MESSAGE;
END;
SET V_LEGAL_ENT_NBR=TRIM(CAST(LEGAL_ENT_NBR AS INTEGER));
SET V_SQL='REPLACE VIEW mdm.MATCHD_CNSMR_SCORE_'||TRIM(CAST(LEGAL_ENT_NBR AS INTEGER))||'
AS
SEL
A.LEGAL_ENT_NBR,
MATCHD_CNSMR_PRSNA_ID,';
SET V_SQL2='/**/';
SET V_LEGAL_ENT_NBR=LEGAL_ENT_NBR;
FOR
TABLE_LST AS C1 CURSOR FOR
    SELECT A.CNSMR_SCORE_NBR,A.CNSMR_SCORE_NAME,A.COL_DSPL_TYPE_TXT
    FROM MDM.CNSMR_SCORE_REF A
    INNER JOIN MDM.mtchd_cnsmr_scr_dmn_map B
    ON A.CNSMR_SCORE_NBR=B.CNSMR_SCORE_NBR
    WHERE LEGAL_ENT_NBR=V_LEGAL_ENT_NBR
	AND B.SYS_ENT_STATE='ACTIVE'
DO


SET V_CNSMR_SCORE_NAME=TABLE_LST.CNSMR_SCORE_NAME;
SET V_CNSMR_SCORE_NBR=TABLE_LST.CNSMR_SCORE_NBR;
SET V_COL_DSPL_TYPE_TXT=TABLE_LST.COL_DSPL_TYPE_TXT;

IF V_COL_DSPL_TYPE_TXT='BOTH' THEN
SET V_SQL1='Max(CASE WHEN A.CNSMR_SCORE_NBR='||V_CNSMR_SCORE_NBR||'
THEN CASE WHEN B.COL_DSPL_TYPE_TXT= '||''''||'BOTH'||''''||' THEN CNSMR_SCORE_AMT End
 END) AS '||V_CNSMR_SCORE_NAME||'_AMT,
 MAX(CASE WHEN A.CNSMR_SCORE_NBR='||V_CNSMR_SCORE_NBR||'
THEN CASE WHEN B.COL_DSPL_TYPE_TXT='||''''||'BOTH'||''''||'  THEN CNSMR_SCORE_VAL End
 END) AS '||V_CNSMR_SCORE_NAME||'_VAL ,';
ELSE
SET V_SQL1='Max(CASE WHEN A.CNSMR_SCORE_NBR='||V_CNSMR_SCORE_NBR||'
THEN CASE WHEN B.COL_DSPL_TYPE_TXT='''||V_COL_DSPL_TYPE_TXT||''' THEN ' ||V_COL_DSPL_TYPE_TXT||' End
 END) AS '||V_CNSMR_SCORE_NAME||' ,';
 END IF;
SET V_SQL2=V_SQL2||V_SQL1;

END FOR;
SET V_SQL=V_SQL||' '||V_SQL2;
SET V_SQL=TRIM(TRAILING ',' FROM V_SQL);
SET V_SQL=V_SQL||' FROM MDM.MATCHD_CNSMR_SCORE A
inner JOIN MDM.CNSMR_SCORE_REF B
ON A.CNSMR_SCORE_NBR=B.CNSMR_SCORE_NBR
inner join mdm.mtchd_cnsmr_scr_dmn_map C
 ON B.CNSMR_SCORE_NBR=C.CNSMR_SCORE_NBR
WHERE A.LEGAL_ENT_NBR='||V_LEGAL_ENT_NBR||
'AND C.SYS_ENT_STATE='||''''||'ACTIVE'||''''||' 
GROUP BY 1,2;';

INSERT INTO MDM.TEST_CNSMR_SCORE
SEL V_SQL;
CALL DBC.SYSEXECSQL(V_SQL);   

END;
----------------------------------------------------------------------------
CALL MDM.SP_CNSMR_SCORE(15);
----------------------------------------------------------------------------
CALL MDM.SP_CNSMR_SCORE(20);
